-- Generated from installed mission data. Do not edit.
-- Zones are authored state rows; population and event sites come from the slice sets.
return function(mission, freeroam)
    local unit = freeroam.unit
    return {
        {
            state = mission.states.STATE_80F4696A_0005_0000_80F46ACD,
            region = 40,
            patrol = {
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_0_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_0_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_1_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_1_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_2_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_2_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_5_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_5_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_0_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_0_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_1_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_1_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_2_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_2_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_0_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_0_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_1_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_1_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_2_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_2_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_0_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_0_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_1_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_1_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_2_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_2_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_0_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_0_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_1_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_1_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_2_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_2_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_0_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_0_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_1_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_1_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_3_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_3_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_4_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_4_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_5_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_5_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_6_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_6_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_0_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_0_80F55922),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_1_80F55922, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_1_80F55922),
            },
        },
        {
            state = mission.states.STATE_80F4696A_0006_0000_80F46ACE,
            region = 48,
            patrol = {
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_LEFT_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_LEFT_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_LEFT_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_LEFT_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_LEFT_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_LEFT_80F5A530),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_MIDDLE_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_MIDDLE_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_MIDDLE_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_MIDDLE_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_MIDDLE_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_MIDDLE_80F5A530),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_RIGHT_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_RIGHT_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_RIGHT_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_RIGHT_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_RIGHT_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_CENTER_RIGHT_80F5A530),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_A_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_A_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_A_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_A_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_A_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_A_80F5A530),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_B_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_B_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_B_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_B_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_B_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_LEFT_B_80F5A530),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_A_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_A_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_A_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_A_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_A_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_A_80F5A530),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_B_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_B_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_B_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_B_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_B_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_DROPSHIP_RIGHT_B_80F5A530),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_KNIGHT_SWORD_BACK_80F5A0FB, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_KNIGHT_SWORD_BACK_80F5A0FB),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_KNIGHT_SWORD_BACK_80F5A316, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_KNIGHT_SWORD_BACK_80F5A316),
                unit(mission.Squad.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_KNIGHT_SWORD_BACK_80F5A530, mission.Slot.PF2_HORDE_DEFENSE_PF2_HORDE_ENCOUNTER_0_SQ_KNIGHT_SWORD_BACK_80F5A530),
            },
        },
        {
            state = mission.states.STATE_80F4696A_0007_0000_80F46ACF,
            region = 56,
            patrol = {
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_0_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_0_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_1_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_1_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_2_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_2_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_5_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_1_FALLEN_5_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_0_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_0_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_1_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_1_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_2_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_2_FALLEN_2_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_0_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_0_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_1_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_1_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_2_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_AIR_3_FALLEN_2_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_0_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_0_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_1_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_1_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_2_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_AMBIENT_2_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_0_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_0_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_1_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_1_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_2_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FALLEN_FAIL_ADDS_2_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_0_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_0_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_1_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_1_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_3_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_3_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_4_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_4_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_5_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_5_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_6_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_FINAL_AREA_FALLEN_6_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_0_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_0_80F5AB1E),
                unit(mission.Squad.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_1_80F5AB1E, mission.Slot.ASCEND_HC_ASCEND_ENCOUNTER_GROUND_SQUAD_FALLEN_1_80F5AB1E),
            },
        },
        {
            state = mission.states.STATE_80F4696A_000F_0000_80F46AD5,
            region = 120,
            patrol = {
                unit(mission.Squad.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_HOTSPOT_SQUAD_0, mission.Slot.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_HOTSPOT_SQUAD_0),
                unit(mission.Squad.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_HOTSPOT_SQUAD_1, mission.Slot.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_HOTSPOT_SQUAD_1),
                unit(mission.Squad.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_SQUAD_0, mission.Slot.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_SQUAD_0),
                unit(mission.Squad.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_SQUAD_1, mission.Slot.PF_LIGHTHOUSE_VX_CRATER_LEFT_A_SQUAD_1),
                unit(mission.Squad.SQ_VANCE, mission.Slot.SQ_VANCE),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F5E1B6,
                    objective = mission.Slot.PSIONA_TRAVEL_POINTS_0_OBJ_PIKE_PATH,
                    squads = {
                        unit(mission.Squad.PSION_SQUAD_A_ARC, mission.Slot.PSION_SQUAD_A_ARC),
                        unit(mission.Squad.PSION_SQUAD_A_THERMAL, mission.Slot.PSION_SQUAD_A_THERMAL),
                        unit(mission.Squad.PSION_SQUAD_A_VOID, mission.Slot.PSION_SQUAD_A_VOID),
                        unit(mission.Squad.PSION_SQUAD_B_ARC, mission.Slot.PSION_SQUAD_B_ARC),
                        unit(mission.Squad.PSION_SQUAD_B_THERMAL, mission.Slot.PSION_SQUAD_B_THERMAL),
                        unit(mission.Squad.PSION_SQUAD_B_VOID, mission.Slot.PSION_SQUAD_B_VOID),
                    },
                    chest = {
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F5E352,
                    objective = mission.Slot.PF_EVENT_VEX_CANNON_1_OBJ_MAIN,
                    squads = {
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_A_T1, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_A_T1),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_A_T2, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_A_T2),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_A_T2_BACKUP, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_A_T2_BACKUP),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_B_T1, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_B_T1),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_B_T2, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_B_T2),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_B_T2_BACKUP, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_B_T2_BACKUP),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_C_T1, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_C_T1),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_C_T2, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_C_T2),
                        unit(mission.Squad.PF_EVENT_VEX_CANNON_1_SQ_GUARD_C_T2_BACKUP, mission.Slot.PF_EVENT_VEX_CANNON_1_SQ_GUARD_C_T2_BACKUP),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_VEX_CANNON_1_CANNON_A_CHEST_OBJECT,
                        mission.Slot.PF_EVENT_VEX_CANNON_1_CANNON_B_CHEST_OBJECT,
                        mission.Slot.PF_EVENT_VEX_CANNON_1_CANNON_C_CHEST_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F5E517,
                    objective = mission.Slot.OBJ_CENTER,
                    squads = {
                        unit(mission.Squad.SQ_BOSS_80F5E517, mission.Slot.SQ_BOSS_80F5E517),
                        unit(mission.Squad.SQ_BOSS_FODDER_FANATICS, mission.Slot.SQ_BOSS_FODDER_FANATICS),
                        unit(mission.Squad.SQ_BOSS_FODDER_LEFT, mission.Slot.SQ_BOSS_FODDER_LEFT),
                        unit(mission.Squad.SQ_BOSS_FODDER_RIGHT, mission.Slot.SQ_BOSS_FODDER_RIGHT),
                        unit(mission.Squad.SQ_ISLAND_FODDER_1, mission.Slot.SQ_ISLAND_FODDER_1),
                        unit(mission.Squad.SQ_ISLAND_FODDER_2, mission.Slot.SQ_ISLAND_FODDER_2),
                        unit(mission.Squad.SQ_PILGRIMS_LEFT_DEFEND, mission.Slot.SQ_PILGRIMS_LEFT_DEFEND),
                        unit(mission.Squad.SQ_PILGRIMS_LEFT_TRAVEL, mission.Slot.SQ_PILGRIMS_LEFT_TRAVEL),
                        unit(mission.Squad.SQ_PILGRIMS_RIGHT_DEFEND, mission.Slot.SQ_PILGRIMS_RIGHT_DEFEND),
                        unit(mission.Squad.SQ_PILGRIMS_RIGHT_TRAVEL, mission.Slot.SQ_PILGRIMS_RIGHT_TRAVEL),
                        unit(mission.Squad.SQ_PILGRIM_HARPY, mission.Slot.SQ_PILGRIM_HARPY),
                        unit(mission.Squad.SQ_SNIPER_LEFT_1, mission.Slot.SQ_SNIPER_LEFT_1),
                        unit(mission.Squad.SQ_SNIPER_LEFT_2, mission.Slot.SQ_SNIPER_LEFT_2),
                        unit(mission.Squad.SQ_SNIPER_RIGHT_1, mission.Slot.SQ_SNIPER_RIGHT_1),
                        unit(mission.Squad.SQ_SNIPER_RIGHT_2, mission.Slot.SQ_SNIPER_RIGHT_2),
                    },
                    chest = {
                        mission.Slot.O_CHEST_WAYPOINT,
                        mission.Slot.O_SECONDARY_CHEST,
                        mission.Slot.O_SECONDARY_CHEST_SPAWN_FX,
                        mission.Slot.PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_REWARD_CHEST_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F5E55D,
                    objective = mission.Slot.EVENT_VEX_PRISONER_1_PRISONER_TRAVEL_POINTS_0_OBJ_PIKE_PATH_80F5E55D,
                    squads = {
                        unit(mission.Squad.EVENT_VEX_PRISONER_1_SQ_GUARD_80F5E55D, mission.Slot.EVENT_VEX_PRISONER_1_SQ_GUARD_80F5E55D),
                    },
                    chest = {
                        mission.Slot.EVENT_VEX_PRISONER_1_PRISONER_CHEST_OBJECT_80F5E55D,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F5E5A3,
                    objective = mission.Slot.EVENT_VEX_PRISONER_1_PRISONER_TRAVEL_POINTS_0_OBJ_PIKE_PATH_80F5E5A3,
                    squads = {
                        unit(mission.Squad.EVENT_VEX_PRISONER_1_SQ_GUARD_80F5E5A3, mission.Slot.EVENT_VEX_PRISONER_1_SQ_GUARD_80F5E5A3),
                    },
                    chest = {
                        mission.Slot.EVENT_VEX_PRISONER_1_PRISONER_CHEST_OBJECT_80F5E5A3,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80F4696A_0010_0000_80F46AD6,
            region = 128,
            -- Lost Sector in bubble 16.
            sector = {
                boss = mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS,
                squads = {
                    unit(mission.Squad.CABAL_ENTRY_DOGS, mission.Slot.CABAL_ENTRY_DOGS),
                    unit(mission.Squad.CABAL_GATEKEEPER, mission.Slot.CABAL_GATEKEEPER),
                    unit(mission.Squad.CABAL_GUARDS_A, mission.Slot.CABAL_GUARDS_A),
                    unit(mission.Squad.CABAL_GUARDS_B, mission.Slot.CABAL_GUARDS_B),
                    unit(mission.Squad.CABAL_GUARDS_C, mission.Slot.CABAL_GUARDS_C),
                    unit(mission.Squad.CABAL_GUARDS_D, mission.Slot.CABAL_GUARDS_D),
                    unit(mission.Squad.CABAL_GUARDS_E, mission.Slot.CABAL_GUARDS_E),
                    unit(mission.Squad.CABAL_GUARDS_F, mission.Slot.CABAL_GUARDS_F),
                    unit(mission.Squad.FINALE_PHALANXES_ANTI_CHEESE, mission.Slot.FINALE_PHALANXES_ANTI_CHEESE),
                    unit(mission.Squad.FORWARD_PHALANXES, mission.Slot.FORWARD_PHALANXES),
                    unit(mission.Squad.GLADIATOR_BFG, mission.Slot.GLADIATOR_BFG),
                    unit(mission.Squad.GLADIATOR_BFG_CHEESE, mission.Slot.GLADIATOR_BFG_CHEESE),
                    unit(mission.Squad.LEGIONARY_CLOSE, mission.Slot.LEGIONARY_CLOSE),
                    unit(mission.Squad.LEGIONARY_FAR, mission.Slot.LEGIONARY_FAR),
                    unit(mission.Squad.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS, mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS),
                    unit(mission.Squad.PHALANX_A_INNER, mission.Slot.PHALANX_A_INNER),
                    unit(mission.Squad.PHALANX_B_INNER, mission.Slot.PHALANX_B_INNER),
                    unit(mission.Squad.PHALANX_MEDIUM, mission.Slot.PHALANX_MEDIUM),
                    unit(mission.Squad.PHALANX_START_STAIRS_A, mission.Slot.PHALANX_START_STAIRS_A),
                    unit(mission.Squad.PHALANX_START_STAIRS_B, mission.Slot.PHALANX_START_STAIRS_B),
                    unit(mission.Squad.PYRO_MAJOR_BODYGUARDS, mission.Slot.PYRO_MAJOR_BODYGUARDS),
                    unit(mission.Squad.PYRO_MAJOR_BODYGUARDS_B, mission.Slot.PYRO_MAJOR_BODYGUARDS_B),
                    unit(mission.Squad.PYRO_OUTLAW, mission.Slot.PYRO_OUTLAW),
                    unit(mission.Squad.SNIPERS, mission.Slot.SNIPERS),
                },
                chest = {
                    mission.Slot.DUNGEON_CHEST,
                },
            },
        },
    }
end
