-- Generated from installed mission data. Do not edit.
-- Zones are authored state rows; population and event sites come from the slice sets.
return function(mission, freeroam)
    local unit = freeroam.unit
    return {
        {
            state = mission.states.STATE_80B3E142_0000_0000_80B3E076,
            region = 0,
            patrol = {
                unit(mission.Squad.ACOLYTES_2_A, mission.Slot.ACOLYTES_2_A),
                unit(mission.Squad.ACOLYTES_BACKFIELD_REINFORCEMENT_A, mission.Slot.ACOLYTES_BACKFIELD_REINFORCEMENT_A),
                unit(mission.Squad.ACOLYTES_BACKFIELD_REINFORCEMENT_B, mission.Slot.ACOLYTES_BACKFIELD_REINFORCEMENT_B),
                unit(mission.Squad.ACOLYTES_DRAW_IN, mission.Slot.ACOLYTES_DRAW_IN),
                unit(mission.Squad.ACOLYTES_OGRE_SUPPORT, mission.Slot.ACOLYTES_OGRE_SUPPORT),
                unit(mission.Squad.ACOLYTE_PRAYERS, mission.Slot.ACOLYTE_PRAYERS),
                unit(mission.Squad.ACOLYTE_PRAYERS_1, mission.Slot.ACOLYTE_PRAYERS_1),
                unit(mission.Squad.ACOLYTE_PRAYERS_LOWER, mission.Slot.ACOLYTE_PRAYERS_LOWER),
                unit(mission.Squad.ACOLYTE_PRAYERS_UPPER, mission.Slot.ACOLYTE_PRAYERS_UPPER),
                unit(mission.Squad.ACOLYTE_PRAYER_REINFORCEMENTS, mission.Slot.ACOLYTE_PRAYER_REINFORCEMENTS),
                unit(mission.Squad.ACOLYTE_REAR_SUPPORT, mission.Slot.ACOLYTE_REAR_SUPPORT),
                unit(mission.Squad.ACOLYTE_SWARM_A_1, mission.Slot.ACOLYTE_SWARM_A_1),
                unit(mission.Squad.ACOLYTE_SWARM_A_2, mission.Slot.ACOLYTE_SWARM_A_2),
                unit(mission.Squad.ACOLYTE_UPPER, mission.Slot.ACOLYTE_UPPER),
                unit(mission.Squad.ALTAR_WIZARD_80B9842C, mission.Slot.ALTAR_WIZARD_80B9842C),
                unit(mission.Squad.ALTAR_WIZARD_80B984A2, mission.Slot.ALTAR_WIZARD_80B984A2),
                unit(mission.Squad.BOOMER_A, mission.Slot.BOOMER_A),
                unit(mission.Squad.BOOMER_ARTILLERY_LEFT, mission.Slot.BOOMER_ARTILLERY_LEFT),
                unit(mission.Squad.BOOMER_ARTILLERY_REAR_RIGHT, mission.Slot.BOOMER_ARTILLERY_REAR_RIGHT),
                unit(mission.Squad.BOOMER_ARTILLERY_RIGHT, mission.Slot.BOOMER_ARTILLERY_RIGHT),
                unit(mission.Squad.BOOMER_KNIGHT_PRAYER, mission.Slot.BOOMER_KNIGHT_PRAYER),
                unit(mission.Squad.BOUNCER_KNIGHT_A, mission.Slot.BOUNCER_KNIGHT_A),
                unit(mission.Squad.BOUNCER_KNIGHT_B, mission.Slot.BOUNCER_KNIGHT_B),
                unit(mission.Squad.BOUNCER_KNIGHT_C, mission.Slot.BOUNCER_KNIGHT_C),
            },
        },
        {
            state = mission.states.STATE_80B3E142_0001_0000_80B3E0A9,
            region = 8,
            patrol = {
                unit(mission.Squad.ACOLYTES_BACK_LEDGE, mission.Slot.ACOLYTES_BACK_LEDGE),
                unit(mission.Squad.ACOLYTES_BACK_PIT, mission.Slot.ACOLYTES_BACK_PIT),
                unit(mission.Squad.ACOLYTES_LEDGE_80B9918C, mission.Slot.ACOLYTES_LEDGE_80B9918C),
                unit(mission.Squad.ACOLYTES_LEDGE_80B991AB, mission.Slot.ACOLYTES_LEDGE_80B991AB),
                unit(mission.Squad.ACOLYTES_PIT, mission.Slot.ACOLYTES_PIT),
                unit(mission.Squad.CONSOLE_DREG_SQUAD, mission.Slot.CONSOLE_DREG_SQUAD),
                unit(mission.Squad.FIRST_GUARD_CAPTAIN, mission.Slot.FIRST_GUARD_CAPTAIN),
                unit(mission.Squad.HANGAR_ENTRANCE_SQUAD, mission.Slot.HANGAR_ENTRANCE_SQUAD),
                unit(mission.Squad.HANGAR_JET_SQUAD, mission.Slot.HANGAR_JET_SQUAD),
                unit(mission.Squad.HANGAR_LOWER_SQUAD, mission.Slot.HANGAR_LOWER_SQUAD),
                unit(mission.Squad.HANGAR_SWARM_A_SQUAD, mission.Slot.HANGAR_SWARM_A_SQUAD),
                unit(mission.Squad.HANGAR_SWARM_B_SQUAD, mission.Slot.HANGAR_SWARM_B_SQUAD),
                unit(mission.Squad.HANGAR_UPPER_SQUAD, mission.Slot.HANGAR_UPPER_SQUAD),
                unit(mission.Squad.HOLLANDAISE_SWEEP_SQUAD_1, mission.Slot.HOLLANDAISE_SWEEP_SQUAD_1),
                unit(mission.Squad.HOLLANDAISE_SWEEP_SQUAD_2, mission.Slot.HOLLANDAISE_SWEEP_SQUAD_2),
                unit(mission.Squad.INITIAL_ACOLYTE_LEFT_SQUAD, mission.Slot.INITIAL_ACOLYTE_LEFT_SQUAD),
                unit(mission.Squad.INITIAL_ACOLYTE_RIGHT_SQUAD, mission.Slot.INITIAL_ACOLYTE_RIGHT_SQUAD),
                unit(mission.Squad.INITIAL_THRALL_A_SQUAD, mission.Slot.INITIAL_THRALL_A_SQUAD),
                unit(mission.Squad.INITIAL_THRALL_B_SQUAD, mission.Slot.INITIAL_THRALL_B_SQUAD),
                unit(mission.Squad.KNIGHTS_80B9904C, mission.Slot.KNIGHTS_80B9904C),
                unit(mission.Squad.KNIGHTS_SHOTGUNS_80B9904C, mission.Slot.KNIGHTS_SHOTGUNS_80B9904C),
                unit(mission.Squad.KNIGHT_FINAL, mission.Slot.KNIGHT_FINAL),
                unit(mission.Squad.KNIGHT_MIDDLE, mission.Slot.KNIGHT_MIDDLE),
                unit(mission.Squad.KNIGHT_WIZARD_1_80B9918C, mission.Slot.KNIGHT_WIZARD_1_80B9918C),
            },
        },
        {
            state = mission.states.STATE_80B3E142_0002_0000_80B3E0C2,
            region = 16,
            patrol = {
                unit(mission.Squad.PF2_ALLEY_ALT_SIMPLE_SQUAD_0, mission.Slot.PF2_ALLEY_ALT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_ALLEY_SIMPLE_SQUAD_0, mission.Slot.PF2_ALLEY_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_ALLEY_SIMPLE_SQUAD_3, mission.Slot.PF2_ALLEY_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_CARGO_ALT_SIMPLE_SQUAD_1, mission.Slot.PF2_CARGO_ALT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_CARGO_ALT_SIMPLE_SQUAD_2, mission.Slot.PF2_CARGO_ALT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_CARGO_SIMPLE_SQUAD_1_80B9925F, mission.Slot.PF2_CARGO_SIMPLE_SQUAD_1_80B9925F),
                unit(mission.Squad.PF2_DECK_SIMPLE_SQUAD_2_80B99279, mission.Slot.PF2_DECK_SIMPLE_SQUAD_2_80B99279),
                unit(mission.Squad.PF2_DEPOT_ALT_SIMPLE_SQUAD_0, mission.Slot.PF2_DEPOT_ALT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_DEPOT_ALT_SIMPLE_SQUAD_1, mission.Slot.PF2_DEPOT_ALT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_DEPOT_ALT_SIMPLE_SQUAD_2, mission.Slot.PF2_DEPOT_ALT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_DEPOT_SIMPLE_SQUAD_0, mission.Slot.PF2_DEPOT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_DEPOT_SIMPLE_SQUAD_1, mission.Slot.PF2_DEPOT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_DEPOT_SIMPLE_SQUAD_2, mission.Slot.PF2_DEPOT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_DEPOT_SIMPLE_SQUAD_3, mission.Slot.PF2_DEPOT_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_INTERIOR_ALT_SIMPLE_SQUAD_1_80B992D1, mission.Slot.PF2_INTERIOR_ALT_SIMPLE_SQUAD_1_80B992D1),
                unit(mission.Squad.PF2_INTERIOR_ALT_SIMPLE_SQUAD_2_80B992D1, mission.Slot.PF2_INTERIOR_ALT_SIMPLE_SQUAD_2_80B992D1),
                unit(mission.Squad.PF2_INTERIOR_SIMPLE_SQUAD_0_80B992AC, mission.Slot.PF2_INTERIOR_SIMPLE_SQUAD_0_80B992AC),
                unit(mission.Squad.PF2_INTERIOR_SIMPLE_SQUAD_1_80B992AC, mission.Slot.PF2_INTERIOR_SIMPLE_SQUAD_1_80B992AC),
                unit(mission.Squad.PF2_INTERIOR_SIMPLE_SQUAD_2_80B992AC, mission.Slot.PF2_INTERIOR_SIMPLE_SQUAD_2_80B992AC),
                unit(mission.Squad.PF2_ROOFTOP_ALT_SIMPLE_SQUAD_0, mission.Slot.PF2_ROOFTOP_ALT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_ROOFTOP_SIMPLE_SQUAD_0_80B992FD, mission.Slot.PF2_ROOFTOP_SIMPLE_SQUAD_0_80B992FD),
                unit(mission.Squad.PF2_ROOM_ALT_SIMPLE_SQUAD_0_80B99420, mission.Slot.PF2_ROOM_ALT_SIMPLE_SQUAD_0_80B99420),
                unit(mission.Squad.PF2_ROOM_ALT_SIMPLE_SQUAD_1_80B99420, mission.Slot.PF2_ROOM_ALT_SIMPLE_SQUAD_1_80B99420),
                unit(mission.Squad.PF2_ROOM_SIMPLE_SQUAD_0_80B99409, mission.Slot.PF2_ROOM_SIMPLE_SQUAD_0_80B99409),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80B99A9D,
                    objective = mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_OBJECTIVE_80B99A9D,
                    squads = {
                        unit(mission.Squad.EVENT_CONVOY_BOSS_SQUAD_80B99A9D, mission.Slot.EVENT_CONVOY_BOSS_SQUAD_80B99A9D),
                    },
                    chest = {
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_CONVOY_CHEST_OBJECT_80B99A9D,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_1_CONVOY_CHEST_OBJECT_80B99A9D,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_2_CONVOY_CHEST_OBJECT_80B99A9D,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_3_CONVOY_CHEST_OBJECT_80B99A9D,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_4_CONVOY_CHEST_OBJECT_80B99A9D,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80B99AC7,
                    objective = mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_OBJECTIVE_80B99AC7,
                    squads = {
                        unit(mission.Squad.EVENT_CONVOY_BOSS_SQUAD_80B99AC7, mission.Slot.EVENT_CONVOY_BOSS_SQUAD_80B99AC7),
                    },
                    chest = {
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_CONVOY_CHEST_OBJECT_80B99AC7,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_1_CONVOY_CHEST_OBJECT_80B99AC7,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_2_CONVOY_CHEST_OBJECT_80B99AC7,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_3_CONVOY_CHEST_OBJECT_80B99AC7,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80B99ADD,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_OBJECTIVE,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_FODDER_SQUAD, mission.Slot.COWARDLY_MAJOR_CORE_FODDER_SQUAD),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_SQUAD, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_SQUAD),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD, mission.Slot.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80B99F21,
                    objective = mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_OBJECTIVE_80B99F21,
                    squads = {
                        unit(mission.Squad.EVENT_CONVOY_BOSS_SQUAD_80B99F21, mission.Slot.EVENT_CONVOY_BOSS_SQUAD_80B99F21),
                    },
                    chest = {
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_CONVOY_CHEST_OBJECT_80B99F21,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_1_CONVOY_CHEST_OBJECT_80B99F21,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_2_CONVOY_CHEST_OBJECT_80B99F21,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_3_CONVOY_CHEST_OBJECT_80B99F21,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF6028,
                    objective = mission.Slot.PF2_EVENT_MONOLITH_CORE_OBJ_NORMAL_80BF6028,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF6028),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF6028, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF6028),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_80BF6028,
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_SPAWN_FX_80BF6028,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF6570,
                    objective = mission.Slot.PF2_EVENT_MONOLITH_CORE_OBJ_NORMAL_80BF6570,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF6570),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF6570, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF6570),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_80BF6570,
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_SPAWN_FX_80BF6570,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF6641,
                    objective = mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_OBJECTIVE_80BF6641,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF6641, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF6641),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF6641, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF6641),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF6641, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF6641),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF6641, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF6641),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF6641, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF6641),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_O_CHEST_80BF6641,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF66C9,
                    objective = mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_OBJECTIVE_80BF66C9,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF66C9, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF66C9),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF66C9, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF66C9),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF66C9, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF66C9),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF66C9, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF66C9),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF66C9, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF66C9),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_O_CHEST_80BF66C9,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF67B4,
                    objective = mission.Slot.PF2_EVENT_FRIENDS_CORE_OBJECTIVE_80BF67B4,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF67B4, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF67B4),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF67B4, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF67B4),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF67B4, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF67B4),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF67B4, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF67B4),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_FRIENDS_CORE_O_CHEST_80BF67B4,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF68AA,
                    objective = mission.Slot.PF2_EVENT_FRIENDS_CORE_OBJECTIVE_80BF68AA,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF68AA, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF68AA),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF68AA, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF68AA),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF68AA, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF68AA),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF68AA, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF68AA),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_FRIENDS_CORE_O_CHEST_80BF68AA,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80B3E142_0003_0000_80B3E0D3,
            region = 24,
            -- Lost Sector in bubble 3.
            sector = {
                boss = mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF0698,
                squads = {
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_0_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_0_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_1_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_1_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_OGRE_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_OGRE_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_SHRIEKER_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_SHRIEKER_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_0_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_0_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_1_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_1_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_2_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_2_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_0_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_0_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_1_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_1_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_2_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_2_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_1_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_1_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_2_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_2_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_3_80BF0698, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_3_80BF0698),
                    unit(mission.Squad.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF0698, mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF0698),
                    unit(mission.Squad.SQ_FAREWELL_KNIGHT_80B99B66, mission.Slot.SQ_FAREWELL_KNIGHT_80B99B66),
                    unit(mission.Squad.SQ_FA_AREA_1_ANCHOR_0_80BF0698, mission.Slot.SQ_FA_AREA_1_ANCHOR_0_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_ANCHOR_1_80BF0698, mission.Slot.SQ_FA_AREA_1_ANCHOR_1_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_0_80BF0698, mission.Slot.SQ_FA_AREA_1_FODDER_0_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_1_80BF0698, mission.Slot.SQ_FA_AREA_1_FODDER_1_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_2_80BF0698, mission.Slot.SQ_FA_AREA_1_FODDER_2_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_3_80BF0698, mission.Slot.SQ_FA_AREA_1_FODDER_3_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_4_80BF0698, mission.Slot.SQ_FA_AREA_1_FODDER_4_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_5_80BF0698, mission.Slot.SQ_FA_AREA_1_FODDER_5_80BF0698),
                    unit(mission.Squad.SQ_FA_AREA_1_RUSHER_0_80BF0698, mission.Slot.SQ_FA_AREA_1_RUSHER_0_80BF0698),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80BF080B,
                },
            },
        },
        {
            state = mission.states.STATE_80B3E142_0005_0000_80B3E0D5,
            region = 40,
            patrol = {
                unit(mission.Squad.AMBUSH_CORNER_SQUAD, mission.Slot.AMBUSH_CORNER_SQUAD),
                unit(mission.Squad.CAPTURE_WAVE_A_3_SQUAD, mission.Slot.CAPTURE_WAVE_A_3_SQUAD),
                unit(mission.Squad.CAPTURE_WAVE_C_SQUAD, mission.Slot.CAPTURE_WAVE_C_SQUAD),
                unit(mission.Squad.CAT_FAN_SQUAD, mission.Slot.CAT_FAN_SQUAD),
                unit(mission.Squad.CAT_LEFT_SQUAD, mission.Slot.CAT_LEFT_SQUAD),
                unit(mission.Squad.CAT_MID_SQUAD, mission.Slot.CAT_MID_SQUAD),
                unit(mission.Squad.CAT_SCORCH_SQUAD, mission.Slot.CAT_SCORCH_SQUAD),
                unit(mission.Squad.CAT_STAIRS_SQUAD, mission.Slot.CAT_STAIRS_SQUAD),
                unit(mission.Squad.CLOT_DREG_SQUAD, mission.Slot.CLOT_DREG_SQUAD),
                unit(mission.Squad.CRUST_DREG_SQUAD, mission.Slot.CRUST_DREG_SQUAD),
                unit(mission.Squad.FIRST_THIEF_ROOM_SQUAD_A, mission.Slot.FIRST_THIEF_ROOM_SQUAD_A),
                unit(mission.Squad.LOOT_SQUAD_A, mission.Slot.LOOT_SQUAD_A),
                unit(mission.Squad.LOOT_SQUAD_B, mission.Slot.LOOT_SQUAD_B),
                unit(mission.Squad.LOOT_SQUAD_C, mission.Slot.LOOT_SQUAD_C),
                unit(mission.Squad.MAIN_SKIFF_A_SQUAD, mission.Slot.MAIN_SKIFF_A_SQUAD),
                unit(mission.Squad.MAIN_SKIFF_B_SQUAD, mission.Slot.MAIN_SKIFF_B_SQUAD),
                unit(mission.Squad.PF2_HALLWAY_SIMPLE_SQUAD_2, mission.Slot.PF2_HALLWAY_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_ROOM_SIMPLE_SQUAD_0_80BF089C, mission.Slot.PF2_ROOM_SIMPLE_SQUAD_0_80BF089C),
                unit(mission.Squad.PF2_ROOM_SIMPLE_SQUAD_1_80BF089C, mission.Slot.PF2_ROOM_SIMPLE_SQUAD_1_80BF089C),
                unit(mission.Squad.PF2_ROOM_SIMPLE_SQUAD_2_80BF089C, mission.Slot.PF2_ROOM_SIMPLE_SQUAD_2_80BF089C),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80B3E469, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80B3E469),
                unit(mission.Squad.PF2_TANKS_SIMPLE_SQUAD_0, mission.Slot.PF2_TANKS_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_TANKS_SIMPLE_SQUAD_1, mission.Slot.PF2_TANKS_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_TANKS_SIMPLE_SQUAD_2, mission.Slot.PF2_TANKS_SIMPLE_SQUAD_2),
            },
        },
        {
            state = mission.states.STATE_80B3E142_0006_0000_80B3E0D6,
            region = 48,
            patrol = {
                unit(mission.Squad.ACOLYTES_2_80BF113E, mission.Slot.ACOLYTES_2_80BF113E),
                unit(mission.Squad.ACOLYTES_2_80BF1173, mission.Slot.ACOLYTES_2_80BF1173),
                unit(mission.Squad.ACOLYTES_3_80BF1173, mission.Slot.ACOLYTES_3_80BF1173),
                unit(mission.Squad.ACOLYTES_80BF108A, mission.Slot.ACOLYTES_80BF108A),
                unit(mission.Squad.ACOLYTES_80BF1128, mission.Slot.ACOLYTES_80BF1128),
                unit(mission.Squad.ACOLYTES_CIRCULAR_ROOM, mission.Slot.ACOLYTES_CIRCULAR_ROOM),
                unit(mission.Squad.ACOLYTES_LOWER_CATWALK, mission.Slot.ACOLYTES_LOWER_CATWALK),
                unit(mission.Squad.ACOLYTES_PLATFORM, mission.Slot.ACOLYTES_PLATFORM),
                unit(mission.Squad.BOOMER_LOWER_CATWALK, mission.Slot.BOOMER_LOWER_CATWALK),
                unit(mission.Squad.BOUNCER_KNIGHT_80BF1128, mission.Slot.BOUNCER_KNIGHT_80BF1128),
                unit(mission.Squad.BOUNCER_KNIGHT_80BF113E, mission.Slot.BOUNCER_KNIGHT_80BF113E),
                unit(mission.Squad.BOUNCER_KNIGHT_80BF1173, mission.Slot.BOUNCER_KNIGHT_80BF1173),
                unit(mission.Squad.EGRESS_A_SQUAD, mission.Slot.EGRESS_A_SQUAD),
                unit(mission.Squad.EGRESS_B_SQUAD, mission.Slot.EGRESS_B_SQUAD),
                unit(mission.Squad.EGRESS_C_SQUAD, mission.Slot.EGRESS_C_SQUAD),
                unit(mission.Squad.ENTRY_ANCHOR_SQUAD, mission.Slot.ENTRY_ANCHOR_SQUAD),
                unit(mission.Squad.ENTRY_ATTENDANTS_A_SQUAD, mission.Slot.ENTRY_ATTENDANTS_A_SQUAD),
                unit(mission.Squad.ENTRY_ATTENDANTS_B_SQUAD, mission.Slot.ENTRY_ATTENDANTS_B_SQUAD),
                unit(mission.Squad.ENTRY_A_SQUAD, mission.Slot.ENTRY_A_SQUAD),
                unit(mission.Squad.ENTRY_B_SQUAD, mission.Slot.ENTRY_B_SQUAD),
                unit(mission.Squad.ENTRY_C_SQUAD, mission.Slot.ENTRY_C_SQUAD),
                unit(mission.Squad.ENTRY_D_SQUAD, mission.Slot.ENTRY_D_SQUAD),
                unit(mission.Squad.EXPLODERS_PLATFORM, mission.Slot.EXPLODERS_PLATFORM),
                unit(mission.Squad.FINAL_WAVE_A_SQUAD, mission.Slot.FINAL_WAVE_A_SQUAD),
            },
        },
        {
            state = mission.states.STATE_80B3E142_0007_0000_80B3E0D7,
            region = 56,
            patrol = {
                unit(mission.Squad.ACOLYTES_2_80BF6041, mission.Slot.ACOLYTES_2_80BF6041),
                unit(mission.Squad.ACOLYTES_3_80BF6041, mission.Slot.ACOLYTES_3_80BF6041),
                unit(mission.Squad.ACOLYTES_4, mission.Slot.ACOLYTES_4),
                unit(mission.Squad.ACOLYTES_5, mission.Slot.ACOLYTES_5),
                unit(mission.Squad.ACOLYTES_6, mission.Slot.ACOLYTES_6),
                unit(mission.Squad.ACOLYTES_7, mission.Slot.ACOLYTES_7),
                unit(mission.Squad.ACOLYTES_8, mission.Slot.ACOLYTES_8),
                unit(mission.Squad.ACOLYTES_80BF6041, mission.Slot.ACOLYTES_80BF6041),
                unit(mission.Squad.ACOLYTES_80BF604E, mission.Slot.ACOLYTES_80BF604E),
                unit(mission.Squad.FACILITY_DREG_SQUAD, mission.Slot.FACILITY_DREG_SQUAD),
                unit(mission.Squad.FACILITY_MARAUDER_SQUAD, mission.Slot.FACILITY_MARAUDER_SQUAD),
                unit(mission.Squad.KNIGHT_FIRST_80BF6015, mission.Slot.KNIGHT_FIRST_80BF6015),
                unit(mission.Squad.KNIGHT_WIZARD_80BF6015, mission.Slot.KNIGHT_WIZARD_80BF6015),
                unit(mission.Squad.NAMED_WIZARD, mission.Slot.NAMED_WIZARD),
                unit(mission.Squad.NAMED_WIZARD_1, mission.Slot.NAMED_WIZARD_1),
                unit(mission.Squad.PF2_CARGO_SIMPLE_SQUAD_2, mission.Slot.PF2_CARGO_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_CRANE_ALT_SIMPLE_SQUAD_2, mission.Slot.PF2_CRANE_ALT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_DECK_ALT_SIMPLE_SQUAD_1, mission.Slot.PF2_DECK_ALT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_DECK_ALT_SIMPLE_SQUAD_3, mission.Slot.PF2_DECK_ALT_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_DECK_SIMPLE_SQUAD_3, mission.Slot.PF2_DECK_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_DEPOSITORY_SIMPLE_SQUAD_2, mission.Slot.PF2_DEPOSITORY_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_INTERIOR_ALT_SIMPLE_SQUAD_1_80BF1E8F, mission.Slot.PF2_INTERIOR_ALT_SIMPLE_SQUAD_1_80BF1E8F),
                unit(mission.Squad.PF2_INTERIOR_ALT_SIMPLE_SQUAD_2_80BF1E8F, mission.Slot.PF2_INTERIOR_ALT_SIMPLE_SQUAD_2_80BF1E8F),
                unit(mission.Squad.PF2_INTERIOR_SIMPLE_SQUAD_1_80BF1E7C, mission.Slot.PF2_INTERIOR_SIMPLE_SQUAD_1_80BF1E7C),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF15E3,
                    objective = mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_OBJECTIVE_80BF15E3,
                    squads = {
                        unit(mission.Squad.EVENT_CONVOY_BOSS_SQUAD_80BF15E3, mission.Slot.EVENT_CONVOY_BOSS_SQUAD_80BF15E3),
                    },
                    chest = {
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_0_CONVOY_CHEST_OBJECT_80BF15E3,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_1_CONVOY_CHEST_OBJECT_80BF15E3,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_2_CONVOY_CHEST_OBJECT_80BF15E3,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_3_CONVOY_CHEST_OBJECT_80BF15E3,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_4_CONVOY_CHEST_OBJECT_80BF15E3,
                        mission.Slot.EVENT_CONVOY_CONVOY_POINTS_5_CONVOY_CHEST_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF1600,
                    objective = mission.Slot.PF_EVENT_FALLEN_INCURSION_1_OBJECTIVE_80BF1600,
                    squads = {
                        unit(mission.Squad.SQ_HIVE_RESISTANCE_80BF1600, mission.Slot.SQ_HIVE_RESISTANCE_80BF1600),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_FALLEN_INCURSION_1_LOCKED_CHEST_OBJECT_80BF1600,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF1928,
                    objective = mission.Slot.PF_EVENT_HIVE_RITUAL_1_OBJ_MAIN,
                    squads = {
                        unit(mission.Squad.HOTSPOT_EVENT_LEADER_SQUAD, mission.Slot.HOTSPOT_EVENT_LEADER_SQUAD),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_INITIAL, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_INITIAL),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_INITIAL, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_INITIAL),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_DARKBLADE, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_DARKBLADE),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO0, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO0),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO3, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO3),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO4, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO4),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO5, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO5),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_INITIAL_NON_MAJOR, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_INITIAL_NON_MAJOR),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_INITIAL_NON_MAJOR, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_INITIAL_NON_MAJOR),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_3, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_3),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_WIZARD_BOSS, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_WIZARD_BOSS),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF19C1,
                    objective = mission.Slot.PF_EVENT_SKIRMISH01_OBJ_SKIRMISH_80BF19C1,
                    squads = {
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_A_INTRO_WAVE_0_80BF19C1, mission.Slot.PF_EVENT_SKIRMISH01_SQ_A_INTRO_WAVE_0_80BF19C1),
                    },
                    chest = {
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF1ACB,
                    objective = mission.Slot.PF_EVENT_SKIRMISH02_OBJ_SKIRMISH,
                    squads = {
                        unit(mission.Squad.PF_EVENT_SKIRMISH02_SQ_A_INTRO_WAVE_0, mission.Slot.PF_EVENT_SKIRMISH02_SQ_A_INTRO_WAVE_0),
                    },
                    chest = {
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF6E60,
                    objective = mission.Slot.PF2_EVENT_MONOLITH_CORE_OBJ_NORMAL_80BF6E60,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF6E60),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF6E60, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF6E60),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_80BF6E60,
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_SPAWN_FX_80BF6E60,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF71E5,
                    objective = mission.Slot.PF2_EVENT_MONOLITH_CORE_OBJ_NORMAL_80BF71E5,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_0_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_ANCHOR_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_0_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_CHASER_FODDER_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_BOOMER_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_FRIENDS_KNIGHT_CLEAVER_2_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_OGRE_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_2_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_THRALL_3_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_2_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_HEALING_WIZARD_3_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_BOSS_PLANT_PYRO_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_0_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_CHASER_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_0_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_HEROIC_THRALL_2_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_0_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_BLOCKER_2_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_TURRET_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_TAKEN_ULTRAS_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_0_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_OUTER_1_80BF71E5),
                        unit(mission.Squad.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF71E5, mission.Slot.PF2_EVENT_MONOLITH_CORE_SQ_WAVE_ULTRA_0_80BF71E5),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_80BF71E5,
                        mission.Slot.PF2_EVENT_MONOLITH_CORE_O_TREASURE_CHEST_SPAWN_FX_80BF71E5,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF72A7,
                    objective = mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_OBJECTIVE_80BF72A7,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF72A7, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF72A7),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF72A7, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF72A7),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF72A7, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF72A7),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF72A7, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF72A7),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF72A7, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF72A7),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_O_CHEST_80BF72A7,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF7329,
                    objective = mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_OBJECTIVE_80BF7329,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF7329, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_ANCHOR_1_80BF7329),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF7329, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_CHAMPION_80BF7329),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF7329, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_FODDER_80BF7329),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF7329, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_SHADOW_THRALL_1_80BF7329),
                        unit(mission.Squad.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF7329, mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_SQ_TURRET_1_80BF7329),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_TAKEN_SHIELD_CORE_O_CHEST_80BF7329,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF73DF,
                    objective = mission.Slot.PF2_EVENT_FRIENDS_CORE_OBJECTIVE_80BF73DF,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF73DF, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF73DF),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF73DF, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF73DF),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF73DF, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF73DF),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF73DF, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF73DF),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_FRIENDS_CORE_O_CHEST_80BF73DF,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80BF7452,
                    objective = mission.Slot.PF2_EVENT_FRIENDS_CORE_OBJECTIVE_80BF7452,
                    squads = {
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF7452, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_1_80BF7452),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF7452, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_BOSS_2_80BF7452),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF7452, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_80BF7452),
                        unit(mission.Squad.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF7452, mission.Slot.PF2_EVENT_FRIENDS_CORE_SQ_CHAMPION_FODDER_80BF7452),
                    },
                    chest = {
                        mission.Slot.PF2_EVENT_FRIENDS_CORE_O_CHEST_80BF7452,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80B3E142_0008_0000_80B3E0EC,
            region = 64,
            -- Lost Sector in bubble 8.
            sector = {
                boss = mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF6596,
                squads = {
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_0_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_0_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_1_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_1_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_OGRE_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_OGRE_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_SHRIEKER_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_SHRIEKER_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_0_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_0_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_1_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_1_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_2_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_2_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_0_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_0_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_1_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_1_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_2_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_2_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_1_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_1_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_2_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_2_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_3_80BF6596, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_3_80BF6596),
                    unit(mission.Squad.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF6596, mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF6596),
                    unit(mission.Squad.SQ_CHEESE_KNIGHTS, mission.Slot.SQ_CHEESE_KNIGHTS),
                    unit(mission.Squad.SQ_FA_AREA_1_ANCHOR_0_80BF6596, mission.Slot.SQ_FA_AREA_1_ANCHOR_0_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_ANCHOR_1_80BF6596, mission.Slot.SQ_FA_AREA_1_ANCHOR_1_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_0_80BF6596, mission.Slot.SQ_FA_AREA_1_FODDER_0_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_1_80BF6596, mission.Slot.SQ_FA_AREA_1_FODDER_1_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_2_80BF6596, mission.Slot.SQ_FA_AREA_1_FODDER_2_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_3_80BF6596, mission.Slot.SQ_FA_AREA_1_FODDER_3_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_4_80BF6596, mission.Slot.SQ_FA_AREA_1_FODDER_4_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_5_80BF6596, mission.Slot.SQ_FA_AREA_1_FODDER_5_80BF6596),
                    unit(mission.Squad.SQ_FA_AREA_1_RUSHER_0_80BF6596, mission.Slot.SQ_FA_AREA_1_RUSHER_0_80BF6596),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80BF65DF,
                },
            },
        },
        {
            state = mission.states.STATE_80B3E142_0009_0000_80B3E0ED,
            region = 72,
            -- Lost Sector in bubble 9.
            sector = {
                boss = mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF6B69,
                squads = {
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_0_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_0_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_1_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_KNIGHT_1_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_OGRE_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_OGRE_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_SHRIEKER_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_SHRIEKER_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_0_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_0_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_1_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_1_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_2_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_2_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_0_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_0_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_1_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_1_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_2_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_THRALL_EXTRA_2_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_1_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_1_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_2_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_2_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_3_80BF6B69, mission.Slot.PF2_OUTLAWS_HIVE_CORE_SQ_OUTLAWS_HIVE_WIZARD_3_80BF6B69),
                    unit(mission.Squad.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF6B69, mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_ANCHOR_0_80BF6B69, mission.Slot.SQ_FA_AREA_1_ANCHOR_0_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_ANCHOR_1_80BF6B69, mission.Slot.SQ_FA_AREA_1_ANCHOR_1_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_0_80BF6B69, mission.Slot.SQ_FA_AREA_1_FODDER_0_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_1_80BF6B69, mission.Slot.SQ_FA_AREA_1_FODDER_1_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_2_80BF6B69, mission.Slot.SQ_FA_AREA_1_FODDER_2_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_3_80BF6B69, mission.Slot.SQ_FA_AREA_1_FODDER_3_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_4_80BF6B69, mission.Slot.SQ_FA_AREA_1_FODDER_4_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_5_80BF6B69, mission.Slot.SQ_FA_AREA_1_FODDER_5_80BF6B69),
                    unit(mission.Squad.SQ_FA_AREA_1_FODDER_6, mission.Slot.SQ_FA_AREA_1_FODDER_6),
                    unit(mission.Squad.SQ_FA_AREA_1_RUSHER_0_80BF6B69, mission.Slot.SQ_FA_AREA_1_RUSHER_0_80BF6B69),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR2,
                },
            },
        },
        {
            state = mission.states.STATE_80B3E142_000B_0000_80B3E141,
            region = 88,
            patrol = {
                unit(mission.Squad.ACOLYTES_1_80B98884, mission.Slot.ACOLYTES_1_80B98884),
                unit(mission.Squad.ACOLYTES_2_80B98884, mission.Slot.ACOLYTES_2_80B98884),
                unit(mission.Squad.ACOLYTES_3_80B98884, mission.Slot.ACOLYTES_3_80B98884),
                unit(mission.Squad.ACOLYTES_ADDS_HALLWAY, mission.Slot.ACOLYTES_ADDS_HALLWAY),
                unit(mission.Squad.ACOLYTE_A_SQUAD, mission.Slot.ACOLYTE_A_SQUAD),
                unit(mission.Squad.ACOLYTE_GUARDS, mission.Slot.ACOLYTE_GUARDS),
                unit(mission.Squad.ACOLYTE_PRAYERS_LEFT, mission.Slot.ACOLYTE_PRAYERS_LEFT),
                unit(mission.Squad.ACOLYTE_PRAYERS_RIGHT, mission.Slot.ACOLYTE_PRAYERS_RIGHT),
                unit(mission.Squad.ACOLYTE_REINFORCEMENTS_BACK, mission.Slot.ACOLYTE_REINFORCEMENTS_BACK),
                unit(mission.Squad.ACOLYTE_REINFORCEMENTS_FRONT, mission.Slot.ACOLYTE_REINFORCEMENTS_FRONT),
                unit(mission.Squad.ALTAR_WIZARD_80B98868, mission.Slot.ALTAR_WIZARD_80B98868),
                unit(mission.Squad.ANCHOR_SQUAD, mission.Slot.ANCHOR_SQUAD),
                unit(mission.Squad.CHASE_FA_ULTRA_CAPTAIN_SQUAD_80B987A9, mission.Slot.CHASE_FA_ULTRA_CAPTAIN_SQUAD_80B987A9),
                unit(mission.Squad.DREG_A_SQUAD_80B987A9, mission.Slot.DREG_A_SQUAD_80B987A9),
                unit(mission.Squad.DREG_A_SQUAD_80B98901, mission.Slot.DREG_A_SQUAD_80B98901),
                unit(mission.Squad.DREG_B_SQUAD_80B987A9, mission.Slot.DREG_B_SQUAD_80B987A9),
                unit(mission.Squad.DREG_B_SQUAD_80B98901, mission.Slot.DREG_B_SQUAD_80B98901),
                unit(mission.Squad.DREG_C_SQUAD_80B987A9, mission.Slot.DREG_C_SQUAD_80B987A9),
                unit(mission.Squad.DREG_C_SQUAD_80B98901, mission.Slot.DREG_C_SQUAD_80B98901),
                unit(mission.Squad.DREG_D_SQUAD, mission.Slot.DREG_D_SQUAD),
                unit(mission.Squad.DREG_E_SQUAD, mission.Slot.DREG_E_SQUAD),
                unit(mission.Squad.KNIGHT_1, mission.Slot.KNIGHT_1),
                unit(mission.Squad.KNIGHT_2, mission.Slot.KNIGHT_2),
                unit(mission.Squad.KNIGHT_3, mission.Slot.KNIGHT_3),
            },
        },
    }
end
