-- Generated from installed mission data. Do not edit.
-- Zones are authored state rows; population and event sites come from the slice sets.
return function(mission, freeroam)
    local unit = freeroam.unit
    return {
        {
            state = mission.states.STATE_80F6AB20_0000_0000_80F76D88,
            region = 0,
            patrol = {
                unit(mission.Squad.ACOLYTES, mission.Slot.ACOLYTES),
                unit(mission.Squad.ACOLYTE_80F736A8, mission.Slot.ACOLYTE_80F736A8),
                unit(mission.Squad.ACOLYTE_80F73769, mission.Slot.ACOLYTE_80F73769),
                unit(mission.Squad.ACOLYTE_POPCORN, mission.Slot.ACOLYTE_POPCORN),
                unit(mission.Squad.ACOLYTE_PRAYERS, mission.Slot.ACOLYTE_PRAYERS),
                unit(mission.Squad.ACOLYTE_REINFORCEMENTS_ADDS_A, mission.Slot.ACOLYTE_REINFORCEMENTS_ADDS_A),
                unit(mission.Squad.ADDS_A, mission.Slot.ADDS_A),
                unit(mission.Squad.ADDS_B, mission.Slot.ADDS_B),
                unit(mission.Squad.ADDS_C, mission.Slot.ADDS_C),
                unit(mission.Squad.ADDS_IN_STARTING_AREA_1, mission.Slot.ADDS_IN_STARTING_AREA_1),
                unit(mission.Squad.ADDS_LEADING_UP_HILL_1, mission.Slot.ADDS_LEADING_UP_HILL_1),
                unit(mission.Squad.ADDS_ON_HALFWAY_UP_1, mission.Slot.ADDS_ON_HALFWAY_UP_1),
                unit(mission.Squad.ANCHOR_A, mission.Slot.ANCHOR_A),
                unit(mission.Squad.ARMADA_CAVE_ENCOUNTER_SQUAD_1, mission.Slot.ARMADA_CAVE_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.ARMADA_CAVE_ENCOUNTER_SQUAD_2, mission.Slot.ARMADA_CAVE_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.ARMADA_CAVE_ENCOUNTER_SQUAD_3, mission.Slot.ARMADA_CAVE_ENCOUNTER_SQUAD_3),
                unit(mission.Squad.ARMADA_CAVE_ENCOUNTER_SQUAD_4, mission.Slot.ARMADA_CAVE_ENCOUNTER_SQUAD_4),
                unit(mission.Squad.ARMADA_KNIGHT_ROOM_ENCOUNTER_SQUAD_0, mission.Slot.ARMADA_KNIGHT_ROOM_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.ARMADA_PEAK_ENCOUNTER_SQUAD_0, mission.Slot.ARMADA_PEAK_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.ARMADA_PEAK_ENCOUNTER_SQUAD_1, mission.Slot.ARMADA_PEAK_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.ARMADA_PEAK_ENCOUNTER_SQUAD_2, mission.Slot.ARMADA_PEAK_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.ARMADA_PEAK_ENCOUNTER_SQUAD_3, mission.Slot.ARMADA_PEAK_ENCOUNTER_SQUAD_3),
                unit(mission.Squad.ARMADA_PREAMBLE_ENCOUNTER_SQUAD_0, mission.Slot.ARMADA_PREAMBLE_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.ARMADA_PREAMBLE_ENCOUNTER_SQUAD_1, mission.Slot.ARMADA_PREAMBLE_ENCOUNTER_SQUAD_1),
            },
        },
        {
            state = mission.states.STATE_80F6AB20_0001_0000_80F76D89,
            region = 8,
            patrol = {
                unit(mission.Squad.COMMANDER, mission.Slot.COMMANDER),
                unit(mission.Squad.COURIER_1, mission.Slot.COURIER_1),
                unit(mission.Squad.COURIER_2, mission.Slot.COURIER_2),
                unit(mission.Squad.COURTYARD_ENCOUNTER_CABAL_SQUAD_0, mission.Slot.COURTYARD_ENCOUNTER_CABAL_SQUAD_0),
                unit(mission.Squad.COURTYARD_ENCOUNTER_CABAL_SQUAD_1, mission.Slot.COURTYARD_ENCOUNTER_CABAL_SQUAD_1),
                unit(mission.Squad.COURTYARD_ENCOUNTER_CABAL_SQUAD_2, mission.Slot.COURTYARD_ENCOUNTER_CABAL_SQUAD_2),
                unit(mission.Squad.COURTYARD_ENCOUNTER_SQUAD_1, mission.Slot.COURTYARD_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.COURTYARD_ENCOUNTER_SQUAD_2, mission.Slot.COURTYARD_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.LANDINGINTERIOR_ENCOUNTER_SQUAD_0, mission.Slot.LANDINGINTERIOR_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.LANDINGINTERIOR_ENCOUNTER_SQUAD_1, mission.Slot.LANDINGINTERIOR_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.LANDINGINTERIOR_ENCOUNTER_SQUAD_2, mission.Slot.LANDINGINTERIOR_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.LANDINGPAD3_ENCOUNTER_SQUAD_1, mission.Slot.LANDINGPAD3_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.LANDINGPAD_4_ENCOUNTER_SQUAD_0, mission.Slot.LANDINGPAD_4_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.LANDINGPAD_5_ENCOUNTER_SQUAD_0, mission.Slot.LANDINGPAD_5_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.PHALANX_CABALTWO_COLLECT_1, mission.Slot.PHALANX_CABALTWO_COLLECT_1),
                unit(mission.Squad.PHALANX_CABALTWO_COLLECT_2, mission.Slot.PHALANX_CABALTWO_COLLECT_2),
                unit(mission.Squad.PHALANX_CABALTWO_COLLECT_3, mission.Slot.PHALANX_CABALTWO_COLLECT_3),
                unit(mission.Squad.PHALANX_CABALTWO_COLLECT_4, mission.Slot.PHALANX_CABALTWO_COLLECT_4),
                unit(mission.Squad.PHALANX_CABALTWO_COLLECT_5, mission.Slot.PHALANX_CABALTWO_COLLECT_5),
                unit(mission.Squad.SHORE_ENCOUNTER_SQUAD_0, mission.Slot.SHORE_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.SHORE_ENCOUNTER_SQUAD_1, mission.Slot.SHORE_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.SHORE_ENCOUNTER_SQUAD_3, mission.Slot.SHORE_ENCOUNTER_SQUAD_3),
                unit(mission.Squad.SQ_VENDOR_ANA_BRAY, mission.Slot.SQ_VENDOR_ANA_BRAY),
                unit(mission.Squad.UNDERPASS_ENCOUNTER1_SQUAD_0, mission.Slot.UNDERPASS_ENCOUNTER1_SQUAD_0),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6B2FD,
                    objective = mission.Slot.PF_EVENT_CABAL_SPIRE_1_OBJ_MAIN,
                    squads = {
                        unit(mission.Squad.HOTSPOT_EVENT_LEADER_SQUAD_80F6B2FD, mission.Slot.HOTSPOT_EVENT_LEADER_SQUAD_80F6B2FD),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_PF_CABAL_HARVESTERS_0_SQ_DROPSHIP, mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_CABAL_HARVESTERS_0_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_PF_CABAL_HARVESTERS_1_SQ_DROPSHIP, mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_CABAL_HARVESTERS_1_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_PF_CABAL_HARVESTERS_2_SQ_DROPSHIP, mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_CABAL_HARVESTERS_2_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_CENTER_GRP_1_TIER_1, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_CENTER_GRP_1_TIER_1),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_CENTER_GRP_1_TIER_2, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_CENTER_GRP_1_TIER_2),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_COMMANDER, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_COMMANDER),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_ENGAGEMENT_SKELETON_CREW_A, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_ENGAGEMENT_SKELETON_CREW_A),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_ENGAGEMENT_SKELETON_CREW_B, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_ENGAGEMENT_SKELETON_CREW_B),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_HEROIC_MELEE, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_HEROIC_MELEE),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_HEROIC_OUTSIDE_GROUP_1, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_HEROIC_OUTSIDE_GROUP_1),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_HEROIC_OUTSIDE_GROUP_2, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_HEROIC_OUTSIDE_GROUP_2),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_INTERCEPTOR_1, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_INTERCEPTOR_1),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_INTERCEPTOR_2, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_INTERCEPTOR_2),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_KEYHOLDER_PSION, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_KEYHOLDER_PSION),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_MELEE_GRP_4_TIER_1, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_MELEE_GRP_4_TIER_1),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_MELEE_GRP_4_TIER_2, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_MELEE_GRP_4_TIER_2),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_2_TIER_1, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_2_TIER_1),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_2_TIER_2, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_2_TIER_2),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_3_TIER_1, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_3_TIER_1),
                        unit(mission.Squad.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_3_TIER_2, mission.Slot.PF_EVENT_CABAL_SPIRE_1_SQ_OUTSIDE_GRP_3_TIER_2),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_CABAL_SPIRE_1_PF_REWARD_CHEST_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6B812,
                    objective = mission.Slot.WAVE_LOCATION_0_OBJECTIVE_80F6B812,
                    squads = {
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_BOSS_80F6B812, mission.Slot.BOSS_EATS_ALLIES_SQ_BOSS_80F6B812),
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_MINOR_FOOD_MINION_80F6B812, mission.Slot.BOSS_EATS_ALLIES_SQ_MINOR_FOOD_MINION_80F6B812),
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_SNIPER_GANG_80F6B812, mission.Slot.BOSS_EATS_ALLIES_SQ_SNIPER_GANG_80F6B812),
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_WIZARD_GANG_80F6B812, mission.Slot.BOSS_EATS_ALLIES_SQ_WIZARD_GANG_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOOMERS_MAJORS_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOOMERS_MAJORS_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOSS_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOSS_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL1_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL1_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL2_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL2_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_OGRE_MAJORS_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_OGRE_MAJORS_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_THRALL_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_THRALL_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F6B812),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F6B812, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F6B812),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_BOSS_80F6B812, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_BOSS_80F6B812),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_LEFT_80F6B812, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_LEFT_80F6B812),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_RIGHT_80F6B812, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_RIGHT_80F6B812),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EXPLODER_THRALL_CROWD_80F6B812, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EXPLODER_THRALL_CROWD_80F6B812),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_SWORD_DROPPER_80F6B812, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_SWORD_DROPPER_80F6B812),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_LEFT_80F6B812, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_LEFT_80F6B812),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_RIGHT_80F6B812, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_RIGHT_80F6B812),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_ACOLYTE_80F6B812, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_ACOLYTE_80F6B812),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_BOSS_80F6B812, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_BOSS_80F6B812),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE2_80F6B812, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE2_80F6B812),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE_80F6B812, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE_80F6B812),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE2_80F6B812, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE2_80F6B812),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE_80F6B812, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE_80F6B812),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_TOUGH_ACOLYTE_80F6B812, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_TOUGH_ACOLYTE_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_BOSS_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_BOSS_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL1_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL1_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL2_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL2_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_OGRE_MAJORS_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_OGRE_MAJORS_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_ORB_TROOPERS_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_ORB_TROOPERS_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_THRALL1_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_THRALL1_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_THRALL2_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_THRALL2_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F6B812),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_WIZARDS_MAJORS_80F6B812, mission.Slot.BOSS_SUPER_BONANZA_SQ_WIZARDS_MAJORS_80F6B812),
                        unit(mission.Squad.SQ_SHRIEKER1_80F6B812, mission.Slot.SQ_SHRIEKER1_80F6B812),
                        unit(mission.Squad.SQ_SHRIEKER2_80F6B812, mission.Slot.SQ_SHRIEKER2_80F6B812),
                        unit(mission.Squad.SQ_SHRIEKER3_80F6B812, mission.Slot.SQ_SHRIEKER3_80F6B812),
                        unit(mission.Squad.SQ_WIZARD_BOSS_ATTENDANT1_80F6B812, mission.Slot.SQ_WIZARD_BOSS_ATTENDANT1_80F6B812),
                        unit(mission.Squad.SQ_WIZARD_BOSS_ATTENDANT2_80F6B812, mission.Slot.SQ_WIZARD_BOSS_ATTENDANT2_80F6B812),
                    },
                    chest = {
                        mission.Slot.WAVE_LOCATION_0_O_BOSS_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_0_O_WAVE3_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_0_O_WAVE6_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_1_O_BOSS_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_1_O_WAVE3_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_1_O_WAVE6_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_2_O_BOSS_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_2_O_WAVE3_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_2_O_WAVE6_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_3_O_BOSS_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_3_O_WAVE3_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_3_O_WAVE6_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_4_O_BOSS_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_4_O_WAVE3_CHEST_80F6B812,
                        mission.Slot.WAVE_LOCATION_4_O_WAVE6_CHEST_80F6B812,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6B957,
                    objective = mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_OBJ_EVENT_ENEMY_ENTER_80F6B957,
                    squads = {
                        unit(mission.Squad.HOTSPOT_EVENT_LEADER_SQUAD_80F6B957, mission.Slot.HOTSPOT_EVENT_LEADER_SQUAD_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_1_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_1_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_2_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_2_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_3_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_3_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_0_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_0_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_1_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_1_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_2_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_2_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_2_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_2_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_80F6B957),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_SUPPORT_80F6B957, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_SUPPORT_80F6B957),
                        unit(mission.Squad.SNIPER_SQUAD, mission.Slot.SNIPER_SQUAD),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F6B957,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_SPAWN_FX_OBJECT_80F6B957,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6BACE,
                    objective = mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_OBJ_AMB_REPLACEMENT_80F6BACE,
                    squads = {
                        unit(mission.Squad.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F6BACE, mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F6BACE),
                    },
                    chest = {
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_CONVOY_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER0_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER1_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER2_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER3_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER4_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_CANNON_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_PRISONER_OBJECT_80F6BACE,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_SPAWN_FX_OBJECT_80F6BACE,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6BB2F,
                    objective = mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_OBJ_AMB_REPLACEMENT_80F6BB2F,
                    squads = {
                        unit(mission.Squad.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F6BB2F, mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F6BB2F),
                    },
                    chest = {
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_CONVOY_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER0_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER1_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER2_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER3_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER4_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_CANNON_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_PRISONER_OBJECT_80F6BB2F,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_SPAWN_FX_OBJECT_80F6BB2F,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6BB8A,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_OBJECTIVE_80F6BB8A,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80F6BB8A, mission.Slot.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80F6BB8A),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80F6BB8A, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80F6BB8A),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80F6BB8A, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80F6BB8A),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80F6BB8A, mission.Slot.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80F6BB8A),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F6BB8A,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_80F6BB8A,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6BC45,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_OBJECTIVE_80F6BC45,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80F6BC45, mission.Slot.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80F6BC45),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80F6BC45, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80F6BC45),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80F6BC45, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80F6BC45),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80F6BC45, mission.Slot.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80F6BC45),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F6BC45,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_80F6BC45,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F6BC76,
                    objective = mission.Slot.INTERCEPTOR_GANG_1_OBJ_INTERCEPTOR_EXIT_80F6BC76,
                    squads = {
                        unit(mission.Squad.INTERCEPTOR_GANG_1_SQ_EVENT_INTERCEPTOR_0_80F6BC76, mission.Slot.INTERCEPTOR_GANG_1_SQ_EVENT_INTERCEPTOR_0_80F6BC76),
                    },
                    chest = {
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80F6AB20_0002_0000_80F6AD2F,
            region = 16,
            -- Lost Sector in bubble 2.
            sector = {
                boss = mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80F73C69,
                squads = {
                    unit(mission.Squad.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80F73C69, mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_0_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_0_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_1_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_1_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_2_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_2_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_3_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_3_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_4_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_4_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_5_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_5_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_0_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_0_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_1_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_1_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_2_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_2_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_1_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_1_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_2_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_2_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_0_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_0_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_1_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_1_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_2_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_2_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_1_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_1_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_2_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_2_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_3_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_3_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_4_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_4_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_0_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_0_80F73C69),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_1_80F73C69, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_1_80F73C69),
                    unit(mission.Squad.SQ_HI_AREA_1_ANCHOR_0_80F73C69, mission.Slot.SQ_HI_AREA_1_ANCHOR_0_80F73C69),
                    unit(mission.Squad.SQ_HI_AREA_1_ANCHOR_1_80F73C69, mission.Slot.SQ_HI_AREA_1_ANCHOR_1_80F73C69),
                    unit(mission.Squad.SQ_HI_AREA_1_FODDER_0_80F73C69, mission.Slot.SQ_HI_AREA_1_FODDER_0_80F73C69),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80F73C83,
                },
            },
        },
        {
            state = mission.states.STATE_80F6AB20_0005_0000_80F76D8C,
            region = 40,
            patrol = {
                unit(mission.Squad.CORE_SQUAD_0, mission.Slot.CORE_SQUAD_0),
                unit(mission.Squad.CORE_SQUAD_1, mission.Slot.CORE_SQUAD_1),
                unit(mission.Squad.CORE_SQUAD_2, mission.Slot.CORE_SQUAD_2),
                unit(mission.Squad.CORNER_ENCOUNTER_SQUAD_0, mission.Slot.CORNER_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.CORNER_ENCOUNTER_SQUAD_1, mission.Slot.CORNER_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.HOLES_ENCOUNTER_SQUAD_0, mission.Slot.HOLES_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.HOLES_ENCOUNTER_SQUAD_1, mission.Slot.HOLES_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.HOLES_ENCOUNTER_SQUAD_2, mission.Slot.HOLES_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.OUTPOST_ENCOUNTER_SQUAD_0, mission.Slot.OUTPOST_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.OUTPOST_ENCOUNTER_SQUAD_1, mission.Slot.OUTPOST_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.OUTPOST_ENCOUNTER_SQUAD_2, mission.Slot.OUTPOST_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.RIVERBED_ENCOUNTER_SQUAD_0, mission.Slot.RIVERBED_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.RIVERBED_ENCOUNTER_SQUAD_1, mission.Slot.RIVERBED_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.RIVERBED_ENCOUNTER_SQUAD_2, mission.Slot.RIVERBED_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.STATION_ENCOUNTER_SQUAD_0, mission.Slot.STATION_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.STATION_ENCOUNTER_SQUAD_1, mission.Slot.STATION_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.STATION_ENCOUNTER_SQUAD_2, mission.Slot.STATION_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.STATION_ENCOUNTER_SQUAD_3, mission.Slot.STATION_ENCOUNTER_SQUAD_3),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F722F4,
                    objective = mission.Slot.WAVE_LOCATION_0_OBJECTIVE_80F722F4,
                    squads = {
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_BOSS_80F722F4, mission.Slot.BOSS_EATS_ALLIES_SQ_BOSS_80F722F4),
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_MINOR_FOOD_MINION_80F722F4, mission.Slot.BOSS_EATS_ALLIES_SQ_MINOR_FOOD_MINION_80F722F4),
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_SNIPER_GANG_80F722F4, mission.Slot.BOSS_EATS_ALLIES_SQ_SNIPER_GANG_80F722F4),
                        unit(mission.Squad.BOSS_EATS_ALLIES_SQ_WIZARD_GANG_80F722F4, mission.Slot.BOSS_EATS_ALLIES_SQ_WIZARD_GANG_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOOMERS_MAJORS_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOOMERS_MAJORS_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOSS_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_BOSS_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL1_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL1_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL2_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_EXPLODER_THRALL2_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_OGRE_MAJORS_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_OGRE_MAJORS_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_THRALL_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_THRALL_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F722F4),
                        unit(mission.Squad.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F722F4, mission.Slot.BOSS_OGRE_BACK_WEAKSPOT_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F722F4),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_BOSS_80F722F4, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_BOSS_80F722F4),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_LEFT_80F722F4, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_LEFT_80F722F4),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_RIGHT_80F722F4, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EARLY_FODDER_RIGHT_80F722F4),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EXPLODER_THRALL_CROWD_80F722F4, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_EXPLODER_THRALL_CROWD_80F722F4),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_SWORD_DROPPER_80F722F4, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_SWORD_DROPPER_80F722F4),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_LEFT_80F722F4, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_LEFT_80F722F4),
                        unit(mission.Squad.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_RIGHT_80F722F4, mission.Slot.BOSS_RELIC_DAMAGE_KNIGHT_SQ_TOUGH_FODDER_RIGHT_80F722F4),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_ACOLYTE_80F722F4, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_ACOLYTE_80F722F4),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_BOSS_80F722F4, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_BOSS_80F722F4),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE2_80F722F4, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE2_80F722F4),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE_80F722F4, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_MAJOR_OGRE_80F722F4),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE2_80F722F4, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE2_80F722F4),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE_80F722F4, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_OGRE_80F722F4),
                        unit(mission.Squad.BOSS_SHIELDED_NEAR_ALLIES_SQ_TOUGH_ACOLYTE_80F722F4, mission.Slot.BOSS_SHIELDED_NEAR_ALLIES_SQ_TOUGH_ACOLYTE_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_BOSS_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_BOSS_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL1_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL1_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL2_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_EXPLODER_THRALL2_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_OGRE_MAJORS_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_OGRE_MAJORS_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_ORB_TROOPERS_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_ORB_TROOPERS_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_SHIELDED_SWORD_KNIGHTS_MAJORS_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_THRALL1_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_THRALL1_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_THRALL2_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_THRALL2_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL1_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_TROOPER_BEAM_SNIPER_SMALL2_80F722F4),
                        unit(mission.Squad.BOSS_SUPER_BONANZA_SQ_WIZARDS_MAJORS_80F722F4, mission.Slot.BOSS_SUPER_BONANZA_SQ_WIZARDS_MAJORS_80F722F4),
                        unit(mission.Squad.SQ_SHRIEKER1_80F722F4, mission.Slot.SQ_SHRIEKER1_80F722F4),
                        unit(mission.Squad.SQ_SHRIEKER2_80F722F4, mission.Slot.SQ_SHRIEKER2_80F722F4),
                        unit(mission.Squad.SQ_SHRIEKER3_80F722F4, mission.Slot.SQ_SHRIEKER3_80F722F4),
                        unit(mission.Squad.SQ_WIZARD_BOSS_ATTENDANT1_80F722F4, mission.Slot.SQ_WIZARD_BOSS_ATTENDANT1_80F722F4),
                        unit(mission.Squad.SQ_WIZARD_BOSS_ATTENDANT2_80F722F4, mission.Slot.SQ_WIZARD_BOSS_ATTENDANT2_80F722F4),
                    },
                    chest = {
                        mission.Slot.WAVE_LOCATION_0_O_BOSS_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_0_O_WAVE3_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_0_O_WAVE6_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_1_O_BOSS_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_1_O_WAVE3_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_1_O_WAVE6_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_2_O_BOSS_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_2_O_WAVE3_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_2_O_WAVE6_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_3_O_BOSS_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_3_O_WAVE3_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_3_O_WAVE6_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_4_O_BOSS_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_4_O_WAVE3_CHEST_80F722F4,
                        mission.Slot.WAVE_LOCATION_4_O_WAVE6_CHEST_80F722F4,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F724AD,
                    objective = mission.Slot.PF_EVENT_HIVE_RITUAL_1_OBJ_MAIN,
                    squads = {
                        unit(mission.Squad.HOTSPOT_EVENT_LEADER_SQUAD_80F724AD, mission.Slot.HOTSPOT_EVENT_LEADER_SQUAD_80F724AD),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_INITIAL, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_INITIAL),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_INITIAL, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_INITIAL),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_DARKBLADE, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_DARKBLADE),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO0, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO0),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO3, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO3),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO4, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO4),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO5, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO5),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_INITIAL_NON_MAJOR, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_INITIAL_NON_MAJOR),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_INITIAL_NON_MAJOR, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_INITIAL_NON_MAJOR),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_WIZARD_BOSS, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_WIZARD_BOSS),
                        unit(mission.Squad.SQ_OGRE_PARADE_0, mission.Slot.SQ_OGRE_PARADE_0),
                        unit(mission.Squad.SQ_OGRE_PARADE_1, mission.Slot.SQ_OGRE_PARADE_1),
                        unit(mission.Squad.SQ_OGRE_PARADE_2, mission.Slot.SQ_OGRE_PARADE_2),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F725EE,
                    objective = mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_OBJ_EVENT_ENEMY_ENTER_80F725EE,
                    squads = {
                        unit(mission.Squad.HOTSPOT_EVENT_LEADER_SQUAD_80F725EE, mission.Slot.HOTSPOT_EVENT_LEADER_SQUAD_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_1_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_1_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_2_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_2_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_3_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_HEROIC_TRIGGER_3_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_0_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_0_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_1_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_1_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_2_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MAJORS_2_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_2_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_2_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_MEDITATION_WIZARD_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_80F725EE),
                        unit(mission.Squad.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_SUPPORT_80F725EE, mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_SQ_ULTRA_SUPPORT_80F725EE),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F725EE,
                        mission.Slot.PF_EVENT_COUNTDOWN_DROPSHIP_CHEST_PREFAB_SPAWN_FX_OBJECT_80F725EE,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F726F5,
                    objective = mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_OBJ_AMB_REPLACEMENT_80F726F5,
                    squads = {
                        unit(mission.Squad.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F726F5, mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F726F5),
                    },
                    chest = {
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_CONVOY_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER0_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER1_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER2_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER3_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER4_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_CANNON_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_PRISONER_OBJECT_80F726F5,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_SPAWN_FX_OBJECT_80F726F5,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F72756,
                    objective = mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_OBJ_AMB_REPLACEMENT_80F72756,
                    squads = {
                        unit(mission.Squad.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F72756, mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_AMB_REPLACEMENT_0_SQ_AMBIENT_REPLACEMENT_80F72756),
                    },
                    chest = {
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_CONVOY_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER0_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER1_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER2_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER3_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_TIER4_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_CANNON_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_CHEST_VEX_PRISONER_OBJECT_80F72756,
                        mission.Slot.EVENT_AMBIENT_AMBUSH_PF_AMB_REPLACEMENT_GROUP_0_PF_TREASURE_CHEST_SPAWN_FX_OBJECT_80F72756,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F72787,
                    objective = mission.Slot.INTERCEPTOR_GANG_1_OBJ_INTERCEPTOR_EXIT_80F72787,
                    squads = {
                        unit(mission.Squad.INTERCEPTOR_GANG_1_SQ_EVENT_INTERCEPTOR_0_80F72787, mission.Slot.INTERCEPTOR_GANG_1_SQ_EVENT_INTERCEPTOR_0_80F72787),
                    },
                    chest = {
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F728B7,
                    objective = mission.Slot.PF_EVENT_SKIRMISH01_OBJ_SKIRMISH_80F728B7,
                    squads = {
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_B_END_ANCHOR_80F728B7, mission.Slot.PF_EVENT_SKIRMISH01_SQ_B_END_ANCHOR_80F728B7),
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_B_INTRO_ANCHOR_80F728B7, mission.Slot.PF_EVENT_SKIRMISH01_SQ_B_INTRO_ANCHOR_80F728B7),
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_B_MID_ANCHOR_80F728B7, mission.Slot.PF_EVENT_SKIRMISH01_SQ_B_MID_ANCHOR_80F728B7),
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_B_MID_WAVE_0_80F728B7, mission.Slot.PF_EVENT_SKIRMISH01_SQ_B_MID_WAVE_0_80F728B7),
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_B_MID_WAVE_1_80F728B7, mission.Slot.PF_EVENT_SKIRMISH01_SQ_B_MID_WAVE_1_80F728B7),
                    },
                    chest = {
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F72929,
                    objective = mission.Slot.PF_EVENT_SKIRMISH01_OBJ_SKIRMISH_80F72929,
                    squads = {
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_B_END_ANCHOR_80F72929, mission.Slot.PF_EVENT_SKIRMISH01_SQ_B_END_ANCHOR_80F72929),
                        unit(mission.Squad.PF_EVENT_SKIRMISH01_SQ_B_MID_WAVE_1_80F72929, mission.Slot.PF_EVENT_SKIRMISH01_SQ_B_MID_WAVE_1_80F72929),
                    },
                    chest = {
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80F6AB20_0006_0000_80F76D8D,
            region = 48,
            -- Lost Sector in bubble 6.
            sector = {
                boss = mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80F7606F,
                squads = {
                    unit(mission.Squad.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80F7606F, mission.Slot.PF2_OUTLAWS_KILL_OLD_BOSS_SQ_OLD_BOSS_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_0_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_0_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_1_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_1_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_2_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_2_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_3_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_3_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_4_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_4_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_5_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_5_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_0_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_0_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_1_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_1_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_2_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_ACOLYTE_REINFORCE_2_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_1_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_1_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_2_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_EXPLODER_THRALL_2_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_0_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_0_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_1_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_1_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_2_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_2_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_1_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_1_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_2_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_2_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_3_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_3_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_4_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_INITIAL_4_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_0_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_0_80F7606F),
                    unit(mission.Squad.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_1_80F7606F, mission.Slot.PF2_OUTLAWS_POLARIS_CORE_SQ_THRALL_REINFORCE_1_80F7606F),
                    unit(mission.Squad.SQ_HALL_A, mission.Slot.SQ_HALL_A),
                    unit(mission.Squad.SQ_HI_AREA_1_ANCHOR_0_80F7606F, mission.Slot.SQ_HI_AREA_1_ANCHOR_0_80F7606F),
                    unit(mission.Squad.SQ_HI_AREA_1_ANCHOR_1_80F7606F, mission.Slot.SQ_HI_AREA_1_ANCHOR_1_80F7606F),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80F76089,
                },
            },
        },
        {
            state = mission.states.STATE_80F6AB20_0007_0000_80F76D8E,
            region = 56,
            patrol = {
                unit(mission.Squad.BALCONY_ENCOUNTER_SQUAD_0, mission.Slot.BALCONY_ENCOUNTER_SQUAD_0),
                unit(mission.Squad.BALCONY_ENCOUNTER_SQUAD_1, mission.Slot.BALCONY_ENCOUNTER_SQUAD_1),
                unit(mission.Squad.BALCONY_ENCOUNTER_SQUAD_2, mission.Slot.BALCONY_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.BALCONY_ENCOUNTER_SQUAD_3, mission.Slot.BALCONY_ENCOUNTER_SQUAD_3),
                unit(mission.Squad.BALCONY_ENCOUNTER_SQUAD_4, mission.Slot.BALCONY_ENCOUNTER_SQUAD_4),
                unit(mission.Squad.BALCONY_ENCOUNTER_SQUAD_5, mission.Slot.BALCONY_ENCOUNTER_SQUAD_5),
                unit(mission.Squad.CABAL_ADDS_0, mission.Slot.CABAL_ADDS_0),
                unit(mission.Squad.CABAL_ADDS_1, mission.Slot.CABAL_ADDS_1),
                unit(mission.Squad.CABAL_ADDS_2, mission.Slot.CABAL_ADDS_2),
                unit(mission.Squad.CABAL_ADDS_3, mission.Slot.CABAL_ADDS_3),
                unit(mission.Squad.CABAL_ADDS_4, mission.Slot.CABAL_ADDS_4),
                unit(mission.Squad.CABAL_ADDS_5, mission.Slot.CABAL_ADDS_5),
                unit(mission.Squad.CABAL_ADDS_6, mission.Slot.CABAL_ADDS_6),
                unit(mission.Squad.CABAL_ADDS_7, mission.Slot.CABAL_ADDS_7),
                unit(mission.Squad.CABAL_FRONT_ROOM_0, mission.Slot.CABAL_FRONT_ROOM_0),
                unit(mission.Squad.CABAL_FRONT_ROOM_1, mission.Slot.CABAL_FRONT_ROOM_1),
                unit(mission.Squad.CABAL_FRONT_ROOM_2, mission.Slot.CABAL_FRONT_ROOM_2),
                unit(mission.Squad.CABAL_FRONT_ROOM_3, mission.Slot.CABAL_FRONT_ROOM_3),
                unit(mission.Squad.CABAL_FRONT_ROOM_4, mission.Slot.CABAL_FRONT_ROOM_4),
                unit(mission.Squad.CABAL_FRONT_ROOM_5, mission.Slot.CABAL_FRONT_ROOM_5),
                unit(mission.Squad.CABAL_FRONT_ROOM_6, mission.Slot.CABAL_FRONT_ROOM_6),
                unit(mission.Squad.CABAL_FRONT_ROOM_7, mission.Slot.CABAL_FRONT_ROOM_7),
                unit(mission.Squad.CABAL_MID_ROOM_0, mission.Slot.CABAL_MID_ROOM_0),
                unit(mission.Squad.CABAL_MID_ROOM_1, mission.Slot.CABAL_MID_ROOM_1),
            },
        },
        {
            state = mission.states.STATE_80F6AB20_0008_0000_80F76D8F,
            region = 64,
            patrol = {
                unit(mission.Squad.CABALTWO_LEGIONARY_CENTER, mission.Slot.CABALTWO_LEGIONARY_CENTER),
                unit(mission.Squad.CABALTWO_LEGIONARY_LEFT, mission.Slot.CABALTWO_LEGIONARY_LEFT),
                unit(mission.Squad.CABALTWO_LEGIONARY_RIGHT, mission.Slot.CABALTWO_LEGIONARY_RIGHT),
                unit(mission.Squad.CABALTWO_PHALANX_CENTER, mission.Slot.CABALTWO_PHALANX_CENTER),
                unit(mission.Squad.CABALTWO_PHALANX_LEFT, mission.Slot.CABALTWO_PHALANX_LEFT),
                unit(mission.Squad.CABALTWO_PHALANX_RIGHT, mission.Slot.CABALTWO_PHALANX_RIGHT),
                unit(mission.Squad.CABAL_SQUAD_0, mission.Slot.CABAL_SQUAD_0),
                unit(mission.Squad.CABAL_SQUAD_1, mission.Slot.CABAL_SQUAD_1),
                unit(mission.Squad.CABAL_SQUAD_2, mission.Slot.CABAL_SQUAD_2),
                unit(mission.Squad.CABAL_SQUAD_3, mission.Slot.CABAL_SQUAD_3),
                unit(mission.Squad.CABAL_SQUAD_4, mission.Slot.CABAL_SQUAD_4),
                unit(mission.Squad.HIVE_SQUAD_A, mission.Slot.HIVE_SQUAD_A),
                unit(mission.Squad.HIVE_SQUAD_B, mission.Slot.HIVE_SQUAD_B),
                unit(mission.Squad.HIVE_SQUAD_C, mission.Slot.HIVE_SQUAD_C),
                unit(mission.Squad.HIVE_SQUAD_D, mission.Slot.HIVE_SQUAD_D),
            },
        },
        {
            state = mission.states.STATE_80F6AB20_0009_0000_80F76D90,
            region = 72,
            patrol = {
                unit(mission.Squad.BACK_CABAL_SQUAD, mission.Slot.BACK_CABAL_SQUAD),
                unit(mission.Squad.CABAL_0_80F765BA, mission.Slot.CABAL_0_80F765BA),
                unit(mission.Squad.CABAL_1_80F765BA, mission.Slot.CABAL_1_80F765BA),
                unit(mission.Squad.CABAL_2_80F765BA, mission.Slot.CABAL_2_80F765BA),
                unit(mission.Squad.DROPSHIP_SQUAD, mission.Slot.DROPSHIP_SQUAD),
                unit(mission.Squad.FRONT_CABAL_SQUAD, mission.Slot.FRONT_CABAL_SQUAD),
                unit(mission.Squad.LEGIONARY_SQUAD, mission.Slot.LEGIONARY_SQUAD),
                unit(mission.Squad.PF2_AMBIENT_BALCONY_SQUAD_0, mission.Slot.PF2_AMBIENT_BALCONY_SQUAD_0),
                unit(mission.Squad.PF2_AMBIENT_BALCONY_SQUAD_1, mission.Slot.PF2_AMBIENT_BALCONY_SQUAD_1),
                unit(mission.Squad.PSION_SQUAD, mission.Slot.PSION_SQUAD),
                unit(mission.Squad.THRESHER, mission.Slot.THRESHER),
                unit(mission.Squad.THRESHER_B, mission.Slot.THRESHER_B),
            },
        },
        {
            state = mission.states.STATE_80F6AB20_000A_0000_80F76D91,
            region = 80,
            patrol = {
                unit(mission.Squad.AMBIENT_ELEVATOR_RIGHT_1_SQUAD_0, mission.Slot.AMBIENT_ELEVATOR_RIGHT_1_SQUAD_0),
                unit(mission.Squad.AMBIENT_ELEVATOR_RIGHT_1_SQUAD_1, mission.Slot.AMBIENT_ELEVATOR_RIGHT_1_SQUAD_1),
                unit(mission.Squad.ASPIRANT_GUARDS_A, mission.Slot.ASPIRANT_GUARDS_A),
                unit(mission.Squad.ASPIRANT_GUARDS_B, mission.Slot.ASPIRANT_GUARDS_B),
                unit(mission.Squad.ASPIRANT_SQUAD, mission.Slot.ASPIRANT_SQUAD),
                unit(mission.Squad.CABAL_0_80F76838, mission.Slot.CABAL_0_80F76838),
                unit(mission.Squad.CABAL_0_80F768FF, mission.Slot.CABAL_0_80F768FF),
                unit(mission.Squad.CABAL_1_80F76838, mission.Slot.CABAL_1_80F76838),
                unit(mission.Squad.CABAL_1_80F768FF, mission.Slot.CABAL_1_80F768FF),
                unit(mission.Squad.CABAL_2_80F76838, mission.Slot.CABAL_2_80F76838),
                unit(mission.Squad.CABAL_2_80F768FF, mission.Slot.CABAL_2_80F768FF),
                unit(mission.Squad.CABAL_3_80F76838, mission.Slot.CABAL_3_80F76838),
                unit(mission.Squad.CABAL_3_80F768FF, mission.Slot.CABAL_3_80F768FF),
                unit(mission.Squad.CABAL_4, mission.Slot.CABAL_4),
                unit(mission.Squad.CABAL_5, mission.Slot.CABAL_5),
                unit(mission.Squad.CABAL_6, mission.Slot.CABAL_6),
                unit(mission.Squad.CABAL_LOWER_BACK_SQUAD, mission.Slot.CABAL_LOWER_BACK_SQUAD),
                unit(mission.Squad.CABAL_LOWER_FRONT_SQUAD, mission.Slot.CABAL_LOWER_FRONT_SQUAD),
                unit(mission.Squad.CABAL_LOWER_INITIAL1A_SQUAD, mission.Slot.CABAL_LOWER_INITIAL1A_SQUAD),
                unit(mission.Squad.CABAL_LOWER_INITIAL1B_SQUAD, mission.Slot.CABAL_LOWER_INITIAL1B_SQUAD),
                unit(mission.Squad.CABAL_LOWER_INITIAL1C_SQUAD, mission.Slot.CABAL_LOWER_INITIAL1C_SQUAD),
                unit(mission.Squad.CABAL_UPPER_BACK_SQUAD, mission.Slot.CABAL_UPPER_BACK_SQUAD),
                unit(mission.Squad.CABAL_UPPER_FRONT_SQUAD, mission.Slot.CABAL_UPPER_FRONT_SQUAD),
                unit(mission.Squad.FLAYER_1, mission.Slot.FLAYER_1),
            },
        },
        {
            state = mission.states.STATE_80F6AB20_000B_0000_80F76D92,
            region = 88,
            patrol = {
                unit(mission.Squad.SQ_XOL, mission.Slot.SQ_XOL),
            },
        },
        {
            state = mission.states.STATE_80F6AB20_000C_0000_80F76D93,
            region = 96,
            patrol = {
                unit(mission.Squad.SQ_LIST_ANCHOR_BOOMER_0, mission.Slot.SQ_LIST_ANCHOR_BOOMER_0),
                unit(mission.Squad.SQ_LIST_ANCHOR_BOOMER_1, mission.Slot.SQ_LIST_ANCHOR_BOOMER_1),
                unit(mission.Squad.SQ_LIST_ANCHOR_BOOMER_2, mission.Slot.SQ_LIST_ANCHOR_BOOMER_2),
                unit(mission.Squad.SQ_LIST_ANCHOR_OGRE_0, mission.Slot.SQ_LIST_ANCHOR_OGRE_0),
                unit(mission.Squad.SQ_LIST_ANCHOR_OGRE_1, mission.Slot.SQ_LIST_ANCHOR_OGRE_1),
                unit(mission.Squad.SQ_LIST_ANCHOR_WIZARD_0, mission.Slot.SQ_LIST_ANCHOR_WIZARD_0),
                unit(mission.Squad.SQ_LIST_ANCHOR_WIZARD_1, mission.Slot.SQ_LIST_ANCHOR_WIZARD_1),
                unit(mission.Squad.SQ_LIST_ANCHOR_WIZARD_2, mission.Slot.SQ_LIST_ANCHOR_WIZARD_2),
                unit(mission.Squad.SQ_LIST_BOOMER_0, mission.Slot.SQ_LIST_BOOMER_0),
                unit(mission.Squad.SQ_LIST_BOOMER_1, mission.Slot.SQ_LIST_BOOMER_1),
                unit(mission.Squad.SQ_LIST_CRUSADER_0, mission.Slot.SQ_LIST_CRUSADER_0),
                unit(mission.Squad.SQ_LIST_CRUSADER_1, mission.Slot.SQ_LIST_CRUSADER_1),
                unit(mission.Squad.SQ_LIST_CRUSADER_2, mission.Slot.SQ_LIST_CRUSADER_2),
                unit(mission.Squad.SQ_LIST_EXPLODER_0, mission.Slot.SQ_LIST_EXPLODER_0),
                unit(mission.Squad.SQ_LIST_EXPLODER_1, mission.Slot.SQ_LIST_EXPLODER_1),
                unit(mission.Squad.SQ_LIST_EXPLODER_2, mission.Slot.SQ_LIST_EXPLODER_2),
                unit(mission.Squad.SQ_LIST_SNIPER_0, mission.Slot.SQ_LIST_SNIPER_0),
                unit(mission.Squad.SQ_LIST_SNIPER_1, mission.Slot.SQ_LIST_SNIPER_1),
                unit(mission.Squad.SQ_LIST_THRALL_0, mission.Slot.SQ_LIST_THRALL_0),
                unit(mission.Squad.SQ_LIST_THRALL_1, mission.Slot.SQ_LIST_THRALL_1),
                unit(mission.Squad.SQ_LIST_THRALL_2, mission.Slot.SQ_LIST_THRALL_2),
                unit(mission.Squad.SQ_LIST_THRALL_3, mission.Slot.SQ_LIST_THRALL_3),
                unit(mission.Squad.SQ_LIST_TROOPER_0, mission.Slot.SQ_LIST_TROOPER_0),
                unit(mission.Squad.SQ_LIST_TROOPER_1, mission.Slot.SQ_LIST_TROOPER_1),
            },
        },
    }
end
