-- Generated from installed mission data. Do not edit.
-- Zones are authored state rows; population and event sites come from the slice sets.
return function(mission, freeroam)
    local unit = freeroam.unit
    return {
        {
            state = mission.states.STATE_80FC9645_0003_0000_80FC95E2,
            region = 24,
            patrol = {
                unit(mission.Squad.MELEE_SQUAD_80FD452B, mission.Slot.MELEE_SQUAD_80FD452B),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FC968D, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FC968D),
                unit(mission.Squad.SHORT_RANGE_SQUAD, mission.Slot.SHORT_RANGE_SQUAD),
                unit(mission.Squad.SQ_ANCHOR_1, mission.Slot.SQ_ANCHOR_1),
                unit(mission.Squad.SQ_ANCHOR_2, mission.Slot.SQ_ANCHOR_2),
                unit(mission.Squad.SQ_ANCHOR_80FD4451, mission.Slot.SQ_ANCHOR_80FD4451),
                unit(mission.Squad.SQ_FORSAKEN_FIRST_ROOM_0, mission.Slot.SQ_FORSAKEN_FIRST_ROOM_0),
                unit(mission.Squad.SQ_FORSAKEN_FIRST_ROOM_1, mission.Slot.SQ_FORSAKEN_FIRST_ROOM_1),
                unit(mission.Squad.SQ_FORSAKEN_FIRST_ROOM_2, mission.Slot.SQ_FORSAKEN_FIRST_ROOM_2),
                unit(mission.Squad.SQ_HIVE_FIRST_ROOM_0, mission.Slot.SQ_HIVE_FIRST_ROOM_0),
                unit(mission.Squad.SQ_HIVE_FIRST_ROOM_1, mission.Slot.SQ_HIVE_FIRST_ROOM_1),
                unit(mission.Squad.SQ_HIVE_FIRST_ROOM_2, mission.Slot.SQ_HIVE_FIRST_ROOM_2),
                unit(mission.Squad.SQ_INTRO_FORSAKEN_1, mission.Slot.SQ_INTRO_FORSAKEN_1),
                unit(mission.Squad.SQ_MAP_OGRE, mission.Slot.SQ_MAP_OGRE),
                unit(mission.Squad.SQ_OGRE_80FD478E, mission.Slot.SQ_OGRE_80FD478E),
                unit(mission.Squad.SQ_RANGED_BACK_1, mission.Slot.SQ_RANGED_BACK_1),
                unit(mission.Squad.SQ_RANGED_BACK_2, mission.Slot.SQ_RANGED_BACK_2),
                unit(mission.Squad.SQ_RANGED_BACK_3, mission.Slot.SQ_RANGED_BACK_3),
                unit(mission.Squad.SQ_RANGED_BOTTOM_1, mission.Slot.SQ_RANGED_BOTTOM_1),
                unit(mission.Squad.SQ_RANGED_BOTTOM_2, mission.Slot.SQ_RANGED_BOTTOM_2),
                unit(mission.Squad.SQ_RANGED_BOTTOM_3, mission.Slot.SQ_RANGED_BOTTOM_3),
                unit(mission.Squad.SQ_RANGED_HIGH, mission.Slot.SQ_RANGED_HIGH),
                unit(mission.Squad.SQ_RANGED_LEFT_1, mission.Slot.SQ_RANGED_LEFT_1),
                unit(mission.Squad.SQ_RANGED_LEFT_2, mission.Slot.SQ_RANGED_LEFT_2),
            },
        },
        {
            state = mission.states.STATE_80FC9645_0004_0000_80FC95E3,
            region = 32,
            patrol = {
                unit(mission.Squad.PF2_CRYPT_OPENING_SIMPLE_SQUAD_0, mission.Slot.PF2_CRYPT_OPENING_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_CRYPT_OPENING_SIMPLE_SQUAD_1, mission.Slot.PF2_CRYPT_OPENING_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_CRYPT_OPENING_SIMPLE_SQUAD_2, mission.Slot.PF2_CRYPT_OPENING_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_CRYPT_OPENING_SIMPLE_SQUAD_3, mission.Slot.PF2_CRYPT_OPENING_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FC9709, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FC9709),
            },
        },
        {
            state = mission.states.STATE_80FC9645_0005_0000_80FC95E4,
            region = 40,
            patrol = {
                unit(mission.Squad.PF_BREAKABLE_CAGE_0_SQ_CAPTIVE, mission.Slot.PF_BREAKABLE_CAGE_0_SQ_CAPTIVE),
                unit(mission.Squad.PF_BREAKABLE_CAGE_0_SQ_JAILER, mission.Slot.PF_BREAKABLE_CAGE_0_SQ_JAILER),
                unit(mission.Squad.PF_BREAKABLE_CAGE_0_SQ_JAILER_BKUP, mission.Slot.PF_BREAKABLE_CAGE_0_SQ_JAILER_BKUP),
                unit(mission.Squad.PF_BREAKABLE_CAGE_1_SQ_CAPTIVE, mission.Slot.PF_BREAKABLE_CAGE_1_SQ_CAPTIVE),
                unit(mission.Squad.PF_BREAKABLE_CAGE_1_SQ_JAILER, mission.Slot.PF_BREAKABLE_CAGE_1_SQ_JAILER),
                unit(mission.Squad.PF_BREAKABLE_CAGE_1_SQ_JAILER_BKUP, mission.Slot.PF_BREAKABLE_CAGE_1_SQ_JAILER_BKUP),
                unit(mission.Squad.PF_BREAKABLE_CAGE_2_SQ_CAPTIVE, mission.Slot.PF_BREAKABLE_CAGE_2_SQ_CAPTIVE),
                unit(mission.Squad.PF_BREAKABLE_CAGE_2_SQ_JAILER, mission.Slot.PF_BREAKABLE_CAGE_2_SQ_JAILER),
                unit(mission.Squad.PF_BREAKABLE_CAGE_2_SQ_JAILER_BKUP, mission.Slot.PF_BREAKABLE_CAGE_2_SQ_JAILER_BKUP),
                unit(mission.Squad.PF_BREAKABLE_CAGE_3_SQ_CAPTIVE, mission.Slot.PF_BREAKABLE_CAGE_3_SQ_CAPTIVE),
                unit(mission.Squad.PF_BREAKABLE_CAGE_3_SQ_JAILER, mission.Slot.PF_BREAKABLE_CAGE_3_SQ_JAILER),
                unit(mission.Squad.PF_BREAKABLE_CAGE_3_SQ_JAILER_BKUP, mission.Slot.PF_BREAKABLE_CAGE_3_SQ_JAILER_BKUP),
                unit(mission.Squad.SQ_BRIDGE, mission.Slot.SQ_BRIDGE),
                unit(mission.Squad.SQ_BRIDGE_MAJOR, mission.Slot.SQ_BRIDGE_MAJOR),
                unit(mission.Squad.SQ_SUPPORT_1_80FD4961, mission.Slot.SQ_SUPPORT_1_80FD4961),
                unit(mission.Squad.SQ_SUPPORT_2_80FD4961, mission.Slot.SQ_SUPPORT_2_80FD4961),
                unit(mission.Squad.SQ_SUPPORT_3_80FD4961, mission.Slot.SQ_SUPPORT_3_80FD4961),
            },
        },
        {
            state = mission.states.STATE_80FC9645_0006_0000_80FC95E5,
            region = 48,
            patrol = {
                unit(mission.Squad.ANCHOR_SQUAD_80FD49E1, mission.Slot.ANCHOR_SQUAD_80FD49E1),
                unit(mission.Squad.ANCHOR_SQUAD_80FD4A52, mission.Slot.ANCHOR_SQUAD_80FD4A52),
                unit(mission.Squad.DOOR_GUARD_SQUAD, mission.Slot.DOOR_GUARD_SQUAD),
                unit(mission.Squad.MELEE_SQUAD_80FD4A11, mission.Slot.MELEE_SQUAD_80FD4A11),
                unit(mission.Squad.SHORT_RANGE_SQUAD_1_80FD49E1, mission.Slot.SHORT_RANGE_SQUAD_1_80FD49E1),
                unit(mission.Squad.SHORT_RANGE_SQUAD_1_80FD4A11, mission.Slot.SHORT_RANGE_SQUAD_1_80FD4A11),
                unit(mission.Squad.SHORT_RANGE_SQUAD_1_80FD4A52, mission.Slot.SHORT_RANGE_SQUAD_1_80FD4A52),
                unit(mission.Squad.SHORT_RANGE_SQUAD_2_80FD49E1, mission.Slot.SHORT_RANGE_SQUAD_2_80FD49E1),
                unit(mission.Squad.SHORT_RANGE_SQUAD_2_80FD4A11, mission.Slot.SHORT_RANGE_SQUAD_2_80FD4A11),
                unit(mission.Squad.SHORT_RANGE_SQUAD_2_80FD4A52, mission.Slot.SHORT_RANGE_SQUAD_2_80FD4A52),
                unit(mission.Squad.SHORT_RANGE_SQUAD_3_80FD49E1, mission.Slot.SHORT_RANGE_SQUAD_3_80FD49E1),
                unit(mission.Squad.SHORT_RANGE_SQUAD_3_80FD4A11, mission.Slot.SHORT_RANGE_SQUAD_3_80FD4A11),
                unit(mission.Squad.SHORT_RANGE_SQUAD_3_80FD4A52, mission.Slot.SHORT_RANGE_SQUAD_3_80FD4A52),
                unit(mission.Squad.SHORT_RANGE_SQUAD_4, mission.Slot.SHORT_RANGE_SQUAD_4),
                unit(mission.Squad.SHORT_RANGE_SQUAD_5, mission.Slot.SHORT_RANGE_SQUAD_5),
                unit(mission.Squad.SNIPER_SQUAD_1_80FD4A52, mission.Slot.SNIPER_SQUAD_1_80FD4A52),
                unit(mission.Squad.SNIPER_SQUAD_2_80FD4A52, mission.Slot.SNIPER_SQUAD_2_80FD4A52),
                unit(mission.Squad.SNIPER_SQUAD_3, mission.Slot.SNIPER_SQUAD_3),
                unit(mission.Squad.SQ_CONVEYOR_FODDER_0, mission.Slot.SQ_CONVEYOR_FODDER_0),
                unit(mission.Squad.SQ_CONVEYOR_FODDER_1, mission.Slot.SQ_CONVEYOR_FODDER_1),
                unit(mission.Squad.SQ_CONVEYOR_FODDER_2, mission.Slot.SQ_CONVEYOR_FODDER_2),
                unit(mission.Squad.SQ_CONVEYOR_FODDER_3, mission.Slot.SQ_CONVEYOR_FODDER_3),
                unit(mission.Squad.SQ_CONVEYOR_FODDER_4, mission.Slot.SQ_CONVEYOR_FODDER_4),
                unit(mission.Squad.SQ_CONVEYOR_FODDER_5, mission.Slot.SQ_CONVEYOR_FODDER_5),
            },
        },
        {
            state = mission.states.STATE_80FC9645_0007_0000_80FC95E6,
            region = 56,
            patrol = {
                unit(mission.Squad.MOSQUITO01_SQUAD, mission.Slot.MOSQUITO01_SQUAD),
                unit(mission.Squad.MOSQUITO01_SQUAD_1, mission.Slot.MOSQUITO01_SQUAD_1),
                unit(mission.Squad.MOSQUITO01_SQUAD_2, mission.Slot.MOSQUITO01_SQUAD_2),
                unit(mission.Squad.PF2_CAMP_STAY_SQUAD_0, mission.Slot.PF2_CAMP_STAY_SQUAD_0),
                unit(mission.Squad.PF2_CAMP_TRAVEL_SQUAD_0, mission.Slot.PF2_CAMP_TRAVEL_SQUAD_0),
                unit(mission.Squad.PF2_CLIFF_SIMPLE_SQUAD_0, mission.Slot.PF2_CLIFF_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_CRYPT_SIMPLE_SQUAD_0, mission.Slot.PF2_CRYPT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_CRYPT_SIMPLE_SQUAD_1, mission.Slot.PF2_CRYPT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_CRYPT_SIMPLE_SQUAD_2, mission.Slot.PF2_CRYPT_SIMPLE_SQUAD_2),
                unit(mission.Squad.SQ_ABOMINATION, mission.Slot.SQ_ABOMINATION),
                unit(mission.Squad.SQ_AMBUSH_1, mission.Slot.SQ_AMBUSH_1),
                unit(mission.Squad.SQ_AMBUSH_2, mission.Slot.SQ_AMBUSH_2),
                unit(mission.Squad.SQ_AMBUSH_3, mission.Slot.SQ_AMBUSH_3),
                unit(mission.Squad.SQ_DEFEND_FODDER_1, mission.Slot.SQ_DEFEND_FODDER_1),
                unit(mission.Squad.SQ_DEFEND_FODDER_2, mission.Slot.SQ_DEFEND_FODDER_2),
                unit(mission.Squad.SQ_DEFEND_FODDER_3, mission.Slot.SQ_DEFEND_FODDER_3),
                unit(mission.Squad.SQ_INITIAL_FODDER_1, mission.Slot.SQ_INITIAL_FODDER_1),
                unit(mission.Squad.SQ_INITIAL_FODDER_2, mission.Slot.SQ_INITIAL_FODDER_2),
                unit(mission.Squad.SQ_INITIAL_FODDER_3, mission.Slot.SQ_INITIAL_FODDER_3),
                unit(mission.Squad.SQ_MAD_BOMBER_80FD5BB1, mission.Slot.SQ_MAD_BOMBER_80FD5BB1),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD50FD,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD50FD,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD50FD, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD50FD),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD50FD,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD50FD,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD50FD,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD5152,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD5152,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD5152, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD5152),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD5152,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD5152,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD5152,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD52DF,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_2_OBJECTIVE_80FD52DF,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD52DF, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD52DF),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD52DF, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD52DF),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD52DF, mission.Slot.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD52DF),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD52DF,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD52DF,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD533A,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_2_OBJECTIVE_80FD533A,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD533A, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD533A),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD533A, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD533A),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD533A, mission.Slot.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD533A),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD533A,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD533A,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD5497,
                    objective = mission.Slot.PF_EVENT_CRYO_POD_CORE_OBJ_BOSS_80FD5497,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FD5497),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FD5497, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FD5497),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER0_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER1_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER2_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER3_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER4_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT_80FD5497,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_SPAWN_FX_OBJECT_80FD5497,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD58B9,
                    objective = mission.Slot.OBJ_FLASHPOINT,
                    squads = {
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_PF_FALLEN_DRILL_SQ_DROPSHIP, mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_PF_FALLEN_DRILL_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_PF_FALLEN_DRILL_SQ_DROPSHIP, mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_PF_FALLEN_DRILL_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_PF_FALLEN_DRILL_SQ_DROPSHIP, mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_PF_FALLEN_DRILL_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDERS_0, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDERS_0),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDERS_1, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDERS_1),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDERS_2, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDERS_2),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDER_ANCHORS_0, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDER_ANCHORS_0),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDER_ANCHORS_1, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDER_ANCHORS_1),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDER_ANCHORS_2, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDER_ANCHORS_2),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDER_BOSS, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDER_BOSS),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDER_BOSS_1, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDER_BOSS_1),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_DEFENDER_BOSS_2, mission.Slot.PF_EVENT_MULTIPOINT_SQ_DEFENDER_BOSS_2),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_HEROIC_FINALE_BOSS, mission.Slot.PF_EVENT_MULTIPOINT_SQ_HEROIC_FINALE_BOSS),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_HEROIC_FINALE_WAVE, mission.Slot.PF_EVENT_MULTIPOINT_SQ_HEROIC_FINALE_WAVE),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_HEROIC_HEAVY_WAVE, mission.Slot.PF_EVENT_MULTIPOINT_SQ_HEROIC_HEAVY_WAVE),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_HEROIC_INITIAL_LIGHT_WAVE, mission.Slot.PF_EVENT_MULTIPOINT_SQ_HEROIC_INITIAL_LIGHT_WAVE),
                        unit(mission.Squad.PF_EVENT_MULTIPOINT_SQ_HEROIC_STEALTH_MELEE_WAVE, mission.Slot.PF_EVENT_MULTIPOINT_SQ_HEROIC_STEALTH_MELEE_WAVE),
                        unit(mission.Squad.SQ_FLASHPOINT, mission.Slot.SQ_FLASHPOINT),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_0_CHEST_PREFAB_SPAWN_FX_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_1_CHEST_PREFAB_SPAWN_FX_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_MULTIPOINT_PF_PLACEMENT_2_CHEST_PREFAB_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD5A2C,
                    objective = mission.Slot.PF_EVENT_SOUL_HARVESTER_OBJ_EVENT_MAIN,
                    squads = {
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_ARC_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_ARC_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_BARON, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_BARON),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FLASHPOINT, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FLASHPOINT),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_ARC_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_ARC_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_DREG, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_DREG),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_EXPLODER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_EXPLODER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_ARC_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_ARC_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_DREG, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_DREG),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_MARAUDER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_MARAUDER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SCOURGE, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SCOURGE),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SNIPER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SNIPER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SOLAR_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SOLAR_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VANDAL, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VANDAL),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VOID_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VOID_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_WRETCH, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_WRETCH),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MARAUDER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MARAUDER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SCOURGE, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SCOURGE),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SNIPER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SNIPER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SOLAR_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SOLAR_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VANDAL, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VANDAL),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VOID_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VOID_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_WRETCH, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_WRETCH),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_MONGREL, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_MONGREL),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_SOLAR_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_SOLAR_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_VOID_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_VOID_CAPTAIN),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_VEX_PRISONER_OBJECT,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_0008_0000_80FC95E7,
            region = 64,
            -- Lost Sector in bubble 8.
            sector = {
                boss = mission.Slot.SQ_DUNGEON_MINIBOSS_1,
                squads = {
                    unit(mission.Squad.SQ_DUNGEON_MINIBOSS_1, mission.Slot.SQ_DUNGEON_MINIBOSS_1),
                    unit(mission.Squad.SQ_FINALE_INITIAL_1, mission.Slot.SQ_FINALE_INITIAL_1),
                    unit(mission.Squad.SQ_FINALE_INITIAL_2, mission.Slot.SQ_FINALE_INITIAL_2),
                    unit(mission.Squad.SQ_FINALE_INITIAL_3, mission.Slot.SQ_FINALE_INITIAL_3),
                    unit(mission.Squad.SQ_FODDER_1_80FBA086, mission.Slot.SQ_FODDER_1_80FBA086),
                    unit(mission.Squad.SQ_HALLWAY_DOGS_1, mission.Slot.SQ_HALLWAY_DOGS_1),
                    unit(mission.Squad.SQ_HALLWAY_DOGS_2, mission.Slot.SQ_HALLWAY_DOGS_2),
                    unit(mission.Squad.SQ_HALLWAY_INITIAL_1, mission.Slot.SQ_HALLWAY_INITIAL_1),
                    unit(mission.Squad.SQ_HALLWAY_INITIAL_2, mission.Slot.SQ_HALLWAY_INITIAL_2),
                    unit(mission.Squad.SQ_HALLWAY_PHALANX_1, mission.Slot.SQ_HALLWAY_PHALANX_1),
                    unit(mission.Squad.SQ_HALLWAY_PHALANX_2, mission.Slot.SQ_HALLWAY_PHALANX_2),
                    unit(mission.Squad.SQ_RUSH_DOG_1, mission.Slot.SQ_RUSH_DOG_1),
                    unit(mission.Squad.SQ_RUSH_DOG_2, mission.Slot.SQ_RUSH_DOG_2),
                    unit(mission.Squad.SQ_RUSH_SNIPER_1, mission.Slot.SQ_RUSH_SNIPER_1),
                    unit(mission.Squad.SQ_RUSH_SNIPER_2, mission.Slot.SQ_RUSH_SNIPER_2),
                    unit(mission.Squad.SQ_SLEEPING_DOG_1, mission.Slot.SQ_SLEEPING_DOG_1),
                    unit(mission.Squad.SQ_SLEEPING_DOG_2, mission.Slot.SQ_SLEEPING_DOG_2),
                    unit(mission.Squad.SQ_WATERFALL_AMBUSH_1, mission.Slot.SQ_WATERFALL_AMBUSH_1),
                    unit(mission.Squad.SQ_WATERFALL_AMBUSH_2, mission.Slot.SQ_WATERFALL_AMBUSH_2),
                    unit(mission.Squad.SQ_WATERFALL_DEFEND_1, mission.Slot.SQ_WATERFALL_DEFEND_1),
                    unit(mission.Squad.SQ_WATERFALL_DEFEND_2, mission.Slot.SQ_WATERFALL_DEFEND_2),
                    unit(mission.Squad.SQ_WATERFALL_DEFEND_3, mission.Slot.SQ_WATERFALL_DEFEND_3),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80FD5D26,
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_0009_0000_80FC95E8,
            region = 72,
            patrol = {
                unit(mission.Squad.HARVEST_CLONES_PRIME, mission.Slot.HARVEST_CLONES_PRIME),
                unit(mission.Squad.PF2_BOXES_SIDE_SIMPLE_SQUAD_0, mission.Slot.PF2_BOXES_SIDE_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_BOXES_SIDE_SIMPLE_SQUAD_1, mission.Slot.PF2_BOXES_SIDE_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_BOXES_SIMPLE_SQUAD_1, mission.Slot.PF2_BOXES_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_BOXES_SIMPLE_SQUAD_2, mission.Slot.PF2_BOXES_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_BUILDING_OUTSIDE_SIMPLE_SQUAD_0, mission.Slot.PF2_BUILDING_OUTSIDE_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_HEART_SIMPLE_SQUAD_0, mission.Slot.PF2_HEART_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_PIPE_SIMPLE_SQUAD_0, mission.Slot.PF2_PIPE_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_PIPE_SIMPLE_SQUAD_2, mission.Slot.PF2_PIPE_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_PLATFORM_SIMPLE_SQUAD_0, mission.Slot.PF2_PLATFORM_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_SIDE_HUT_SIMPLE_SQUAD_0, mission.Slot.PF2_SIDE_HUT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_SLUDGE_HUT_SIMPLE_SQUAD_0, mission.Slot.PF2_SLUDGE_HUT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_SLUDGE_HUT_SIMPLE_SQUAD_1, mission.Slot.PF2_SLUDGE_HUT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_SLUDGE_HUT_SIMPLE_SQUAD_2, mission.Slot.PF2_SLUDGE_HUT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_SLUDGE_SIMPLE_SQUAD_0, mission.Slot.PF2_SLUDGE_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_SLUDGE_SIMPLE_SQUAD_1, mission.Slot.PF2_SLUDGE_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_SLUDGE_SIMPLE_SQUAD_2, mission.Slot.PF2_SLUDGE_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_SLUDGE_SIMPLE_SQUAD_3, mission.Slot.PF2_SLUDGE_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_SLUDGE_SIMPLE_SQUAD_4, mission.Slot.PF2_SLUDGE_SIMPLE_SQUAD_4),
                unit(mission.Squad.PF2_TUNNEL_SIMPLE_CABAL_SQUAD_0, mission.Slot.PF2_TUNNEL_SIMPLE_CABAL_SQUAD_0),
                unit(mission.Squad.PF2_WIRES_HUT_SIMPLE_SQUAD_0, mission.Slot.PF2_WIRES_HUT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_WIRES_HUT_SIMPLE_SQUAD_1, mission.Slot.PF2_WIRES_HUT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_WIRES_HUT_SIMPLE_SQUAD_2, mission.Slot.PF2_WIRES_HUT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_WIRES_HUT_SIMPLE_SQUAD_3, mission.Slot.PF2_WIRES_HUT_SIMPLE_SQUAD_3),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD8059,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD8059,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD8059, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD8059),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD8059,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD8059,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD8059,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD80AD,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD80AD,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD80AD, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD80AD),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD80AD,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD80AD,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD80AD,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD8102,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD8102,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD8102, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD8102),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD8102,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD8102,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD8102,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD822B,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_OBJECTIVE_80FD822B,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80FD822B, mission.Slot.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80FD822B),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD822B, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD822B),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD822B, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD822B),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD822B, mission.Slot.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD822B),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD822B,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD822B,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD8286,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_2_OBJECTIVE_80FD8286,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_FODDER_SQUAD_80FD8286, mission.Slot.COWARDLY_MAJOR_CORE_2_FODDER_SQUAD_80FD8286),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD8286, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD8286),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD8286, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD8286),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD8286, mission.Slot.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD8286),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD8286,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD8286,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD83E3,
                    objective = mission.Slot.PF_EVENT_CRYO_POD_CORE_OBJ_BOSS_80FD83E3,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FD83E3),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FD83E3, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FD83E3),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER0_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER1_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER2_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER3_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER4_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT_80FD83E3,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_SPAWN_FX_OBJECT_80FD83E3,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_000A_0000_80FC95E9,
            region = 80,
            -- Lost Sector in bubble 10.
            sector = {
                boss = mission.Slot.SQ_MIDBOSS,
                squads = {
                    unit(mission.Squad.SQ_ACOLYTE_0, mission.Slot.SQ_ACOLYTE_0),
                    unit(mission.Squad.SQ_ACOLYTE_1_80FD85BF, mission.Slot.SQ_ACOLYTE_1_80FD85BF),
                    unit(mission.Squad.SQ_ACOLYTE_2_80FD85BF, mission.Slot.SQ_ACOLYTE_2_80FD85BF),
                    unit(mission.Squad.SQ_ACOLYTE_HIGH, mission.Slot.SQ_ACOLYTE_HIGH),
                    unit(mission.Squad.SQ_ACOLYTE_LOW_1, mission.Slot.SQ_ACOLYTE_LOW_1),
                    unit(mission.Squad.SQ_ACOLYTE_LOW_2, mission.Slot.SQ_ACOLYTE_LOW_2),
                    unit(mission.Squad.SQ_ACOLYTE_LOW_3, mission.Slot.SQ_ACOLYTE_LOW_3),
                    unit(mission.Squad.SQ_ENTRANCE_THRALLS, mission.Slot.SQ_ENTRANCE_THRALLS),
                    unit(mission.Squad.SQ_EXPLODER_0, mission.Slot.SQ_EXPLODER_0),
                    unit(mission.Squad.SQ_EXPLODER_1_80FD85BF, mission.Slot.SQ_EXPLODER_1_80FD85BF),
                    unit(mission.Squad.SQ_MIDBOSS, mission.Slot.SQ_MIDBOSS),
                    unit(mission.Squad.SQ_MIDDLE_PLATFORM, mission.Slot.SQ_MIDDLE_PLATFORM),
                    unit(mission.Squad.SQ_OGRE_80FD85BF, mission.Slot.SQ_OGRE_80FD85BF),
                    unit(mission.Squad.SQ_THRALL_0, mission.Slot.SQ_THRALL_0),
                    unit(mission.Squad.SQ_THRALL_1, mission.Slot.SQ_THRALL_1),
                    unit(mission.Squad.SQ_THRALL_2, mission.Slot.SQ_THRALL_2),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80FD85CC,
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_000C_0000_80FC95EB,
            region = 96,
            patrol = {
                unit(mission.Squad.SHOWDOWN_DECOYS, mission.Slot.SHOWDOWN_DECOYS),
                unit(mission.Squad.SHOWDOWN_DECOYS_1, mission.Slot.SHOWDOWN_DECOYS_1),
                unit(mission.Squad.SHOWDOWN_DECOYS_2, mission.Slot.SHOWDOWN_DECOYS_2),
                unit(mission.Squad.SHOWDOWN_DECOYS_3, mission.Slot.SHOWDOWN_DECOYS_3),
                unit(mission.Squad.SHOWDOWN_DECOYS_4, mission.Slot.SHOWDOWN_DECOYS_4),
                unit(mission.Squad.SHOWDOWN_DECOYS_5, mission.Slot.SHOWDOWN_DECOYS_5),
                unit(mission.Squad.SHOWDOWN_DECOYS_6, mission.Slot.SHOWDOWN_DECOYS_6),
                unit(mission.Squad.SHOWDOWN_DECOYS_7, mission.Slot.SHOWDOWN_DECOYS_7),
                unit(mission.Squad.SQ_ACOLYTE_1_80FD8877, mission.Slot.SQ_ACOLYTE_1_80FD8877),
                unit(mission.Squad.SQ_ACOLYTE_2_80FD8877, mission.Slot.SQ_ACOLYTE_2_80FD8877),
                unit(mission.Squad.SQ_ACOLYTE_3, mission.Slot.SQ_ACOLYTE_3),
                unit(mission.Squad.SQ_ANCHOR_80FD8635, mission.Slot.SQ_ANCHOR_80FD8635),
                unit(mission.Squad.SQ_ANCHOR_80FD868D, mission.Slot.SQ_ANCHOR_80FD868D),
                unit(mission.Squad.SQ_CAPTAIN_80FD8801, mission.Slot.SQ_CAPTAIN_80FD8801),
                unit(mission.Squad.SQ_CAPTAIN_80FD8877, mission.Slot.SQ_CAPTAIN_80FD8877),
                unit(mission.Squad.SQ_FODDER_1_80FD8801, mission.Slot.SQ_FODDER_1_80FD8801),
                unit(mission.Squad.SQ_FODDER_1_80FD88DC, mission.Slot.SQ_FODDER_1_80FD88DC),
                unit(mission.Squad.SQ_FODDER_2_80FD8801, mission.Slot.SQ_FODDER_2_80FD8801),
                unit(mission.Squad.SQ_FODDER_2_80FD88DC, mission.Slot.SQ_FODDER_2_80FD88DC),
                unit(mission.Squad.SQ_FODDER_3_80FD8801, mission.Slot.SQ_FODDER_3_80FD8801),
                unit(mission.Squad.SQ_FODDER_3_80FD88DC, mission.Slot.SQ_FODDER_3_80FD88DC),
                unit(mission.Squad.SQ_FODDER_4, mission.Slot.SQ_FODDER_4),
                unit(mission.Squad.SQ_FORSAKEN_FODDER_1, mission.Slot.SQ_FORSAKEN_FODDER_1),
                unit(mission.Squad.SQ_FORSAKEN_FODDER_2, mission.Slot.SQ_FORSAKEN_FODDER_2),
            },
        },
        {
            state = mission.states.STATE_80FC9645_000D_0000_80FC95F1,
            region = 104,
            patrol = {
                unit(mission.Squad.PF2_AMBIENT_PLAINS_CAMP_BOTTOM_SQUAD_0, mission.Slot.PF2_AMBIENT_PLAINS_CAMP_BOTTOM_SQUAD_0),
                unit(mission.Squad.PF2_AMBIENT_PLAINS_CAMP_BOTTOM_SQUAD_1, mission.Slot.PF2_AMBIENT_PLAINS_CAMP_BOTTOM_SQUAD_1),
                unit(mission.Squad.PF2_AMBIENT_PLAINS_CAMP_CAVE_SQUAD_0, mission.Slot.PF2_AMBIENT_PLAINS_CAMP_CAVE_SQUAD_0),
                unit(mission.Squad.PF2_AMBIENT_PLAINS_CAMP_TOP_SQUAD_0, mission.Slot.PF2_AMBIENT_PLAINS_CAMP_TOP_SQUAD_0),
                unit(mission.Squad.PF2_AMBIENT_PLAINS_CAMP_TOP_SQUAD_2, mission.Slot.PF2_AMBIENT_PLAINS_CAMP_TOP_SQUAD_2),
                unit(mission.Squad.PF2_AMBIENT_PLAINS_EDGE_CAVE_SQUAD_0, mission.Slot.PF2_AMBIENT_PLAINS_EDGE_CAVE_SQUAD_0),
                unit(mission.Squad.PF2_AMBIENT_PLAINS_PRAIRIE_CAVE_SQUAD_0, mission.Slot.PF2_AMBIENT_PLAINS_PRAIRIE_CAVE_SQUAD_0),
                unit(mission.Squad.SQ_AMBIENT_CABAL_1, mission.Slot.SQ_AMBIENT_CABAL_1),
                unit(mission.Squad.SQ_AMBIENT_CABAL_2, mission.Slot.SQ_AMBIENT_CABAL_2),
                unit(mission.Squad.SQ_AMBIENT_CABAL_3, mission.Slot.SQ_AMBIENT_CABAL_3),
                unit(mission.Squad.SQ_AMBIENT_FORSAKEN_1, mission.Slot.SQ_AMBIENT_FORSAKEN_1),
                unit(mission.Squad.SQ_AMBIENT_FORSAKEN_2, mission.Slot.SQ_AMBIENT_FORSAKEN_2),
                unit(mission.Squad.SQ_AMBIENT_FORSAKEN_3, mission.Slot.SQ_AMBIENT_FORSAKEN_3),
                unit(mission.Squad.SQ_CAMP_CABAL_1, mission.Slot.SQ_CAMP_CABAL_1),
                unit(mission.Squad.SQ_CAMP_CABAL_2, mission.Slot.SQ_CAMP_CABAL_2),
                unit(mission.Squad.SQ_CAMP_CABAL_3, mission.Slot.SQ_CAMP_CABAL_3),
                unit(mission.Squad.SQ_CAMP_FORSAKEN_1, mission.Slot.SQ_CAMP_FORSAKEN_1),
                unit(mission.Squad.SQ_CAMP_FORSAKEN_2, mission.Slot.SQ_CAMP_FORSAKEN_2),
                unit(mission.Squad.SQ_CAMP_FORSAKEN_3, mission.Slot.SQ_CAMP_FORSAKEN_3),
                unit(mission.Squad.SQ_CAPTAIN_1, mission.Slot.SQ_CAPTAIN_1),
                unit(mission.Squad.SQ_CAPTAIN_2, mission.Slot.SQ_CAPTAIN_2),
                unit(mission.Squad.SQ_CAPTAIN_3, mission.Slot.SQ_CAPTAIN_3),
                unit(mission.Squad.SQ_FACTION_FIGHT_CABAL_1, mission.Slot.SQ_FACTION_FIGHT_CABAL_1),
                unit(mission.Squad.SQ_FACTION_FIGHT_CABAL_2, mission.Slot.SQ_FACTION_FIGHT_CABAL_2),
            },
        },
        {
            state = mission.states.STATE_80FC9645_000E_0000_80FC95F2,
            region = 112,
            patrol = {
                unit(mission.Squad.MISSION_RITUAL_PORT_MARAUDER_CENTER_SQUAD, mission.Slot.MISSION_RITUAL_PORT_MARAUDER_CENTER_SQUAD),
                unit(mission.Squad.PF2_ALLEY_FRONT_SIMPLE_SQUAD_0, mission.Slot.PF2_ALLEY_FRONT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_ALLEY_FRONT_SIMPLE_SQUAD_1, mission.Slot.PF2_ALLEY_FRONT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_ALLEY_SIMPLE_SQUAD_0, mission.Slot.PF2_ALLEY_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_ALLEY_SIMPLE_SQUAD_1, mission.Slot.PF2_ALLEY_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_ALLEY_SIMPLE_SQUAD_2, mission.Slot.PF2_ALLEY_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_ALLEY_UPPER_SIMPLE_SQUAD_0, mission.Slot.PF2_ALLEY_UPPER_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_BASEMENT_SIMPLE_SQUAD_0, mission.Slot.PF2_BASEMENT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_BASEMENT_SIMPLE_SQUAD_1, mission.Slot.PF2_BASEMENT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_BASEMENT_SIMPLE_SQUAD_2, mission.Slot.PF2_BASEMENT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_BAZAAR_DOCK_SIMPLE_SQUAD_0, mission.Slot.PF2_BAZAAR_DOCK_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_BAZAAR_DOCK_SIMPLE_SQUAD_1, mission.Slot.PF2_BAZAAR_DOCK_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_BAZAAR_INSIDE_SIMPLE_SQUAD_0, mission.Slot.PF2_BAZAAR_INSIDE_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_BAZAAR_INSIDE_SIMPLE_SQUAD_1, mission.Slot.PF2_BAZAAR_INSIDE_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_BAZAAR_INSIDE_SIMPLE_SQUAD_2, mission.Slot.PF2_BAZAAR_INSIDE_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_BAZAAR_RAISED_SIMPLE_SQUAD_1, mission.Slot.PF2_BAZAAR_RAISED_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_BAZAAR_RAISED_SIMPLE_SQUAD_2, mission.Slot.PF2_BAZAAR_RAISED_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_BAZAAR_SIMPLE_SQUAD_0, mission.Slot.PF2_BAZAAR_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_BAZAAR_SIMPLE_SQUAD_1, mission.Slot.PF2_BAZAAR_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_BAZAAR_SIMPLE_SQUAD_2, mission.Slot.PF2_BAZAAR_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_BAZAAR_SIMPLE_SQUAD_3, mission.Slot.PF2_BAZAAR_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_BAZAAR_SIMPLE_SQUAD_4, mission.Slot.PF2_BAZAAR_SIMPLE_SQUAD_4),
                unit(mission.Squad.PF2_CENTER_SIMPLE_SQUAD_0_80FD8CB7, mission.Slot.PF2_CENTER_SIMPLE_SQUAD_0_80FD8CB7),
                unit(mission.Squad.PF2_CENTER_SIMPLE_SQUAD_1_80FD8CB7, mission.Slot.PF2_CENTER_SIMPLE_SQUAD_1_80FD8CB7),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD90C0,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD90C0,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD90C0, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD90C0),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD90C0,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD90C0,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD90C0,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9115,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD9115,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9115, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9115),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD9115,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD9115,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD9115,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD916A,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD916A,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD916A, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD916A),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD916A,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD916A,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD916A,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD91BF,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD91BF,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD91BF, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD91BF),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD91BF,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD91BF,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD91BF,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9214,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD9214,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9214, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9214),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD9214,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD9214,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD9214,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9269,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD9269,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9269, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9269),
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_RESISTANCE_SQUAD_80FD9269, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_RESISTANCE_SQUAD_80FD9269),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD9269,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD9269,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD9269,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9392,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_OBJECTIVE_80FD9392,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80FD9392, mission.Slot.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80FD9392),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD9392, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD9392),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD9392, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD9392),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD9392, mission.Slot.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD9392),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD9392,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD9392,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD93ED,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_OBJECTIVE_80FD93ED,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD93ED, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD93ED),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD93ED, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD93ED),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD93ED, mission.Slot.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD93ED),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD93ED,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD93ED,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9448,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_OBJECTIVE_80FD9448,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80FD9448, mission.Slot.COWARDLY_MAJOR_CORE_FODDER_SQUAD_80FD9448),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD9448, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_80FD9448),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD9448, mission.Slot.COWARDLY_MAJOR_CORE_MAJOR_SQUAD_80FD9448),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD9448, mission.Slot.COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_80FD9448),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD9448,
                        mission.Slot.COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD9448,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD959F,
                    objective = mission.Slot.PF_EVENT_CRYO_POD_CORE_OBJ_BOSS_80FD959F,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_1_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_1_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FD959F),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FD959F, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FD959F),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER0_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER1_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER2_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER3_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER4_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT_80FD959F,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_SPAWN_FX_OBJECT_80FD959F,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_000F_0000_80FC95F3,
            region = 120,
            -- Lost Sector in bubble 15.
            sector = {
                boss = mission.Slot.SQ_BOSS_80FD9694,
                squads = {
                    unit(mission.Squad.SQ_BOSS_80FD9694, mission.Slot.SQ_BOSS_80FD9694),
                    unit(mission.Squad.SQ_FRONT_RANGED_1, mission.Slot.SQ_FRONT_RANGED_1),
                    unit(mission.Squad.SQ_FRONT_RANGED_2, mission.Slot.SQ_FRONT_RANGED_2),
                    unit(mission.Squad.SQ_FRONT_RANGED_3, mission.Slot.SQ_FRONT_RANGED_3),
                    unit(mission.Squad.SQ_MAURADER, mission.Slot.SQ_MAURADER),
                    unit(mission.Squad.SQ_MELEE_80FD9694, mission.Slot.SQ_MELEE_80FD9694),
                    unit(mission.Squad.SQ_REINFORCEMENT_1, mission.Slot.SQ_REINFORCEMENT_1),
                    unit(mission.Squad.SQ_REINFORCEMENT_2, mission.Slot.SQ_REINFORCEMENT_2),
                    unit(mission.Squad.SQ_REINFORCEMENT_3, mission.Slot.SQ_REINFORCEMENT_3),
                    unit(mission.Squad.SQ_REINFORCEMENT_4, mission.Slot.SQ_REINFORCEMENT_4),
                    unit(mission.Squad.SQ_SNIPER_1_80FD9694, mission.Slot.SQ_SNIPER_1_80FD9694),
                    unit(mission.Squad.SQ_SNIPER_2, mission.Slot.SQ_SNIPER_2),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80FD96A1,
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_0010_0000_80FD9F60,
            region = 128,
            -- Lost Sector in bubble 16.
            sector = {
                boss = mission.Slot.SQ_FALLEN_BOSS_1,
                squads = {
                    unit(mission.Squad.SQ_CABAL_RUSHER_1, mission.Slot.SQ_CABAL_RUSHER_1),
                    unit(mission.Squad.SQ_CABAL_RUSHER_2, mission.Slot.SQ_CABAL_RUSHER_2),
                    unit(mission.Squad.SQ_CABAL_RUSHER_3, mission.Slot.SQ_CABAL_RUSHER_3),
                    unit(mission.Squad.SQ_CABAL_RUSHER_4, mission.Slot.SQ_CABAL_RUSHER_4),
                    unit(mission.Squad.SQ_CABAL_RUSHER_5, mission.Slot.SQ_CABAL_RUSHER_5),
                    unit(mission.Squad.SQ_CABAL_RUSHER_6, mission.Slot.SQ_CABAL_RUSHER_6),
                    unit(mission.Squad.SQ_FALLEN_ANCHOR_1, mission.Slot.SQ_FALLEN_ANCHOR_1),
                    unit(mission.Squad.SQ_FALLEN_BARTENDER_1, mission.Slot.SQ_FALLEN_BARTENDER_1),
                    unit(mission.Squad.SQ_FALLEN_BOSS_1, mission.Slot.SQ_FALLEN_BOSS_1),
                    unit(mission.Squad.SQ_FALLEN_BOUNCER_1, mission.Slot.SQ_FALLEN_BOUNCER_1),
                    unit(mission.Squad.SQ_FALLEN_CUPHOLDER_1, mission.Slot.SQ_FALLEN_CUPHOLDER_1),
                    unit(mission.Squad.SQ_FALLEN_CUPHOLDER_2, mission.Slot.SQ_FALLEN_CUPHOLDER_2),
                    unit(mission.Squad.SQ_FALLEN_DJ_1, mission.Slot.SQ_FALLEN_DJ_1),
                    unit(mission.Squad.SQ_FALLEN_EXPLOSIVE_1, mission.Slot.SQ_FALLEN_EXPLOSIVE_1),
                    unit(mission.Squad.SQ_FALLEN_FISTICUFFS_1, mission.Slot.SQ_FALLEN_FISTICUFFS_1),
                    unit(mission.Squad.SQ_FALLEN_FISTICUFFS_2, mission.Slot.SQ_FALLEN_FISTICUFFS_2),
                    unit(mission.Squad.SQ_FALLEN_FODDER_1, mission.Slot.SQ_FALLEN_FODDER_1),
                    unit(mission.Squad.SQ_FALLEN_FODDER_2, mission.Slot.SQ_FALLEN_FODDER_2),
                    unit(mission.Squad.SQ_FALLEN_FODDER_3, mission.Slot.SQ_FALLEN_FODDER_3),
                    unit(mission.Squad.SQ_FALLEN_FODDER_4, mission.Slot.SQ_FALLEN_FODDER_4),
                    unit(mission.Squad.SQ_FALLEN_FODDER_5, mission.Slot.SQ_FALLEN_FODDER_5),
                    unit(mission.Squad.SQ_FALLEN_MELEE_1, mission.Slot.SQ_FALLEN_MELEE_1),
                    unit(mission.Squad.SQ_FALLEN_MELEE_2, mission.Slot.SQ_FALLEN_MELEE_2),
                    unit(mission.Squad.SQ_FALLEN_MELEE_3, mission.Slot.SQ_FALLEN_MELEE_3),
                },
                chest = {
                    mission.Slot.TREASURE_CHEST_DUNGEON,
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_0012_0000_80FC95F6,
            region = 144,
            patrol = {
                unit(mission.Squad.PF2_CAVE_AMBUSH_SIMPLE_SQUAD_0, mission.Slot.PF2_CAVE_AMBUSH_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_CAVE_AMBUSH_SIMPLE_SQUAD_2, mission.Slot.PF2_CAVE_AMBUSH_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_CLEARING_SIMPLE_SQUAD_0, mission.Slot.PF2_CLEARING_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_CLEARING_SIMPLE_SQUAD_2, mission.Slot.PF2_CLEARING_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_0, mission.Slot.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_1, mission.Slot.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_2, mission.Slot.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_3, mission.Slot.PF2_FIGHT_CRACK_LEFT_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_FIGHT_CRACK_RIGHT_SIMPLE_MEDIUM_SQUAD_0, mission.Slot.PF2_FIGHT_CRACK_RIGHT_SIMPLE_MEDIUM_SQUAD_0),
                unit(mission.Squad.PF2_FIGHT_CRACK_RIGHT_SIMPLE_MEDIUM_SQUAD_1, mission.Slot.PF2_FIGHT_CRACK_RIGHT_SIMPLE_MEDIUM_SQUAD_1),
                unit(mission.Squad.PF2_FIGHT_CRACK_RIGHT_SIMPLE_MEDIUM_SQUAD_2, mission.Slot.PF2_FIGHT_CRACK_RIGHT_SIMPLE_MEDIUM_SQUAD_2),
                unit(mission.Squad.PF2_HARVEST_PATH_SIMPLE_SQUAD_0, mission.Slot.PF2_HARVEST_PATH_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_HARVEST_PATH_SIMPLE_SQUAD_1, mission.Slot.PF2_HARVEST_PATH_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_HARVEST_PATH_SIMPLE_SQUAD_2, mission.Slot.PF2_HARVEST_PATH_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_HIVE_SHIP_SIMPLE_SQUAD_0, mission.Slot.PF2_HIVE_SHIP_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_HIVE_SHIP_SIMPLE_SQUAD_1, mission.Slot.PF2_HIVE_SHIP_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_HIVE_SHIP_SIMPLE_SQUAD_3, mission.Slot.PF2_HIVE_SHIP_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_LOWER_SIMPLE_SQUAD_0, mission.Slot.PF2_LOWER_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_LOWER_SIMPLE_SQUAD_1, mission.Slot.PF2_LOWER_SIMPLE_SQUAD_1),
                unit(mission.Squad.PF2_LOWER_SIMPLE_SQUAD_2, mission.Slot.PF2_LOWER_SIMPLE_SQUAD_2),
                unit(mission.Squad.PF2_LOWER_SIMPLE_SQUAD_3, mission.Slot.PF2_LOWER_SIMPLE_SQUAD_3),
                unit(mission.Squad.PF2_SHIP_OUTSIDE_GUARD_SQUAD_0, mission.Slot.PF2_SHIP_OUTSIDE_GUARD_SQUAD_0),
                unit(mission.Squad.PF2_SIDE_SPOT_RANGED_SIMPLE_SQUAD_0, mission.Slot.PF2_SIDE_SPOT_RANGED_SIMPLE_SQUAD_0),
                unit(mission.Squad.PF2_SIDE_SPOT_RANGED_SIMPLE_SQUAD_1, mission.Slot.PF2_SIDE_SPOT_RANGED_SIMPLE_SQUAD_1),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9C9D,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD9C9D,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9C9D, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9C9D),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD9C9D,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD9C9D,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD9C9D,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9CF2,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD9CF2,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9CF2, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9CF2),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD9CF2,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD9CF2,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD9CF2,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9D47,
                    objective = mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_OBJECTIVE_80FD9D47,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9D47, mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_BOSS_SQUAD_80FD9D47),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_1_80FD9D47,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_COVER_OBJECT_2_80FD9D47,
                        mission.Slot.PF_EVENT_CHEST_SKIRMISH_1_LOCKED_CHEST_OBJECT_80FD9D47,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9E73,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_2_OBJECTIVE_80FD9E73,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD9E73, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD9E73),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD9E73, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD9E73),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD9E73, mission.Slot.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD9E73),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD9E73,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD9E73,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9ECE,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_2_OBJECTIVE_80FD9ECE,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD9ECE, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD9ECE),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD9ECE, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD9ECE),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD9ECE, mission.Slot.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD9ECE),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD9ECE,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD9ECE,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FD9F29,
                    objective = mission.Slot.COWARDLY_MAJOR_CORE_2_OBJECTIVE_80FD9F29,
                    squads = {
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_FODDER_SQUAD_80FD9F29, mission.Slot.COWARDLY_MAJOR_CORE_2_FODDER_SQUAD_80FD9F29),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD9F29, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_FODDER_SQUAD_80FD9F29),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD9F29, mission.Slot.COWARDLY_MAJOR_CORE_2_MAJOR_SQUAD_80FD9F29),
                        unit(mission.Squad.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD9F29, mission.Slot.COWARDLY_MAJOR_CORE_2_NO_LOOT_FODDER_SQUAD_80FD9F29),
                    },
                    chest = {
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80FD9F29,
                        mission.Slot.COWARDLY_MAJOR_CORE_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80FD9F29,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80FDC083,
                    objective = mission.Slot.PF_EVENT_CRYO_POD_CORE_OBJ_BOSS_80FDC083,
                    squads = {
                        unit(mission.Squad.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_CORE_SQ_BOSS_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_1_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_1_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_2, mission.Slot.PF_EVENT_CRYO_POD_SQ_FLASHPOINT_2),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_ALTERNATE_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_FODDER_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_MINIBOSS_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_SUPPORT_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_HEROIC_WAVE_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_INTRO_WAVE_1_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_1_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_DIFFICULTY_2_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_FODDER_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_SUPPORT_0_80FDC083),
                        unit(mission.Squad.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FDC083, mission.Slot.PF_EVENT_CRYO_POD_SQ_STANDARD_WAVE_0_80FDC083),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER0_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER1_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER2_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER3_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_TIER4_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT_80FDC083,
                        mission.Slot.PF_EVENT_CRYO_POD_CORE_PF_REWARD_CHEST_SPAWN_FX_OBJECT_80FDC083,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_0013_0000_80FC95F7,
            region = 152,
            -- Lost Sector in bubble 19.
            sector = {
                boss = mission.Slot.BOSS_SQUAD,
                squads = {
                    unit(mission.Squad.BOSS_SQUAD, mission.Slot.BOSS_SQUAD),
                    unit(mission.Squad.EXPLODERS_SQUAD, mission.Slot.EXPLODERS_SQUAD),
                    unit(mission.Squad.MELEE_SQUAD_80FDC3A6, mission.Slot.MELEE_SQUAD_80FDC3A6),
                    unit(mission.Squad.RANGED_BACK_SQUAD, mission.Slot.RANGED_BACK_SQUAD),
                    unit(mission.Squad.RANGED_BACK_SQUAD_1, mission.Slot.RANGED_BACK_SQUAD_1),
                    unit(mission.Squad.RANGED_BACK_SQUAD_2, mission.Slot.RANGED_BACK_SQUAD_2),
                    unit(mission.Squad.RANGED_FRONT_SQUAD, mission.Slot.RANGED_FRONT_SQUAD),
                    unit(mission.Squad.RANGED_FRONT_SQUAD_1, mission.Slot.RANGED_FRONT_SQUAD_1),
                    unit(mission.Squad.RANGED_FRONT_SQUAD_2, mission.Slot.RANGED_FRONT_SQUAD_2),
                    unit(mission.Squad.RANGED_FRONT_SQUAD_3, mission.Slot.RANGED_FRONT_SQUAD_3),
                    unit(mission.Squad.RANGED_SQUAD_1, mission.Slot.RANGED_SQUAD_1),
                    unit(mission.Squad.RANGED_SQUAD_2, mission.Slot.RANGED_SQUAD_2),
                    unit(mission.Squad.RANGED_SQUAD_3, mission.Slot.RANGED_SQUAD_3),
                    unit(mission.Squad.RANGED_SQUAD_4, mission.Slot.RANGED_SQUAD_4),
                    unit(mission.Squad.SNIPER_1_SQUAD, mission.Slot.SNIPER_1_SQUAD),
                    unit(mission.Squad.SNIPER_2_SQUAD, mission.Slot.SNIPER_2_SQUAD),
                    unit(mission.Squad.SNIPER_SQUAD, mission.Slot.SNIPER_SQUAD),
                    unit(mission.Squad.SNIPER_SQUAD_1_80FDC3A6, mission.Slot.SNIPER_SQUAD_1_80FDC3A6),
                    unit(mission.Squad.SNIPER_SQUAD_2_80FDC3A6, mission.Slot.SNIPER_SQUAD_2_80FDC3A6),
                    unit(mission.Squad.SQ_SKIFF_1, mission.Slot.SQ_SKIFF_1),
                    unit(mission.Squad.SQ_SKIFF_2, mission.Slot.SQ_SKIFF_2),
                },
                chest = {
                    mission.Slot.O_DUNGEON_CHEST,
                },
            },
        },
        {
            state = mission.states.STATE_80FC9645_0014_0000_80FC95F8,
            region = 160,
            patrol = {
                unit(mission.Squad.CAPTIVE_1_SQ_CAPTIVE, mission.Slot.CAPTIVE_1_SQ_CAPTIVE),
                unit(mission.Squad.CAPTIVE_1_SQ_JAILER, mission.Slot.CAPTIVE_1_SQ_JAILER),
                unit(mission.Squad.CAPTIVE_1_SQ_JAILER_BKUP, mission.Slot.CAPTIVE_1_SQ_JAILER_BKUP),
                unit(mission.Squad.CAPTIVE_2_SQ_CAPTIVE, mission.Slot.CAPTIVE_2_SQ_CAPTIVE),
                unit(mission.Squad.CAPTIVE_2_SQ_JAILER, mission.Slot.CAPTIVE_2_SQ_JAILER),
                unit(mission.Squad.CAPTIVE_2_SQ_JAILER_BKUP, mission.Slot.CAPTIVE_2_SQ_JAILER_BKUP),
                unit(mission.Squad.PF2_ENTRY_CORNER_SQUAD_0, mission.Slot.PF2_ENTRY_CORNER_SQUAD_0),
                unit(mission.Squad.PF2_ENTRY_CORNER_SQUAD_1, mission.Slot.PF2_ENTRY_CORNER_SQUAD_1),
                unit(mission.Squad.PF2_ENTRY_CORNER_SQUAD_2, mission.Slot.PF2_ENTRY_CORNER_SQUAD_2),
                unit(mission.Squad.PF2_ENTRY_CORNER_SQUAD_3, mission.Slot.PF2_ENTRY_CORNER_SQUAD_3),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_0, mission.Slot.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_0),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_1, mission.Slot.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_1),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_2, mission.Slot.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_2),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_3, mission.Slot.PF2_ENTRY_FACTION_FIGHT_1_SQUAD_3),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_0, mission.Slot.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_0),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_1, mission.Slot.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_1),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_2, mission.Slot.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_2),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_3, mission.Slot.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_3),
                unit(mission.Squad.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_4, mission.Slot.PF2_ENTRY_FACTION_FIGHT_2_SQUAD_4),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FD4138, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FD4138),
                unit(mission.Squad.PF2_STREETS_END_SQUAD_0, mission.Slot.PF2_STREETS_END_SQUAD_0),
                unit(mission.Squad.SQ_ALLEY_1, mission.Slot.SQ_ALLEY_1),
                unit(mission.Squad.SQ_ALLEY_2, mission.Slot.SQ_ALLEY_2),
                unit(mission.Squad.SQ_ALLEY_MELEE_1, mission.Slot.SQ_ALLEY_MELEE_1),
            },
        },
        {
            state = mission.states.STATE_80FC9645_0015_0000_80FC95F9,
            region = 168,
            patrol = {
                unit(mission.Squad.SQ_VENDOR_PETRA, mission.Slot.SQ_VENDOR_PETRA),
                unit(mission.Squad.SQ_VENDOR_SPIDER, mission.Slot.SQ_VENDOR_SPIDER),
            },
        },
        {
            state = mission.states.STATE_80FC9645_0016_0000_80FD9F61,
            region = 176,
            patrol = {
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FD4231, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80FD4231),
                unit(mission.Squad.SQ_DREG_DOUBLE, mission.Slot.SQ_DREG_DOUBLE),
                unit(mission.Squad.SQ_DREG_DOUBLE_1, mission.Slot.SQ_DREG_DOUBLE_1),
                unit(mission.Squad.SQ_DREG_DOUBLE_2, mission.Slot.SQ_DREG_DOUBLE_2),
                unit(mission.Squad.SQ_DREG_DOUBLE_3, mission.Slot.SQ_DREG_DOUBLE_3),
                unit(mission.Squad.SQ_DREG_DOUBLE_4, mission.Slot.SQ_DREG_DOUBLE_4),
                unit(mission.Squad.SQ_DREG_DOUBLE_5, mission.Slot.SQ_DREG_DOUBLE_5),
                unit(mission.Squad.SQ_DREG_PIKE, mission.Slot.SQ_DREG_PIKE),
                unit(mission.Squad.SQ_DREG_PIKE_1, mission.Slot.SQ_DREG_PIKE_1),
                unit(mission.Squad.SQ_ENTRY_A_DREGS, mission.Slot.SQ_ENTRY_A_DREGS),
                unit(mission.Squad.SQ_ENTRY_A_VANDALS, mission.Slot.SQ_ENTRY_A_VANDALS),
                unit(mission.Squad.SQ_ENTRY_A_VANDALS_1, mission.Slot.SQ_ENTRY_A_VANDALS_1),
                unit(mission.Squad.SQ_ENTRY_B_MARAUDERS, mission.Slot.SQ_ENTRY_B_MARAUDERS),
                unit(mission.Squad.SQ_ENTRY_B_MARAUDERS_1, mission.Slot.SQ_ENTRY_B_MARAUDERS_1),
                unit(mission.Squad.SQ_ENTRY_B_SNIPER, mission.Slot.SQ_ENTRY_B_SNIPER),
                unit(mission.Squad.SQ_ENTRY_B_SNIPER_1, mission.Slot.SQ_ENTRY_B_SNIPER_1),
                unit(mission.Squad.SQ_MAJOR_VANDAL, mission.Slot.SQ_MAJOR_VANDAL),
                unit(mission.Squad.SQ_MARAUDER_DOUBLE_1_80FDC963, mission.Slot.SQ_MARAUDER_DOUBLE_1_80FDC963),
                unit(mission.Squad.SQ_MARAUDER_DOUBLE_2_80FDC963, mission.Slot.SQ_MARAUDER_DOUBLE_2_80FDC963),
                unit(mission.Squad.SQ_MARAUDER_DOUBLE_80FDC963, mission.Slot.SQ_MARAUDER_DOUBLE_80FDC963),
                unit(mission.Squad.SQ_MARAUDER_SINGLE, mission.Slot.SQ_MARAUDER_SINGLE),
                unit(mission.Squad.SQ_MARAUDER_SINGLE_1, mission.Slot.SQ_MARAUDER_SINGLE_1),
                unit(mission.Squad.SQ_VANDAL_DOUBLE, mission.Slot.SQ_VANDAL_DOUBLE),
                unit(mission.Squad.SQ_VANDAL_DOUBLE_1, mission.Slot.SQ_VANDAL_DOUBLE_1),
            },
        },
    }
end
