-- Generated from installed mission data. Do not edit.
-- Zones are authored state rows; population and event sites come from the slice sets.
return function(mission, freeroam)
    local unit = freeroam.unit
    return {
        {
            state = mission.states.STATE_81503E69_0000_0000_81503E4C,
            region = 0,
            patrol = {
                unit(mission.Squad.NIGHTMARE_0, mission.Slot.NIGHTMARE_0),
                unit(mission.Squad.NIGHTMARE_1, mission.Slot.NIGHTMARE_1),
                unit(mission.Squad.NIGHTMARE_2, mission.Slot.NIGHTMARE_2),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81566CCB,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_81566CCB,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_81566CCB, mission.Slot.PUZZLE_CHEST_SQ_GUARD_81566CCB),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_81566CCB,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_81566CCB,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_81566CCB,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_81566CCB,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_81566CCB,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_81566CCB,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_81566CCB,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81566D23,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_81566D23,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_81566D23, mission.Slot.PUZZLE_CHEST_SQ_GUARD_81566D23),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_81566D23,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_81566D23,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_81566D23,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_81566D23,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_81566D23,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_81566D23,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_81566D23,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81566D7B,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_81566D7B,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_81566D7B, mission.Slot.PUZZLE_CHEST_SQ_GUARD_81566D7B),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_81566D7B,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_81566D7B,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_81566D7B,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_81566D7B,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_81566D7B,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_81566D7B,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_81566D7B,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815672A7,
                    objective = mission.Slot.PF_EVENT_FALLEN_SERVITOR_OBJ_FODDER,
                    squads = {
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_0_SQ_DROPSHIP, mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_0_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_1_SQ_DROPSHIP, mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_1_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_2_SQ_DROPSHIP, mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_2_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_3_SQ_DROPSHIP, mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_3_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_4_SQ_DROPSHIP, mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFFS_4_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFF_SKELETON_CREW_SQ_DROPSHIP, mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_FALLEN_SKIFF_SKELETON_CREW_SQ_DROPSHIP),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SERVITOR_1, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SERVITOR_1),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SERVITOR_2, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SERVITOR_2),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SERVITOR_3, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SERVITOR_3),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SHIELD, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_CELLKEEPER_SHIELD),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_MELEE_FODDER_TIER_1, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_MELEE_FODDER_TIER_1),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_MELEE_FODDER_TIER_2, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_MELEE_FODDER_TIER_2),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SCORCH_CAPTAIN, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SCORCH_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SKELETON_CREW_VANDAL_1, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SKELETON_CREW_VANDAL_1),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SKELETON_CREW_VANDAL_2, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SKELETON_CREW_VANDAL_2),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SKELETON_CREW_VANDAL_3, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SKELETON_CREW_VANDAL_3),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_BASE_1, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_BASE_1),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_BASE_2, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_BASE_2),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_BASE_3, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_BASE_3),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_1_TIER_1, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_1_TIER_1),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_1_TIER_2, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_1_TIER_2),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_2_TIER_1, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_2_TIER_1),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_2_TIER_2, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_2_TIER_2),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_3_TIER_1, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_3_TIER_1),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_3_TIER_2, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_SUPPORT_MAJOR_3_TIER_2),
                        unit(mission.Squad.PF_EVENT_FALLEN_SERVITOR_SQ_ULTRA_SERVITOR, mission.Slot.PF_EVENT_FALLEN_SERVITOR_SQ_ULTRA_SERVITOR),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_FALLEN_SERVITOR_PF_REWARD_CHEST_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815673C8,
                    objective = mission.Slot.PF_LUNA_WARSAT_PE_OBJ_EVENT_ENEMY_ENTER_815673C8,
                    squads = {
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_1_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_1_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_2_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_2_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_3_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_3_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_0_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_0_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_1_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_1_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_2_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_2_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_2_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_2_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_0_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_0_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_1_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_1_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_2_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_2_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_ULTRA_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_ULTRA_815673C8),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_ULTRA_SUPPORT_815673C8, mission.Slot.PF_LUNA_WARSAT_PE_SQ_ULTRA_SUPPORT_815673C8),
                    },
                    chest = {
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER0_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER1_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER2_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER3_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER4_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_815673C8,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_SPAWN_FX_OBJECT_815673C8,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81567574,
                    objective = mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_NIGHTMARE_CHEST_1_81567574,
                    squads = {
                        unit(mission.Squad.SILENT_EVENT_NIGHTMARE_CHEST_1_SQUAD_BOSS_81567574, mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_SQUAD_BOSS_81567574),
                    },
                    chest = {
                        mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_O_CHEST_81567574,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815675A5,
                    objective = mission.Slot.PF_EVENT_PIKE_GANG01_OBJ_PIKE_EXIT_815675A5,
                    squads = {
                        unit(mission.Squad.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_815675A5, mission.Slot.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_815675A5),
                    },
                    chest = {
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815675D6,
                    objective = mission.Slot.PF_EVENT_PIKE_GANG01_OBJ_PIKE_EXIT_815675D6,
                    squads = {
                        unit(mission.Squad.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_815675D6, mission.Slot.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_815675D6),
                    },
                    chest = {
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0001_0000_81565315,
            region = 8,
            -- Lost Sector in bubble 1.
            sector = {
                boss = mission.Slot.SQU_BOSS,
                squads = {
                    unit(mission.Squad.SQU_ARC_DREGS_B, mission.Slot.SQU_ARC_DREGS_B),
                    unit(mission.Squad.SQU_ARC_ENTRY, mission.Slot.SQU_ARC_ENTRY),
                    unit(mission.Squad.SQU_ARC_ENTRY_1, mission.Slot.SQU_ARC_ENTRY_1),
                    unit(mission.Squad.SQU_BOSS, mission.Slot.SQU_BOSS),
                    unit(mission.Squad.SQU_ENTRY_CAPTAIN, mission.Slot.SQU_ENTRY_CAPTAIN),
                    unit(mission.Squad.SQU_ENTRY_MELEE_LEFT, mission.Slot.SQU_ENTRY_MELEE_LEFT),
                    unit(mission.Squad.SQU_ENTRY_MELEE_RIGHT, mission.Slot.SQU_ENTRY_MELEE_RIGHT),
                    unit(mission.Squad.SQU_ENTRY_MELEE_RIGHT_B, mission.Slot.SQU_ENTRY_MELEE_RIGHT_B),
                    unit(mission.Squad.SQU_ENTRY_SNIPERS_CENTER, mission.Slot.SQU_ENTRY_SNIPERS_CENTER),
                    unit(mission.Squad.SQU_ENTRY_SNIPERS_LEFT, mission.Slot.SQU_ENTRY_SNIPERS_LEFT),
                    unit(mission.Squad.SQU_GARAGE_CAPTAIN, mission.Slot.SQU_GARAGE_CAPTAIN),
                    unit(mission.Squad.SQU_GARAGE_EXPLODERS, mission.Slot.SQU_GARAGE_EXPLODERS),
                    unit(mission.Squad.SQU_GARAGE_EXPLODERS_1, mission.Slot.SQU_GARAGE_EXPLODERS_1),
                    unit(mission.Squad.SQU_GARAGE_EXPLODERS_2, mission.Slot.SQU_GARAGE_EXPLODERS_2),
                    unit(mission.Squad.SQU_GARAGE_EXPLODERS_3, mission.Slot.SQU_GARAGE_EXPLODERS_3),
                    unit(mission.Squad.SQU_GARAGE_EXPLODERS_4, mission.Slot.SQU_GARAGE_EXPLODERS_4),
                    unit(mission.Squad.SQU_GARAGE_EXPLODERS_5, mission.Slot.SQU_GARAGE_EXPLODERS_5),
                    unit(mission.Squad.SQU_GARAGE_SHANKS, mission.Slot.SQU_GARAGE_SHANKS),
                    unit(mission.Squad.SQU_GARAGE_SHANK_SNIPERS, mission.Slot.SQU_GARAGE_SHANK_SNIPERS),
                    unit(mission.Squad.SQU_GARAGE_SHANK_SNIPERS_1, mission.Slot.SQU_GARAGE_SHANK_SNIPERS_1),
                    unit(mission.Squad.SQU_GARAGE_SNIPERS_TOP, mission.Slot.SQU_GARAGE_SNIPERS_TOP),
                    unit(mission.Squad.SQU_GARAGE_SUPPORT_HI, mission.Slot.SQU_GARAGE_SUPPORT_HI),
                    unit(mission.Squad.SQU_GARAGE_SUPPORT_LOW, mission.Slot.SQU_GARAGE_SUPPORT_LOW),
                    unit(mission.Squad.SQU_NM01_WAVE01, mission.Slot.SQU_NM01_WAVE01),
                },
                chest = {
                    mission.Slot.BOSS_CHEST_81567B34,
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0002_0000_81565316,
            region = 16,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_B_INTRO_SQUAD, mission.Slot.DELIGHT_PANDORA_B_INTRO_SQUAD),
                unit(mission.Squad.DELIGHT_PANDORA_B_WAVE_1_SQUAD, mission.Slot.DELIGHT_PANDORA_B_WAVE_1_SQUAD),
                unit(mission.Squad.DELIGHT_PANDORA_B_WAVE_2_SQUAD, mission.Slot.DELIGHT_PANDORA_B_WAVE_2_SQUAD),
                unit(mission.Squad.DELIGHT_PANDORA_B_WAVE_3_SQUAD, mission.Slot.DELIGHT_PANDORA_B_WAVE_3_SQUAD),
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_81503F8B, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_81503F8B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_81503F8B, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_81503F8B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_81503F8B, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_81503F8B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_81503F8B, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_81503F8B),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_ANCHOR_0, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_ANCHOR_0),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_ANCHOR_1, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_ANCHOR_1),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_ANCHOR_2, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_ANCHOR_2),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_0, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_0),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_1, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_1),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_2, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_2),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_3, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_3),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_4, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_4),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_0, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_0),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_1, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_1),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_2, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_2),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_3, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_3),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_4, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_4),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_5, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_5),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_6, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_6),
                unit(mission.Squad.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_7, mission.Slot.SACRIFICE_GATEWAY_ENCOUNTER_SQ_FODDER_AERIAL_7),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81567CC2,
                    objective = mission.Slot.SPF_HOBGOBLIN_CHAMPION_OBJ_CHAMPION,
                    squads = {
                        unit(mission.Squad.SPF_HOBGOBLIN_CHAMPION_SQ_HOBGOBLINS, mission.Slot.SPF_HOBGOBLIN_CHAMPION_SQ_HOBGOBLINS),
                        unit(mission.Squad.SPF_HOBGOBLIN_CHAMPION_SQ_KNIGHTS, mission.Slot.SPF_HOBGOBLIN_CHAMPION_SQ_KNIGHTS),
                        unit(mission.Squad.SPF_HOBGOBLIN_CHAMPION_SQ_MINOTAURS, mission.Slot.SPF_HOBGOBLIN_CHAMPION_SQ_MINOTAURS),
                        unit(mission.Squad.SPF_HOBGOBLIN_CHAMPION_SQ_OGRES, mission.Slot.SPF_HOBGOBLIN_CHAMPION_SQ_OGRES),
                    },
                    chest = {
                        mission.Slot.SPF_HOBGOBLIN_CHAMPION_O_CHEST,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0003_0000_81565317,
            region = 24,
            patrol = {
                unit(mission.Squad.SQ_NIGHTMARE_HANK, mission.Slot.SQ_NIGHTMARE_HANK),
                unit(mission.Squad.SQ_NIGHTMARE_RANDAL, mission.Slot.SQ_NIGHTMARE_RANDAL),
                unit(mission.Squad.SQ_NORMAL_SHANK, mission.Slot.SQ_NORMAL_SHANK),
                unit(mission.Squad.SQ_NORMAL_VANDAL, mission.Slot.SQ_NORMAL_VANDAL),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815650A9,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_815650A9,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_815650A9, mission.Slot.PUZZLE_CHEST_SQ_GUARD_815650A9),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_815650A9,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_815650A9,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_815650A9,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_815650A9,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_815650A9,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_815650A9,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_815650A9,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81565101,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_81565101,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_81565101, mission.Slot.PUZZLE_CHEST_SQ_GUARD_81565101),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_81565101,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_81565101,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_81565101,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_81565101,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_81565101,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_81565101,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_81565101,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81565159,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_81565159,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_81565159, mission.Slot.PUZZLE_CHEST_SQ_GUARD_81565159),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_81565159,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_81565159,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_81565159,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_81565159,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_81565159,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_81565159,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_81565159,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_8156578D,
                    objective = mission.Slot.AI_OBJ_0,
                    squads = {
                        unit(mission.Squad.PYLON_0_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_0_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_0_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_0_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_10_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_10_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_10_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_10_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_11_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_11_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_11_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_11_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_1_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_1_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_1_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_1_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_2_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_2_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_2_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_2_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_3_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_3_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_3_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_3_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_4_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_4_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_4_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_4_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_5_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_5_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_5_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_5_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_6_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_6_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_6_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_6_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_7_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_7_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_7_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_7_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_8_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_8_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_8_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_8_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.PYLON_9_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0, mission.Slot.PYLON_9_HORDE_MODE_SWORDBEARER_1_SQ_SWORDBEARER_BOSS_0),
                        unit(mission.Squad.PYLON_9_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD, mission.Slot.PYLON_9_SPF_HORDE_CRYSTAL_COMBATANT_0_SQ_WIZARD),
                        unit(mission.Squad.SQ_HIVE_HORDE_BOSS_SHRIEKER_0, mission.Slot.SQ_HIVE_HORDE_BOSS_SHRIEKER_0),
                        unit(mission.Squad.SQ_HIVE_HORDE_BOSS_SHRIEKER_1, mission.Slot.SQ_HIVE_HORDE_BOSS_SHRIEKER_1),
                        unit(mission.Squad.SQ_HIVE_HORDE_BOSS_SHRIEKER_2, mission.Slot.SQ_HIVE_HORDE_BOSS_SHRIEKER_2),
                    },
                    chest = {
                        mission.Slot.PYLON_0_O_CHEST_0,
                        mission.Slot.PYLON_0_O_CHEST_1,
                        mission.Slot.PYLON_0_O_CHEST_2,
                        mission.Slot.PYLON_0_O_CHEST_3,
                        mission.Slot.PYLON_0_O_CHEST_4,
                        mission.Slot.PYLON_0_O_KEY_CHEST,
                        mission.Slot.PYLON_10_O_CHEST_0,
                        mission.Slot.PYLON_10_O_CHEST_1,
                        mission.Slot.PYLON_10_O_CHEST_2,
                        mission.Slot.PYLON_10_O_CHEST_3,
                        mission.Slot.PYLON_10_O_CHEST_4,
                        mission.Slot.PYLON_10_O_KEY_CHEST,
                        mission.Slot.PYLON_11_O_CHEST_0,
                        mission.Slot.PYLON_11_O_CHEST_1,
                        mission.Slot.PYLON_11_O_CHEST_2,
                        mission.Slot.PYLON_11_O_CHEST_3,
                        mission.Slot.PYLON_11_O_CHEST_4,
                        mission.Slot.PYLON_11_O_KEY_CHEST,
                        mission.Slot.PYLON_1_O_CHEST_0,
                        mission.Slot.PYLON_1_O_CHEST_1,
                        mission.Slot.PYLON_1_O_CHEST_2,
                        mission.Slot.PYLON_1_O_CHEST_3,
                        mission.Slot.PYLON_1_O_CHEST_4,
                        mission.Slot.PYLON_1_O_KEY_CHEST,
                        mission.Slot.PYLON_2_O_CHEST_0,
                        mission.Slot.PYLON_2_O_CHEST_1,
                        mission.Slot.PYLON_2_O_CHEST_2,
                        mission.Slot.PYLON_2_O_CHEST_3,
                        mission.Slot.PYLON_2_O_CHEST_4,
                        mission.Slot.PYLON_2_O_KEY_CHEST,
                        mission.Slot.PYLON_3_O_CHEST_0,
                        mission.Slot.PYLON_3_O_CHEST_1,
                        mission.Slot.PYLON_3_O_CHEST_2,
                        mission.Slot.PYLON_3_O_CHEST_3,
                        mission.Slot.PYLON_3_O_CHEST_4,
                        mission.Slot.PYLON_3_O_KEY_CHEST,
                        mission.Slot.PYLON_4_O_CHEST_0,
                        mission.Slot.PYLON_4_O_CHEST_1,
                        mission.Slot.PYLON_4_O_CHEST_2,
                        mission.Slot.PYLON_4_O_CHEST_3,
                        mission.Slot.PYLON_4_O_CHEST_4,
                        mission.Slot.PYLON_4_O_KEY_CHEST,
                        mission.Slot.PYLON_5_O_CHEST_0,
                        mission.Slot.PYLON_5_O_CHEST_1,
                        mission.Slot.PYLON_5_O_CHEST_2,
                        mission.Slot.PYLON_5_O_CHEST_3,
                        mission.Slot.PYLON_5_O_CHEST_4,
                        mission.Slot.PYLON_5_O_KEY_CHEST,
                        mission.Slot.PYLON_6_O_CHEST_0,
                        mission.Slot.PYLON_6_O_CHEST_1,
                        mission.Slot.PYLON_6_O_CHEST_2,
                        mission.Slot.PYLON_6_O_CHEST_3,
                        mission.Slot.PYLON_6_O_CHEST_4,
                        mission.Slot.PYLON_6_O_KEY_CHEST,
                        mission.Slot.PYLON_7_O_CHEST_0,
                        mission.Slot.PYLON_7_O_CHEST_1,
                        mission.Slot.PYLON_7_O_CHEST_2,
                        mission.Slot.PYLON_7_O_CHEST_3,
                        mission.Slot.PYLON_7_O_CHEST_4,
                        mission.Slot.PYLON_7_O_KEY_CHEST,
                        mission.Slot.PYLON_8_O_CHEST_0,
                        mission.Slot.PYLON_8_O_CHEST_1,
                        mission.Slot.PYLON_8_O_CHEST_2,
                        mission.Slot.PYLON_8_O_CHEST_3,
                        mission.Slot.PYLON_8_O_CHEST_4,
                        mission.Slot.PYLON_8_O_KEY_CHEST,
                        mission.Slot.PYLON_9_O_CHEST_0,
                        mission.Slot.PYLON_9_O_CHEST_1,
                        mission.Slot.PYLON_9_O_CHEST_2,
                        mission.Slot.PYLON_9_O_CHEST_3,
                        mission.Slot.PYLON_9_O_CHEST_4,
                        mission.Slot.PYLON_9_O_KEY_CHEST,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81565E39,
                    objective = mission.Slot.PF_EVENT_PIKE_GANG_OBJ_PIKE_EXIT,
                    squads = {
                        unit(mission.Squad.PF_EVENT_PIKE_GANG_SQ_EVENT_PIKE_0, mission.Slot.PF_EVENT_PIKE_GANG_SQ_EVENT_PIKE_0),
                    },
                    chest = {
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0004_0000_81565318,
            region = 32,
            -- Lost Sector in bubble 4.
            sector = {
                boss = mission.Slot.SQ_DIG_BOSS,
                squads = {
                    unit(mission.Squad.SQ_BRIDGE_1_8157011D, mission.Slot.SQ_BRIDGE_1_8157011D),
                    unit(mission.Squad.SQ_BRIDGE_2, mission.Slot.SQ_BRIDGE_2),
                    unit(mission.Squad.SQ_BRIDGE_3, mission.Slot.SQ_BRIDGE_3),
                    unit(mission.Squad.SQ_BRIDGE_SHRIEKER, mission.Slot.SQ_BRIDGE_SHRIEKER),
                    unit(mission.Squad.SQ_DIG_BOSS, mission.Slot.SQ_DIG_BOSS),
                    unit(mission.Squad.SQ_DIG_CRYS1_ANCHOR, mission.Slot.SQ_DIG_CRYS1_ANCHOR),
                    unit(mission.Squad.SQ_DIG_CRYS1_WAVE1_1, mission.Slot.SQ_DIG_CRYS1_WAVE1_1),
                    unit(mission.Squad.SQ_DIG_CRYS1_WAVE1_2, mission.Slot.SQ_DIG_CRYS1_WAVE1_2),
                    unit(mission.Squad.SQ_DIG_CRYS1_WAVE1_3, mission.Slot.SQ_DIG_CRYS1_WAVE1_3),
                    unit(mission.Squad.SQ_DIG_CRYS1_WAVE2_1, mission.Slot.SQ_DIG_CRYS1_WAVE2_1),
                    unit(mission.Squad.SQ_DIG_CRYS1_WAVE2_2, mission.Slot.SQ_DIG_CRYS1_WAVE2_2),
                    unit(mission.Squad.SQ_DIG_CRYS1_WAVE2_3, mission.Slot.SQ_DIG_CRYS1_WAVE2_3),
                    unit(mission.Squad.SQ_DIG_CRYS2_ANCHOR, mission.Slot.SQ_DIG_CRYS2_ANCHOR),
                    unit(mission.Squad.SQ_DIG_CRYS2_WAVE1_1, mission.Slot.SQ_DIG_CRYS2_WAVE1_1),
                    unit(mission.Squad.SQ_DIG_CRYS2_WAVE1_2, mission.Slot.SQ_DIG_CRYS2_WAVE1_2),
                    unit(mission.Squad.SQ_DIG_CRYS2_WAVE1_3, mission.Slot.SQ_DIG_CRYS2_WAVE1_3),
                    unit(mission.Squad.SQ_DIG_CRYS2_WAVE2_1, mission.Slot.SQ_DIG_CRYS2_WAVE2_1),
                    unit(mission.Squad.SQ_DIG_CRYS2_WAVE2_2, mission.Slot.SQ_DIG_CRYS2_WAVE2_2),
                    unit(mission.Squad.SQ_DIG_CRYS2_WAVE2_3, mission.Slot.SQ_DIG_CRYS2_WAVE2_3),
                    unit(mission.Squad.SQ_DIG_CRYS3_ANCHOR, mission.Slot.SQ_DIG_CRYS3_ANCHOR),
                    unit(mission.Squad.SQ_DIG_CRYS3_WAVE1_1, mission.Slot.SQ_DIG_CRYS3_WAVE1_1),
                    unit(mission.Squad.SQ_DIG_CRYS3_WAVE1_2, mission.Slot.SQ_DIG_CRYS3_WAVE1_2),
                    unit(mission.Squad.SQ_DIG_CRYS3_WAVE1_3, mission.Slot.SQ_DIG_CRYS3_WAVE1_3),
                    unit(mission.Squad.SQ_DIG_CRYS3_WAVE2_1, mission.Slot.SQ_DIG_CRYS3_WAVE2_1),
                },
                chest = {
                    mission.Slot.BOSS_CHEST_8157022B,
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0008_0000_8156531C,
            region = 64,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_81564269, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_81564269),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_81564269, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_81564269),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_81564269, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_81564269),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_81564269, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_81564269),
                unit(mission.Squad.SQ_FRONT_0, mission.Slot.SQ_FRONT_0),
                unit(mission.Squad.SQ_FRONT_1, mission.Slot.SQ_FRONT_1),
                unit(mission.Squad.SQ_FRONT_2, mission.Slot.SQ_FRONT_2),
                unit(mission.Squad.SQ_FRONT_3, mission.Slot.SQ_FRONT_3),
                unit(mission.Squad.SQ_FRONT_4, mission.Slot.SQ_FRONT_4),
                unit(mission.Squad.SQ_FRONT_5, mission.Slot.SQ_FRONT_5),
                unit(mission.Squad.SQ_HUNTERS_0, mission.Slot.SQ_HUNTERS_0),
                unit(mission.Squad.SQ_HUNTERS_1, mission.Slot.SQ_HUNTERS_1),
                unit(mission.Squad.SQ_HUNTERS_2, mission.Slot.SQ_HUNTERS_2),
                unit(mission.Squad.SQ_HUNTERS_3, mission.Slot.SQ_HUNTERS_3),
                unit(mission.Squad.SQ_HUNTERS_4, mission.Slot.SQ_HUNTERS_4),
                unit(mission.Squad.SQ_MID_0_81570349, mission.Slot.SQ_MID_0_81570349),
                unit(mission.Squad.SQ_MID_0_815703F9, mission.Slot.SQ_MID_0_815703F9),
                unit(mission.Squad.SQ_MID_1_81570349, mission.Slot.SQ_MID_1_81570349),
                unit(mission.Squad.SQ_MID_1_815703F9, mission.Slot.SQ_MID_1_815703F9),
                unit(mission.Squad.SQ_MID_2_81570349, mission.Slot.SQ_MID_2_81570349),
                unit(mission.Squad.SQ_MID_2_815703F9, mission.Slot.SQ_MID_2_815703F9),
                unit(mission.Squad.SQ_MID_3_81570349, mission.Slot.SQ_MID_3_81570349),
                unit(mission.Squad.SQ_MID_3_815703F9, mission.Slot.SQ_MID_3_815703F9),
                unit(mission.Squad.SQ_SQUAD_0_815703F9, mission.Slot.SQ_SQUAD_0_815703F9),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570294,
                    objective = mission.Slot.SPF_KNIGHT_CHAMPION_OBJ_CHAMPION_81570294,
                    squads = {
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81570294, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81570294),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81570294, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81570294),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81570294, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81570294),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_OGRES_81570294, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_OGRES_81570294),
                    },
                    chest = {
                        mission.Slot.SPF_KNIGHT_CHAMPION_O_CHEST_81570294,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0009_0000_8156531D,
            region = 72,
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570539,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_81570539,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_81570539, mission.Slot.PUZZLE_CHEST_SQ_GUARD_81570539),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_81570539,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_81570539,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_81570539,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_81570539,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_81570539,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_81570539,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_81570539,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570591,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_81570591,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_81570591, mission.Slot.PUZZLE_CHEST_SQ_GUARD_81570591),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_81570591,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_81570591,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_81570591,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_81570591,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_81570591,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_81570591,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_81570591,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815705E9,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_815705E9,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_815705E9, mission.Slot.PUZZLE_CHEST_SQ_GUARD_815705E9),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_815705E9,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_815705E9,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_815705E9,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_815705E9,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_815705E9,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_815705E9,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_815705E9,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570AC3,
                    objective = mission.Slot.PF_EVENT_HIVE_RITUAL_1_OBJ_MAIN,
                    squads = {
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_INITIAL, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_1_INITIAL),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_INITIAL, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_ACOLYTES_SIGIL_2_INITIAL),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_DARKBLADE, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_DARKBLADE),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO0, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO0),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO3, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO3),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO4, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO4),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO5, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_EXPLOSIVE_THRALL_HEROIC_INTRO5),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_INITIAL_NON_MAJOR, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_1_INITIAL_NON_MAJOR),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_INITIAL_NON_MAJOR, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_KNIGHT_SIGIL_2_INITIAL_NON_MAJOR),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_MEDITATION_WIZARD_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_1, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_1),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_2, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_2),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_3, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_THRALL_G_3),
                        unit(mission.Squad.PF_EVENT_HIVE_RITUAL_1_SQ_WIZARD_BOSS, mission.Slot.PF_EVENT_HIVE_RITUAL_1_SQ_WIZARD_BOSS),
                        unit(mission.Squad.SQ_OGRE_PARADE_0, mission.Slot.SQ_OGRE_PARADE_0),
                        unit(mission.Squad.SQ_OGRE_PARADE_1, mission.Slot.SQ_OGRE_PARADE_1),
                        unit(mission.Squad.SQ_OGRE_PARADE_2, mission.Slot.SQ_OGRE_PARADE_2),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_HIVE_RITUAL_1_PF_REWARD_CHEST_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570C07,
                    objective = mission.Slot.PF_LUNA_WARSAT_PE_OBJ_EVENT_ENEMY_ENTER_81570C07,
                    squads = {
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_1_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_1_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_2_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_2_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_3_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_3_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_0_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_0_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_1_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_1_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_2_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_2_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_2_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_2_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_0_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_0_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_1_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_1_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_2_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_2_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_ULTRA_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_ULTRA_81570C07),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_ULTRA_SUPPORT_81570C07, mission.Slot.PF_LUNA_WARSAT_PE_SQ_ULTRA_SUPPORT_81570C07),
                    },
                    chest = {
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER0_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER1_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER2_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER3_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER4_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_81570C07,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_SPAWN_FX_OBJECT_81570C07,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570C84,
                    objective = mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_0_OBJECTIVE_81570C84,
                    squads = {
                        unit(mission.Squad.EVENT_CONVOY_CORE_BOSS_SQUAD_81570C84, mission.Slot.EVENT_CONVOY_CORE_BOSS_SQUAD_81570C84),
                        unit(mission.Squad.SQ_FOLLOWERS_81570C84, mission.Slot.SQ_FOLLOWERS_81570C84),
                    },
                    chest = {
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_0_CONVOY_CHEST_OBJECT_81570C84,
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_1_CONVOY_CHEST_OBJECT_81570C84,
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_2_CONVOY_CHEST_OBJECT_81570C84,
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_3_CONVOY_CHEST_OBJECT_81570C84,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570CD9,
                    objective = mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_0_OBJECTIVE_81570CD9,
                    squads = {
                        unit(mission.Squad.EVENT_CONVOY_CORE_BOSS_SQUAD_81570CD9, mission.Slot.EVENT_CONVOY_CORE_BOSS_SQUAD_81570CD9),
                        unit(mission.Squad.SQ_FOLLOWERS_81570CD9, mission.Slot.SQ_FOLLOWERS_81570CD9),
                    },
                    chest = {
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_0_CONVOY_CHEST_OBJECT_81570CD9,
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_1_CONVOY_CHEST_OBJECT_81570CD9,
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_2_CONVOY_CHEST_OBJECT_81570CD9,
                        mission.Slot.EVENT_CONVOY_CORE_CONVOY_POINTS_3_CONVOY_CHEST_OBJECT_81570CD9,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570D34,
                    objective = mission.Slot.EVENT_COWARDLY_MAJOR_CORE_OBJECTIVE_81570D34,
                    squads = {
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_FODDER_SQUAD_81570D34, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_FODDER_SQUAD_81570D34),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_81570D34, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_81570D34),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_MAJOR_SQUAD_81570D34, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_MAJOR_SQUAD_81570D34),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_81570D34, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_81570D34),
                    },
                    chest = {
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_81570D34,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_81570D34,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570D9B,
                    objective = mission.Slot.PF_EVENT_FALLEN_INCURSION_1_OBJECTIVE_81570D9B,
                    squads = {
                        unit(mission.Squad.SQ_HIVE_RESISTANCE_81570D9B, mission.Slot.SQ_HIVE_RESISTANCE_81570D9B),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_FALLEN_INCURSION_1_LOCKED_CHEST_OBJECT_81570D9B,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570E02,
                    objective = mission.Slot.PF_EVENT_FALLEN_INCURSION_1_OBJECTIVE_81570E02,
                    squads = {
                        unit(mission.Squad.SQ_HIVE_RESISTANCE_81570E02, mission.Slot.SQ_HIVE_RESISTANCE_81570E02),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_FALLEN_INCURSION_1_LOCKED_CHEST_OBJECT_81570E02,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570E78,
                    objective = mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_NIGHTMARE_CHEST_1_81570E78,
                    squads = {
                        unit(mission.Squad.SILENT_EVENT_NIGHTMARE_CHEST_1_SQUAD_BOSS_81570E78, mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_SQUAD_BOSS_81570E78),
                    },
                    chest = {
                        mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_O_CHEST_81570E78,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570EEE,
                    objective = mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_NIGHTMARE_CHEST_1_81570EEE,
                    squads = {
                        unit(mission.Squad.SILENT_EVENT_NIGHTMARE_CHEST_1_SQUAD_BOSS_81570EEE, mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_SQUAD_BOSS_81570EEE),
                    },
                    chest = {
                        mission.Slot.SILENT_EVENT_NIGHTMARE_CHEST_1_O_CHEST_81570EEE,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570F25,
                    objective = mission.Slot.PF_EVENT_PIKE_GANG01_OBJ_PIKE_EXIT_81570F25,
                    squads = {
                        unit(mission.Squad.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_81570F25, mission.Slot.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_81570F25),
                    },
                    chest = {
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81570F5C,
                    objective = mission.Slot.PF_EVENT_PIKE_GANG01_OBJ_PIKE_EXIT_81570F5C,
                    squads = {
                        unit(mission.Squad.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_81570F5C, mission.Slot.PF_EVENT_PIKE_GANG01_SQ_EVENT_PIKE_0_81570F5C),
                    },
                    chest = {
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_000A_0000_8156531E,
            region = 80,
            -- Lost Sector in bubble 10.
            sector = {
                boss = mission.Slot.SQ_BOSS_81571311,
                squads = {
                    unit(mission.Squad.SQ_BOSS_81571311, mission.Slot.SQ_BOSS_81571311),
                    unit(mission.Squad.SQ_BRIDGE, mission.Slot.SQ_BRIDGE),
                    unit(mission.Squad.SQ_BRIDGE_1_81571311, mission.Slot.SQ_BRIDGE_1_81571311),
                    unit(mission.Squad.SQ_COLLAPSE, mission.Slot.SQ_COLLAPSE),
                    unit(mission.Squad.SQ_COLLAPSE_1, mission.Slot.SQ_COLLAPSE_1),
                    unit(mission.Squad.SQ_ENTRANCE, mission.Slot.SQ_ENTRANCE),
                    unit(mission.Squad.SQ_ENTRANCE_1, mission.Slot.SQ_ENTRANCE_1),
                    unit(mission.Squad.SQ_ENTRANCE_2, mission.Slot.SQ_ENTRANCE_2),
                    unit(mission.Squad.SQ_ENTRANCE_3, mission.Slot.SQ_ENTRANCE_3),
                    unit(mission.Squad.SQ_ENTRANCE_4, mission.Slot.SQ_ENTRANCE_4),
                    unit(mission.Squad.SQ_ENTRANCE_5, mission.Slot.SQ_ENTRANCE_5),
                    unit(mission.Squad.SQ_RAVINE, mission.Slot.SQ_RAVINE),
                    unit(mission.Squad.SQ_RAVINE_1, mission.Slot.SQ_RAVINE_1),
                    unit(mission.Squad.SQ_RAVINE_10, mission.Slot.SQ_RAVINE_10),
                    unit(mission.Squad.SQ_RAVINE_11, mission.Slot.SQ_RAVINE_11),
                    unit(mission.Squad.SQ_RAVINE_12, mission.Slot.SQ_RAVINE_12),
                    unit(mission.Squad.SQ_RAVINE_2, mission.Slot.SQ_RAVINE_2),
                    unit(mission.Squad.SQ_RAVINE_3, mission.Slot.SQ_RAVINE_3),
                    unit(mission.Squad.SQ_RAVINE_3B, mission.Slot.SQ_RAVINE_3B),
                    unit(mission.Squad.SQ_RAVINE_4, mission.Slot.SQ_RAVINE_4),
                    unit(mission.Squad.SQ_RAVINE_5, mission.Slot.SQ_RAVINE_5),
                    unit(mission.Squad.SQ_RAVINE_6, mission.Slot.SQ_RAVINE_6),
                    unit(mission.Squad.SQ_RAVINE_7, mission.Slot.SQ_RAVINE_7),
                    unit(mission.Squad.SQ_RAVINE_8, mission.Slot.SQ_RAVINE_8),
                },
                chest = {
                    mission.Slot.BOSS_CHEST_81571412,
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_000D_0000_81565321,
            region = 104,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_815643A8, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_815643A8),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_815643A8, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_815643A8),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_815643A8, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_815643A8),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_815643A8, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_815643A8),
                unit(mission.Squad.SQ_WEAPON5_REINF, mission.Slot.SQ_WEAPON5_REINF),
                unit(mission.Squad.SQ_WEAPON5_TARGET, mission.Slot.SQ_WEAPON5_TARGET),
            },
        },
        {
            state = mission.states.STATE_81503E69_000E_0000_81565323,
            region = 112,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_8156442C, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_8156442C),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_8156442C, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_8156442C),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_8156442C, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_8156442C),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_8156442C, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_8156442C),
            },
        },
        {
            state = mission.states.STATE_81503E69_0010_0000_81565325,
            region = 128,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_81564464, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_81564464),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_81564464, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_81564464),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_81564464, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_81564464),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_81564464, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_81564464),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81571C42,
                    objective = mission.Slot.SPF_KNIGHT_CHAMPION_OBJ_CHAMPION_81571C42,
                    squads = {
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81571C42, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81571C42),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81571C42, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81571C42),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81571C42, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81571C42),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_OGRES_81571C42, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_OGRES_81571C42),
                    },
                    chest = {
                        mission.Slot.SPF_KNIGHT_CHAMPION_O_CHEST_81571C42,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0014_0000_81565326,
            region = 160,
            patrol = {
                unit(mission.Squad.SQ_BONECOLLECTOR, mission.Slot.SQ_BONECOLLECTOR),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_8157205D,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_8157205D,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_8157205D, mission.Slot.PUZZLE_CHEST_SQ_GUARD_8157205D),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_8157205D,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_8157205D,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_8157205D,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_8157205D,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_8157205D,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_8157205D,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_8157205D,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815720B5,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_815720B5,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_815720B5, mission.Slot.PUZZLE_CHEST_SQ_GUARD_815720B5),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_815720B5,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_815720B5,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_815720B5,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_815720B5,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_815720B5,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_815720B5,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_815720B5,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_8157210D,
                    objective = mission.Slot.PUZZLE_CHEST_OBJ_GUARD_8157210D,
                    squads = {
                        unit(mission.Squad.PUZZLE_CHEST_SQ_GUARD_8157210D, mission.Slot.PUZZLE_CHEST_SQ_GUARD_8157210D),
                    },
                    chest = {
                        mission.Slot.PUZZLE_CHEST_O_CHEST_8157210D,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_0_8157210D,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_1_8157210D,
                        mission.Slot.PUZZLE_CHEST_O_DEST_RUNE_2_8157210D,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_0_8157210D,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_1_8157210D,
                        mission.Slot.PUZZLE_CHEST_O_TRANSMAT_RUNE_2_8157210D,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81572437,
                    objective = mission.Slot.PF_EVENT_SPIDER_TANK_OBJ_TANK,
                    squads = {
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_DROPSHIP_HEROIC, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_DROPSHIP_HEROIC),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_DROPSHIP_TANK, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_DROPSHIP_TANK),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_HEROIC_ANCHOR, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_HEROIC_ANCHOR),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_HEROIC_ANCHOR_HARD, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_HEROIC_ANCHOR_HARD),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_HEROIC_HARD, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_HEROIC_HARD),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_HEROIC_REGULAR, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_HEROIC_REGULAR),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_HEROIC_TANK, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_HEROIC_TANK),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_INITIAL_SCORCH_CAPTAIN, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_INITIAL_SCORCH_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_HARD_1, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_HARD_1),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_HARD_2, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_HARD_2),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_HARD_3, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_HARD_3),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_MEDIUM_1, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_MEDIUM_1),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_MEDIUM_2, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_MEDIUM_2),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_MEDIUM_3, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_FODDER_CACHE_MEDIUM_3),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_MINIONS, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_MINIONS),
                        unit(mission.Squad.PF_EVENT_SPIDER_TANK_SQ_TANK_MINIONS_HEROIC, mission.Slot.PF_EVENT_SPIDER_TANK_SQ_TANK_MINIONS_HEROIC),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT,
                        mission.Slot.PF_EVENT_SPIDER_TANK_CHEST_PREFAB_SPAWN_FX_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81572598,
                    objective = mission.Slot.PF_LUNA_WARSAT_PE_OBJ_EVENT_ENEMY_ENTER_81572598,
                    squads = {
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_1_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_1_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_2_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_2_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_3_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_HEROIC_TRIGGER_3_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_0_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_0_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_1_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_1_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MAJORS_2_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MAJORS_2_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_2_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_2_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_MEDITATION_WIZARD_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_0_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_0_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_1_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_1_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_2_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_SWORDBEARER_KNIGHT_2_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_ULTRA_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_ULTRA_81572598),
                        unit(mission.Squad.PF_LUNA_WARSAT_PE_SQ_ULTRA_SUPPORT_81572598, mission.Slot.PF_LUNA_WARSAT_PE_SQ_ULTRA_SUPPORT_81572598),
                    },
                    chest = {
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER0_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER1_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER2_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER3_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_TIER4_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_81572598,
                        mission.Slot.PF_LUNA_WARSAT_PE_CHEST_PREFAB_SPAWN_FX_OBJECT_81572598,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_815726B3,
                    objective = mission.Slot.EVENT_COWARDLY_MAJOR_CORE_OBJECTIVE_815726B3,
                    squads = {
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_FODDER_SQUAD_815726B3, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_FODDER_SQUAD_815726B3),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_815726B3, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_815726B3),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_MAJOR_SQUAD_815726B3, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_MAJOR_SQUAD_815726B3),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_815726B3, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_815726B3),
                    },
                    chest = {
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_815726B3,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_815726B3,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_8157270E,
                    objective = mission.Slot.EVENT_COWARDLY_MAJOR_CORE_OBJECTIVE_8157270E,
                    squads = {
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_FODDER_SQUAD_8157270E, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_FODDER_SQUAD_8157270E),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_8157270E, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_MAJOR_FODDER_SQUAD_8157270E),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_MAJOR_SQUAD_8157270E, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_MAJOR_SQUAD_8157270E),
                        unit(mission.Squad.EVENT_COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_8157270E, mission.Slot.EVENT_COWARDLY_MAJOR_CORE_NO_LOOT_FODDER_SQUAD_8157270E),
                    },
                    chest = {
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_CONVOY_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER0_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER1_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER2_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER3_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_TIER4_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_8157270E,
                        mission.Slot.EVENT_COWARDLY_MAJOR_CORE_CHEST_PREFAB_SPAWN_FX_OBJECT_8157270E,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0015_0000_81565327,
            region = 168,
            -- Lost Sector in bubble 21.
            sector = {
                boss = mission.Slot.SQ_CORE_BOSS,
                squads = {
                    unit(mission.Squad.SQ_CONNECTOR_A_1, mission.Slot.SQ_CONNECTOR_A_1),
                    unit(mission.Squad.SQ_CONNECTOR_B_1, mission.Slot.SQ_CONNECTOR_B_1),
                    unit(mission.Squad.SQ_CONNECTOR_INTRO, mission.Slot.SQ_CONNECTOR_INTRO),
                    unit(mission.Squad.SQ_CORE_BOSS, mission.Slot.SQ_CORE_BOSS),
                    unit(mission.Squad.SQ_CORE_INITIAL_1, mission.Slot.SQ_CORE_INITIAL_1),
                    unit(mission.Squad.SQ_CORE_INITIAL_2, mission.Slot.SQ_CORE_INITIAL_2),
                    unit(mission.Squad.SQ_CORE_PRE_A_1, mission.Slot.SQ_CORE_PRE_A_1),
                    unit(mission.Squad.SQ_CORE_PRE_A_2, mission.Slot.SQ_CORE_PRE_A_2),
                    unit(mission.Squad.SQ_CORE_PRE_A_3, mission.Slot.SQ_CORE_PRE_A_3),
                    unit(mission.Squad.SQ_CORE_PRE_A_4, mission.Slot.SQ_CORE_PRE_A_4),
                    unit(mission.Squad.SQ_CORE_PRE_A_5, mission.Slot.SQ_CORE_PRE_A_5),
                    unit(mission.Squad.SQ_CORE_PRE_B_1, mission.Slot.SQ_CORE_PRE_B_1),
                    unit(mission.Squad.SQ_CORE_PRE_B_2, mission.Slot.SQ_CORE_PRE_B_2),
                    unit(mission.Squad.SQ_CORE_PRE_B_3, mission.Slot.SQ_CORE_PRE_B_3),
                    unit(mission.Squad.SQ_CORE_PRE_B_4, mission.Slot.SQ_CORE_PRE_B_4),
                    unit(mission.Squad.SQ_CORE_PRE_B_5, mission.Slot.SQ_CORE_PRE_B_5),
                    unit(mission.Squad.SQ_CORE_PRE_C_1, mission.Slot.SQ_CORE_PRE_C_1),
                    unit(mission.Squad.SQ_CORE_PRE_C_2, mission.Slot.SQ_CORE_PRE_C_2),
                    unit(mission.Squad.SQ_CORE_PRE_C_3, mission.Slot.SQ_CORE_PRE_C_3),
                    unit(mission.Squad.SQ_CORE_WAVE_A_1, mission.Slot.SQ_CORE_WAVE_A_1),
                    unit(mission.Squad.SQ_CORE_WAVE_A_2, mission.Slot.SQ_CORE_WAVE_A_2),
                    unit(mission.Squad.SQ_CORE_WAVE_A_3, mission.Slot.SQ_CORE_WAVE_A_3),
                    unit(mission.Squad.SQ_CORE_WAVE_A_4, mission.Slot.SQ_CORE_WAVE_A_4),
                    unit(mission.Squad.SQ_CORE_WAVE_B_1, mission.Slot.SQ_CORE_WAVE_B_1),
                },
                chest = {
                    mission.Slot.BOSS_CHEST_81572CE7,
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0017_0000_81565329,
            region = 184,
            patrol = {
                unit(mission.Squad.SQ_ERIS_2, mission.Slot.SQ_ERIS_2),
                unit(mission.Squad.SQ_ERIS_3, mission.Slot.SQ_ERIS_3),
            },
        },
        {
            state = mission.states.STATE_81503E69_0018_0000_8156532A,
            region = 192,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_8156459B, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_8156459B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_8156459B, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_8156459B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_8156459B, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_8156459B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_8156459B, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_8156459B),
                unit(mission.Squad.SQ_WEAPON1_REINF, mission.Slot.SQ_WEAPON1_REINF),
                unit(mission.Squad.SQ_WEAPON1_TARGET, mission.Slot.SQ_WEAPON1_TARGET),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81572ECA,
                    objective = mission.Slot.SPF_KNIGHT_CHAMPION_OBJ_CHAMPION_81572ECA,
                    squads = {
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81572ECA, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81572ECA),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81572ECA, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81572ECA),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81572ECA, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81572ECA),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_OGRES_81572ECA, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_OGRES_81572ECA),
                    },
                    chest = {
                        mission.Slot.SPF_KNIGHT_CHAMPION_O_CHEST_81572ECA,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_0019_0000_8156532B,
            region = 200,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_815645D3, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_815645D3),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_815645D3, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_815645D3),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_815645D3, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_815645D3),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_815645D3, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_815645D3),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81572F35,
                    objective = mission.Slot.SPF_OGRE_CHAMPION_OBJ_CHAMPION,
                    squads = {
                        unit(mission.Squad.SPF_OGRE_CHAMPION_SQ_HOBGOBLINS, mission.Slot.SPF_OGRE_CHAMPION_SQ_HOBGOBLINS),
                        unit(mission.Squad.SPF_OGRE_CHAMPION_SQ_KNIGHTS, mission.Slot.SPF_OGRE_CHAMPION_SQ_KNIGHTS),
                        unit(mission.Squad.SPF_OGRE_CHAMPION_SQ_MINOTAURS, mission.Slot.SPF_OGRE_CHAMPION_SQ_MINOTAURS),
                        unit(mission.Squad.SPF_OGRE_CHAMPION_SQ_OGRES, mission.Slot.SPF_OGRE_CHAMPION_SQ_OGRES),
                    },
                    chest = {
                        mission.Slot.SPF_OGRE_CHAMPION_O_CHEST,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_001B_0000_8156532D,
            region = 216,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_8156460B, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_8156460B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_8156460B, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_8156460B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_8156460B, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_8156460B),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_8156460B, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_8156460B),
                unit(mission.Squad.SQ_WEAPON8_REINF, mission.Slot.SQ_WEAPON8_REINF),
                unit(mission.Squad.SQ_WEAPON8_TARGET, mission.Slot.SQ_WEAPON8_TARGET),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81573656,
                    objective = mission.Slot.SPF_KNIGHT_CHAMPION_OBJ_CHAMPION_81573656,
                    squads = {
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81573656, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_81573656),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81573656, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_81573656),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81573656, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_81573656),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_OGRES_81573656, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_OGRES_81573656),
                    },
                    chest = {
                        mission.Slot.SPF_KNIGHT_CHAMPION_O_CHEST_81573656,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_001D_0000_8156532F,
            region = 232,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_81564644, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_81564644),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_81564644, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_81564644),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_81564644, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_81564644),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_81564644, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_81564644),
                unit(mission.Squad.SQ_WEAPON7_REINF, mission.Slot.SQ_WEAPON7_REINF),
                unit(mission.Squad.SQ_WEAPON7_TARGET, mission.Slot.SQ_WEAPON7_TARGET),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_8157370E,
                    objective = mission.Slot.SPF_KNIGHT_CHAMPION_OBJ_CHAMPION_8157370E,
                    squads = {
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_8157370E, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_HOBGOBLINS_8157370E),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_8157370E, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_KNIGHTS_8157370E),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_8157370E, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_MINOTAURS_8157370E),
                        unit(mission.Squad.SPF_KNIGHT_CHAMPION_SQ_OGRES_8157370E, mission.Slot.SPF_KNIGHT_CHAMPION_SQ_OGRES_8157370E),
                    },
                    chest = {
                        mission.Slot.SPF_KNIGHT_CHAMPION_O_CHEST_8157370E,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_81503E69_001E_0000_81565330,
            region = 240,
            patrol = {
                unit(mission.Squad.SQ_ERIS_1_81573804, mission.Slot.SQ_ERIS_1_81573804),
                unit(mission.Squad.SQ_ERIS_1_8157383C, mission.Slot.SQ_ERIS_1_8157383C),
                unit(mission.Squad.SQ_ERIS_1_81573870, mission.Slot.SQ_ERIS_1_81573870),
                unit(mission.Squad.SQ_ERIS_1_815738A5, mission.Slot.SQ_ERIS_1_815738A5),
                unit(mission.Squad.SQ_ERIS_1_815738DA, mission.Slot.SQ_ERIS_1_815738DA),
                unit(mission.Squad.SQ_ERIS_1_8157390E, mission.Slot.SQ_ERIS_1_8157390E),
            },
        },
        {
            state = mission.states.STATE_81503E69_001F_0000_81565331,
            region = 248,
            patrol = {
                unit(mission.Squad.DELIGHT_PANDORA_INTRO_SQUAD_815646C9, mission.Slot.DELIGHT_PANDORA_INTRO_SQUAD_815646C9),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_1_SQUAD_815646C9, mission.Slot.DELIGHT_PANDORA_WAVE_1_SQUAD_815646C9),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_2_SQUAD_815646C9, mission.Slot.DELIGHT_PANDORA_WAVE_2_SQUAD_815646C9),
                unit(mission.Squad.DELIGHT_PANDORA_WAVE_3_SQUAD_815646C9, mission.Slot.DELIGHT_PANDORA_WAVE_3_SQUAD_815646C9),
            },
        },
        {
            state = mission.states.STATE_81503E69_0020_0000_815647F2,
            region = 256,
            patrol = {
                unit(mission.Squad.SQ_DEFENDER_0, mission.Slot.SQ_DEFENDER_0),
                unit(mission.Squad.SQ_DEFENDER_1, mission.Slot.SQ_DEFENDER_1),
                unit(mission.Squad.SQ_NIGHTMARE_81573AE7, mission.Slot.SQ_NIGHTMARE_81573AE7),
                unit(mission.Squad.SQ_WIZARD_81573AE7, mission.Slot.SQ_WIZARD_81573AE7),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_81573A77,
                    objective = mission.Slot.SPF_MINOTAUR_CHAMPION_OBJ_CHAMPION,
                    squads = {
                        unit(mission.Squad.SPF_MINOTAUR_CHAMPION_SQ_HOBGOBLINS, mission.Slot.SPF_MINOTAUR_CHAMPION_SQ_HOBGOBLINS),
                        unit(mission.Squad.SPF_MINOTAUR_CHAMPION_SQ_KNIGHTS, mission.Slot.SPF_MINOTAUR_CHAMPION_SQ_KNIGHTS),
                        unit(mission.Squad.SPF_MINOTAUR_CHAMPION_SQ_MINOTAURS, mission.Slot.SPF_MINOTAUR_CHAMPION_SQ_MINOTAURS),
                        unit(mission.Squad.SPF_MINOTAUR_CHAMPION_SQ_OGRES, mission.Slot.SPF_MINOTAUR_CHAMPION_SQ_OGRES),
                    },
                    chest = {
                        mission.Slot.SPF_MINOTAUR_CHAMPION_O_CHEST,
                    },
                },
            },
        },
    }
end
