-- Generated from installed mission data. Do not edit.
-- Zones are authored state rows; population and event sites come from the slice sets.
return function(mission, freeroam)
    local unit = freeroam.unit
    return {
        {
            state = mission.states.STATE_80F1404D_0000_0000_80F14038,
            region = 0,
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1CE6B,
                    objective = mission.Slot.PF_INF_RUSH_INTRO_TK_1_OBJECTIVE_80F1CE6B,
                    squads = {
                        unit(mission.Squad.SQ_PINNACLE_INF_L_80F1CE6B, mission.Slot.SQ_PINNACLE_INF_L_80F1CE6B),
                        unit(mission.Squad.SQ_PINNACLE_INF_M, mission.Slot.SQ_PINNACLE_INF_M),
                        unit(mission.Squad.SQ_PINNACLE_INF_R_80F1CE6B, mission.Slot.SQ_PINNACLE_INF_R_80F1CE6B),
                        unit(mission.Squad.SQ_PINNACLE_L, mission.Slot.SQ_PINNACLE_L),
                        unit(mission.Squad.SQ_PINNACLE_R, mission.Slot.SQ_PINNACLE_R),
                        unit(mission.Squad.SQ_PINNACLE_SCREEB_L, mission.Slot.SQ_PINNACLE_SCREEB_L),
                        unit(mission.Squad.SQ_PINNACLE_SCREEB_M, mission.Slot.SQ_PINNACLE_SCREEB_M),
                        unit(mission.Squad.SQ_PINNACLE_SCREEB_R, mission.Slot.SQ_PINNACLE_SCREEB_R),
                    },
                    chest = {
                        mission.Slot.PIT_CHEST_CHEST_PINNACLE_OBJECT_80F1CE6B,
                        mission.Slot.PIT_CHEST_CHEST_TIER0_OBJECT_80F1CE6B,
                        mission.Slot.PIT_CHEST_CHEST_TIER1_OBJECT_80F1CE6B,
                        mission.Slot.PIT_CHEST_CHEST_TIER2_OBJECT_80F1CE6B,
                        mission.Slot.PIT_CHEST_CHEST_TIER3_OBJECT_80F1CE6B,
                        mission.Slot.PIT_CHEST_SPAWN_FX_OBJECT_80F1CE6B,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1D379,
                    objective = mission.Slot.PF_INF_RUSH_INTRO_TK_1_OBJECTIVE_80F1D379,
                    squads = {
                        unit(mission.Squad.SQ_PINNACLE_80F1D379, mission.Slot.SQ_PINNACLE_80F1D379),
                        unit(mission.Squad.SQ_PINNACLE_ANCHOR_L_80F1D379, mission.Slot.SQ_PINNACLE_ANCHOR_L_80F1D379),
                        unit(mission.Squad.SQ_PINNACLE_ANCHOR_R_80F1D379, mission.Slot.SQ_PINNACLE_ANCHOR_R_80F1D379),
                        unit(mission.Squad.SQ_PINNACLE_INF_L_80F1D379, mission.Slot.SQ_PINNACLE_INF_L_80F1D379),
                        unit(mission.Squad.SQ_PINNACLE_INF_R_80F1D379, mission.Slot.SQ_PINNACLE_INF_R_80F1D379),
                        unit(mission.Squad.SQ_PINNACLE_WELL_1, mission.Slot.SQ_PINNACLE_WELL_1),
                        unit(mission.Squad.SQ_PINNACLE_WELL_2, mission.Slot.SQ_PINNACLE_WELL_2),
                        unit(mission.Squad.SQ_PINNACLE_WELL_3, mission.Slot.SQ_PINNACLE_WELL_3),
                    },
                    chest = {
                        mission.Slot.PIT_CHEST_CHEST_PINNACLE_OBJECT_80F1D379,
                        mission.Slot.PIT_CHEST_CHEST_TIER0_OBJECT_80F1D379,
                        mission.Slot.PIT_CHEST_CHEST_TIER1_OBJECT_80F1D379,
                        mission.Slot.PIT_CHEST_CHEST_TIER2_OBJECT_80F1D379,
                        mission.Slot.PIT_CHEST_CHEST_TIER3_OBJECT_80F1D379,
                        mission.Slot.PIT_CHEST_SPAWN_FX_OBJECT_80F1D379,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1D8AC,
                    objective = mission.Slot.PF_INF_RUSH_INTRO_TK_1_OBJECTIVE_80F1D8AC,
                    squads = {
                        unit(mission.Squad.SQ_PINNACLE_80F1D8AC, mission.Slot.SQ_PINNACLE_80F1D8AC),
                        unit(mission.Squad.SQ_PINNACLE_ANCHOR_L_80F1D8AC, mission.Slot.SQ_PINNACLE_ANCHOR_L_80F1D8AC),
                        unit(mission.Squad.SQ_PINNACLE_ANCHOR_R_80F1D8AC, mission.Slot.SQ_PINNACLE_ANCHOR_R_80F1D8AC),
                        unit(mission.Squad.SQ_PINNACLE_INF_L_80F1D8AC, mission.Slot.SQ_PINNACLE_INF_L_80F1D8AC),
                        unit(mission.Squad.SQ_PINNACLE_INF_R_80F1D8AC, mission.Slot.SQ_PINNACLE_INF_R_80F1D8AC),
                        unit(mission.Squad.SQ_PINNACLE_TURRET_1, mission.Slot.SQ_PINNACLE_TURRET_1),
                        unit(mission.Squad.SQ_PINNACLE_TURRET_2, mission.Slot.SQ_PINNACLE_TURRET_2),
                        unit(mission.Squad.SQ_PINNACLE_TURRET_3, mission.Slot.SQ_PINNACLE_TURRET_3),
                        unit(mission.Squad.SQ_PINNACLE_TURRET_4, mission.Slot.SQ_PINNACLE_TURRET_4),
                    },
                    chest = {
                        mission.Slot.PIT_CHEST_CHEST_PINNACLE_OBJECT_80F1D8AC,
                        mission.Slot.PIT_CHEST_CHEST_TIER0_OBJECT_80F1D8AC,
                        mission.Slot.PIT_CHEST_CHEST_TIER1_OBJECT_80F1D8AC,
                        mission.Slot.PIT_CHEST_CHEST_TIER2_OBJECT_80F1D8AC,
                        mission.Slot.PIT_CHEST_CHEST_TIER3_OBJECT_80F1D8AC,
                        mission.Slot.PIT_CHEST_SPAWN_FX_OBJECT_80F1D8AC,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80F1404D_0001_0000_80F14039,
            region = 8,
            patrol = {
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_CAPTAIN_80F2402B, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_CAPTAIN_80F2402B),
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_1_80F2402B, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_1_80F2402B),
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_80F2402B, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_80F2402B),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D909, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D909),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D929, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D929),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D947, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D947),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D964, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D964),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9A4, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9A4),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9C1, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9C1),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9DE, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9DE),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9FB, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1D9FB),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA1E, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA1E),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA3B, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA3B),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA61, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA61),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA81, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DA81),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAA4, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAA4),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAC4, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAC4),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAE2, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAE2),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAFF, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DAFF),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB1C, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB1C),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB3F, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB3F),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB5C, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB5C),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB9A, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DB9A),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DBB7, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1DBB7),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1DDC9,
                    objective = mission.Slot.DREAMING_CITY_BOSS_SPAWN_EVENT_1_OBJ_A,
                    squads = {
                        unit(mission.Squad.DREAMING_CITY_BOSS_SPAWN_EVENT_1_SQ_SQUAD_A_0, mission.Slot.DREAMING_CITY_BOSS_SPAWN_EVENT_1_SQ_SQUAD_A_0),
                        unit(mission.Squad.DREAMING_CITY_BOSS_SPAWN_EVENT_1_SQ_SQUAD_B_0, mission.Slot.DREAMING_CITY_BOSS_SPAWN_EVENT_1_SQ_SQUAD_B_0),
                    },
                    chest = {
                        mission.Slot.DREAMING_CITY_BOSS_SPAWN_EVENT_1_O_CHEST_A,
                        mission.Slot.DREAMING_CITY_BOSS_SPAWN_EVENT_1_O_CHEST_B,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1DFF8,
                    objective = mission.Slot.PF_EVENT_SOUL_HARVESTER_OBJ_EVENT_MAIN,
                    squads = {
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_ARC_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_ARC_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_BARON, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_BARON),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_ARC_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_ARC_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_DREG, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_DREG),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_EXPLODER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_EXPLODER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_ARC_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_ARC_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_DREG, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_DREG),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_MARAUDER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_MARAUDER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SCOURGE, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SCOURGE),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SNIPER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SNIPER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SOLAR_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SOLAR_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VANDAL, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VANDAL),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VOID_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VOID_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_WRETCH, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_WRETCH),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MARAUDER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_MARAUDER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SCOURGE, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SCOURGE),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SNIPER, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SNIPER),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SOLAR_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_SOLAR_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VANDAL, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VANDAL),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VOID_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_VOID_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_WRETCH, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_FODDER_WRETCH),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_MONGREL, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_MONGREL),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_SOLAR_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_SOLAR_CAPTAIN),
                        unit(mission.Squad.PF_EVENT_SOUL_HARVESTER_SQ_VOID_CAPTAIN, mission.Slot.PF_EVENT_SOUL_HARVESTER_SQ_VOID_CAPTAIN),
                    },
                    chest = {
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_CONVOY_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER0_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER1_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER2_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER3_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER4_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.PF_EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_VEX_PRISONER_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F24336,
                    objective = mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_FLOATER_OBJECTIVE_80F24336,
                    squads = {
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_ANCHOR_SQUAD_80F24336, mission.Slot.TAKEN_INFECTION_CORE_EASY_ANCHOR_SQUAD_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_FLOATER_SQUAD_80F24336, mission.Slot.TAKEN_INFECTION_CORE_EASY_FLOATER_SQUAD_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_0_80F24336, mission.Slot.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_0_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_1_80F24336, mission.Slot.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_1_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_ANCHOR_SQUAD_80F24336, mission.Slot.TAKEN_INFECTION_CORE_HARD_ANCHOR_SQUAD_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_FLOATER_SQUAD_80F24336, mission.Slot.TAKEN_INFECTION_CORE_HARD_FLOATER_SQUAD_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_0_80F24336, mission.Slot.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_0_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_1_80F24336, mission.Slot.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_1_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_2_80F24336, mission.Slot.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_2_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_ANCHOR_SQUAD_80F24336, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_ANCHOR_SQUAD_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_FLOATER_SQUAD_80F24336, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_FLOATER_SQUAD_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_0_80F24336, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_0_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_1_80F24336, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_1_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_2_80F24336, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_2_80F24336),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_ULTRA_SQUAD_80F24336, mission.Slot.TAKEN_INFECTION_CORE_ULTRA_SQUAD_80F24336),
                    },
                    chest = {
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_SPAWN_FX_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_SPAWN_FX_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F24336,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80F24336,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F24367,
                    objective = mission.Slot.EVENT_SILENT_SPAWNER_1_OBJ_80F24367,
                    squads = {
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_ANCHOR_80F24367, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_ANCHOR_80F24367),
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_BOSS_80F24367, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_BOSS_80F24367),
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_FODDER_80F24367, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_FODDER_80F24367),
                    },
                    chest = {
                        mission.Slot.EVENT_SILENT_SPAWNER_1_REWARD_CHEST_OBJECT_80F24367,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80F1404D_0002_0000_80F1403A,
            region = 16,
            patrol = {
                unit(mission.Squad.PF_ENCOUNTER_SQUAD_0_80F248E0, mission.Slot.PF_ENCOUNTER_SQUAD_0_80F248E0),
                unit(mission.Squad.PF_ENCOUNTER_SQUAD_1_80F248E0, mission.Slot.PF_ENCOUNTER_SQUAD_1_80F248E0),
                unit(mission.Squad.PF_ENCOUNTER_SQUAD_2, mission.Slot.PF_ENCOUNTER_SQUAD_2),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24511, mission.Slot.PF_SIMPLE_SQUAD_0_80F24511),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24531, mission.Slot.PF_SIMPLE_SQUAD_0_80F24531),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24551, mission.Slot.PF_SIMPLE_SQUAD_0_80F24551),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24597, mission.Slot.PF_SIMPLE_SQUAD_0_80F24597),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F245B8, mission.Slot.PF_SIMPLE_SQUAD_0_80F245B8),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F245D7, mission.Slot.PF_SIMPLE_SQUAD_0_80F245D7),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F245F4, mission.Slot.PF_SIMPLE_SQUAD_0_80F245F4),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24614, mission.Slot.PF_SIMPLE_SQUAD_0_80F24614),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24657, mission.Slot.PF_SIMPLE_SQUAD_0_80F24657),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24676, mission.Slot.PF_SIMPLE_SQUAD_0_80F24676),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24728, mission.Slot.PF_SIMPLE_SQUAD_0_80F24728),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24748, mission.Slot.PF_SIMPLE_SQUAD_0_80F24748),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F24767, mission.Slot.PF_SIMPLE_SQUAD_0_80F24767),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F24577, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F24577),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F24637, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F24637),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F24577, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F24577),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F24637, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F24637),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_2_80F24577, mission.Slot.PF_SIMPLE_WAVE_SQUAD_2_80F24577),
                unit(mission.Squad.SQ_CENTER_PHALANX, mission.Slot.SQ_CENTER_PHALANX),
                unit(mission.Squad.SQ_DARKBLADE_80F244F4, mission.Slot.SQ_DARKBLADE_80F244F4),
                unit(mission.Squad.SQ_FORWARD_RUSHERS, mission.Slot.SQ_FORWARD_RUSHERS),
            },
        },
        {
            state = mission.states.STATE_80F1404D_0008_0000_80F14040,
            region = 64,
            -- Lost Sector in bubble 8.
            sector = {
                boss = mission.Slot.SQ_ASCENDANT_BOSS,
                squads = {
                    unit(mission.Squad.SQ_ASCENDANT_BOSS, mission.Slot.SQ_ASCENDANT_BOSS),
                    unit(mission.Squad.SQ_BEACH_GREETERS, mission.Slot.SQ_BEACH_GREETERS),
                    unit(mission.Squad.SQ_BOOPERS, mission.Slot.SQ_BOOPERS),
                    unit(mission.Squad.SQ_CAPTAIN_1, mission.Slot.SQ_CAPTAIN_1),
                    unit(mission.Squad.SQ_CAPTAIN_2, mission.Slot.SQ_CAPTAIN_2),
                    unit(mission.Squad.SQ_CAPTAIN_3, mission.Slot.SQ_CAPTAIN_3),
                    unit(mission.Squad.SQ_CRAB_1, mission.Slot.SQ_CRAB_1),
                    unit(mission.Squad.SQ_CRAB_10, mission.Slot.SQ_CRAB_10),
                    unit(mission.Squad.SQ_CRAB_2, mission.Slot.SQ_CRAB_2),
                    unit(mission.Squad.SQ_CRAB_3, mission.Slot.SQ_CRAB_3),
                    unit(mission.Squad.SQ_CRAB_4, mission.Slot.SQ_CRAB_4),
                    unit(mission.Squad.SQ_CRAB_5, mission.Slot.SQ_CRAB_5),
                    unit(mission.Squad.SQ_CRAB_6, mission.Slot.SQ_CRAB_6),
                    unit(mission.Squad.SQ_CRAB_7, mission.Slot.SQ_CRAB_7),
                    unit(mission.Squad.SQ_CRAB_8, mission.Slot.SQ_CRAB_8),
                    unit(mission.Squad.SQ_CRAB_9, mission.Slot.SQ_CRAB_9),
                    unit(mission.Squad.SQ_DOOR_GUARDS, mission.Slot.SQ_DOOR_GUARDS),
                    unit(mission.Squad.SQ_FLOOR_ANCHOR, mission.Slot.SQ_FLOOR_ANCHOR),
                    unit(mission.Squad.SQ_FLOOR_L, mission.Slot.SQ_FLOOR_L),
                    unit(mission.Squad.SQ_FLOOR_R, mission.Slot.SQ_FLOOR_R),
                    unit(mission.Squad.SQ_INTRO_80F25045, mission.Slot.SQ_INTRO_80F25045),
                    unit(mission.Squad.SQ_LEDGE_80F25045, mission.Slot.SQ_LEDGE_80F25045),
                    unit(mission.Squad.SQ_SHADOW_THRALL_80F25045, mission.Slot.SQ_SHADOW_THRALL_80F25045),
                    unit(mission.Squad.SQ_SNIPER_1_80F25045, mission.Slot.SQ_SNIPER_1_80F25045),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80F25086,
                },
            },
        },
        {
            state = mission.states.STATE_80F1404D_0009_0000_80F14041,
            region = 72,
            -- Lost Sector in bubble 9.
            sector = {
                boss = mission.Slot.SQ_BOSS_80F25324,
                squads = {
                    unit(mission.Squad.SQ_ANCHOR_80F25360, mission.Slot.SQ_ANCHOR_80F25360),
                    unit(mission.Squad.SQ_BOSS_80F25324, mission.Slot.SQ_BOSS_80F25324),
                    unit(mission.Squad.SQ_BOUNCER_1, mission.Slot.SQ_BOUNCER_1),
                    unit(mission.Squad.SQ_BOUNCER_2, mission.Slot.SQ_BOUNCER_2),
                    unit(mission.Squad.SQ_DARKBLADE_80F25324, mission.Slot.SQ_DARKBLADE_80F25324),
                    unit(mission.Squad.SQ_HALL_A, mission.Slot.SQ_HALL_A),
                    unit(mission.Squad.SQ_HALL_B, mission.Slot.SQ_HALL_B),
                    unit(mission.Squad.SQ_INF_L, mission.Slot.SQ_INF_L),
                    unit(mission.Squad.SQ_INF_R, mission.Slot.SQ_INF_R),
                    unit(mission.Squad.SQ_INTRO_80F25360, mission.Slot.SQ_INTRO_80F25360),
                    unit(mission.Squad.SQ_LEDGE_80F25360, mission.Slot.SQ_LEDGE_80F25360),
                    unit(mission.Squad.SQ_REAR, mission.Slot.SQ_REAR),
                    unit(mission.Squad.SQ_SHADOW_THRALL_1_80F25324, mission.Slot.SQ_SHADOW_THRALL_1_80F25324),
                    unit(mission.Squad.SQ_SHADOW_THRALL_2_80F25324, mission.Slot.SQ_SHADOW_THRALL_2_80F25324),
                    unit(mission.Squad.SQ_SHADOW_THRALL_3_80F25324, mission.Slot.SQ_SHADOW_THRALL_3_80F25324),
                    unit(mission.Squad.SQ_SHADOW_THRALL_4, mission.Slot.SQ_SHADOW_THRALL_4),
                    unit(mission.Squad.SQ_SHADOW_THRALL_5, mission.Slot.SQ_SHADOW_THRALL_5),
                    unit(mission.Squad.SQ_SHADOW_THRALL_6, mission.Slot.SQ_SHADOW_THRALL_6),
                    unit(mission.Squad.SQ_SHRIEKER_1, mission.Slot.SQ_SHRIEKER_1),
                    unit(mission.Squad.SQ_SHRIEKER_2, mission.Slot.SQ_SHRIEKER_2),
                    unit(mission.Squad.SQ_SHRIEKER_3, mission.Slot.SQ_SHRIEKER_3),
                    unit(mission.Squad.SQ_SHRIEKER_4, mission.Slot.SQ_SHRIEKER_4),
                    unit(mission.Squad.SQ_SHRIEKER_5, mission.Slot.SQ_SHRIEKER_5),
                    unit(mission.Squad.SQ_SHRIEKER_6, mission.Slot.SQ_SHRIEKER_6),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80F25376,
                },
            },
        },
        {
            state = mission.states.STATE_80F1404D_000A_0000_80F14042,
            region = 80,
            -- Lost Sector in bubble 10.
            sector = {
                boss = mission.Slot.SQ_BOSS_80F255C4,
                squads = {
                    unit(mission.Squad.SQ_1, mission.Slot.SQ_1),
                    unit(mission.Squad.SQ_2, mission.Slot.SQ_2),
                    unit(mission.Squad.SQ_3, mission.Slot.SQ_3),
                    unit(mission.Squad.SQ_ANCHOR_80F255C4, mission.Slot.SQ_ANCHOR_80F255C4),
                    unit(mission.Squad.SQ_BOSS_80F255C4, mission.Slot.SQ_BOSS_80F255C4),
                    unit(mission.Squad.SQ_DARKBLADE_80F255C4, mission.Slot.SQ_DARKBLADE_80F255C4),
                    unit(mission.Squad.SQ_FRONT_1, mission.Slot.SQ_FRONT_1),
                    unit(mission.Squad.SQ_FRONT_1_TURRET, mission.Slot.SQ_FRONT_1_TURRET),
                    unit(mission.Squad.SQ_FRONT_2, mission.Slot.SQ_FRONT_2),
                    unit(mission.Squad.SQ_FRONT_2_TURRET, mission.Slot.SQ_FRONT_2_TURRET),
                    unit(mission.Squad.SQ_FRONT_3, mission.Slot.SQ_FRONT_3),
                    unit(mission.Squad.SQ_FRONT_3_TURRET, mission.Slot.SQ_FRONT_3_TURRET),
                    unit(mission.Squad.SQ_PHALANX, mission.Slot.SQ_PHALANX),
                    unit(mission.Squad.SQ_PSION_1, mission.Slot.SQ_PSION_1),
                    unit(mission.Squad.SQ_PSION_2, mission.Slot.SQ_PSION_2),
                    unit(mission.Squad.SQ_PSION_3, mission.Slot.SQ_PSION_3),
                    unit(mission.Squad.SQ_SHADOW_THRALL_80F255C4, mission.Slot.SQ_SHADOW_THRALL_80F255C4),
                    unit(mission.Squad.SQ_SNIPE_80F255C4, mission.Slot.SQ_SNIPE_80F255C4),
                },
                chest = {
                    mission.Slot.REGION_CHEST_MAJOR1_80F255FC,
                },
            },
        },
        {
            state = mission.states.STATE_80F1404D_000B_0000_80F14043,
            region = 88,
            patrol = {
                unit(mission.Squad.PF_ENCOUNTER_SQUAD_0_80F25C42, mission.Slot.PF_ENCOUNTER_SQUAD_0_80F25C42),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F25737, mission.Slot.PF_SIMPLE_SQUAD_0_80F25737),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F2577A, mission.Slot.PF_SIMPLE_SQUAD_0_80F2577A),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F257BD, mission.Slot.PF_SIMPLE_SQUAD_0_80F257BD),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F257DC, mission.Slot.PF_SIMPLE_SQUAD_0_80F257DC),
                unit(mission.Squad.PF_SIMPLE_SQUAD_0_80F2583C, mission.Slot.PF_SIMPLE_SQUAD_0_80F2583C),
                unit(mission.Squad.PF_SIMPLE_SQUAD_1_80F256D4, mission.Slot.PF_SIMPLE_SQUAD_1_80F256D4),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F256F7, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F256F7),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F2575A, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F2575A),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F2579D, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F2579D),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F2587F, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F2587F),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F256F7, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F256F7),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F2575A, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F2575A),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F2579D, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F2579D),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F2587F, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F2587F),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_2_80F2575A, mission.Slot.PF_SIMPLE_WAVE_SQUAD_2_80F2575A),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_2_80F2587F, mission.Slot.PF_SIMPLE_WAVE_SQUAD_2_80F2587F),
                unit(mission.Squad.SQ_ACOLYTE_1, mission.Slot.SQ_ACOLYTE_1),
                unit(mission.Squad.SQ_ACOLYTE_2, mission.Slot.SQ_ACOLYTE_2),
                unit(mission.Squad.SQ_KNIGHT_1, mission.Slot.SQ_KNIGHT_1),
                unit(mission.Squad.SQ_KNIGHT_2, mission.Slot.SQ_KNIGHT_2),
                unit(mission.Squad.SQ_KNIGHT_3, mission.Slot.SQ_KNIGHT_3),
                unit(mission.Squad.SQ_PATH0_0, mission.Slot.SQ_PATH0_0),
                unit(mission.Squad.SQ_PATH0_1, mission.Slot.SQ_PATH0_1),
            },
        },
        {
            state = mission.states.STATE_80F1404D_0012_0000_80F1404A,
            region = 144,
            patrol = {
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_CAPTAIN_80F1C606, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_CAPTAIN_80F1C606),
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_1_80F1C606, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_1_80F1C606),
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_80F1C606, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_80F1C606),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE03, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE03),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE26, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE26),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE4C, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE4C),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE69, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE69),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE86, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BE86),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BEA6, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BEA6),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BEC6, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BEC6),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BEE5, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BEE5),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF05, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF05),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF28, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF28),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF4B, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF4B),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF99, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BF99),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BFBE, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BFBE),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BFDA, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BFDA),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BFF6, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1BFF6),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C016, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C016),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C035, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C035),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C054, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C054),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C073, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C073),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C095, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C095),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C0B7, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F1C0B7),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1C211,
                    objective = mission.Slot.EVENT_CONVOY_CORE_BALL_CONVOY_POINTS_BALL_0_OBJECTIVE,
                    squads = {
                        unit(mission.Squad.EVENT_CONVOY_CORE_BALL_SQ_BOSS, mission.Slot.EVENT_CONVOY_CORE_BALL_SQ_BOSS),
                    },
                    chest = {
                        mission.Slot.EVENT_CONVOY_CORE_BALL_O_CHEST_0,
                        mission.Slot.EVENT_CONVOY_CORE_BALL_O_CHEST_1,
                        mission.Slot.EVENT_CONVOY_CORE_BALL_O_CHEST_2,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1C5D3,
                    objective = mission.Slot.EVENT_SOUL_HARVESTER_OBJ_EVENT_MAIN,
                    squads = {
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_ARC_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_ARC_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_BARON, mission.Slot.EVENT_SOUL_HARVESTER_SQ_BARON),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_ARC_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_ARC_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_DREG, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_DREG),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_EXPLODER, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_EXPLODER),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_ARC_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_ARC_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_DREG, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_DREG),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_MARAUDER, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_MARAUDER),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SCOURGE, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SCOURGE),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SNIPER, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SNIPER),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SOLAR_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_SOLAR_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VANDAL, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VANDAL),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VOID_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_VOID_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_WRETCH, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MAJOR_WRETCH),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_MARAUDER, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_MARAUDER),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_SCOURGE, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_SCOURGE),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_SNIPER, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_SNIPER),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_SOLAR_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_SOLAR_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_VANDAL, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_VANDAL),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_VOID_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_VOID_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_FODDER_WRETCH, mission.Slot.EVENT_SOUL_HARVESTER_SQ_FODDER_WRETCH),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_MONGREL, mission.Slot.EVENT_SOUL_HARVESTER_SQ_MONGREL),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_SOLAR_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_SOLAR_CAPTAIN),
                        unit(mission.Squad.EVENT_SOUL_HARVESTER_SQ_VOID_CAPTAIN, mission.Slot.EVENT_SOUL_HARVESTER_SQ_VOID_CAPTAIN),
                    },
                    chest = {
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_AMBIENT_AMBUSH_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_CONVOY_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_COWARDLY_MAJOR_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_FALLEN_REFINERY_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER0_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER1_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER2_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER3_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_TIER4_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_VEX_CANNON_OBJECT,
                        mission.Slot.EVENT_SOUL_HARVESTER_PF_REWARD_CHEST_VEX_PRISONER_OBJECT,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1C8DF,
                    objective = mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_FLOATER_OBJECTIVE_80F1C8DF,
                    squads = {
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_ANCHOR_SQUAD_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_EASY_ANCHOR_SQUAD_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_FLOATER_SQUAD_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_EASY_FLOATER_SQUAD_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_0_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_0_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_1_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_EASY_TETHER_SQUAD_1_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_ANCHOR_SQUAD_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_HARD_ANCHOR_SQUAD_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_FLOATER_SQUAD_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_HARD_FLOATER_SQUAD_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_0_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_0_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_1_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_1_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_2_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_HARD_TETHER_SQUAD_2_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_ANCHOR_SQUAD_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_ANCHOR_SQUAD_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_FLOATER_SQUAD_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_FLOATER_SQUAD_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_0_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_0_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_1_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_1_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_2_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_MEDIUM_TETHER_SQUAD_2_80F1C8DF),
                        unit(mission.Squad.TAKEN_INFECTION_CORE_ULTRA_SQUAD_80F1C8DF, mission.Slot.TAKEN_INFECTION_CORE_ULTRA_SQUAD_80F1C8DF),
                    },
                    chest = {
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_0_CHEST_PREFAB_SPAWN_FX_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_1_CHEST_PREFAB_SPAWN_FX_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_AMBIENT_AMBUSH_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_CONVOY_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_COWARDLY_MAJOR_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_FALLEN_REFINERY_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER0_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER1_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER2_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER3_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_TIER4_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_VEX_CANNON_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_CHEST_VEX_PRISONER_OBJECT_80F1C8DF,
                        mission.Slot.TAKEN_INFECTION_CORE_BLIGHT_GROUPS_2_CHEST_PREFAB_SPAWN_FX_OBJECT_80F1C8DF,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F1C910,
                    objective = mission.Slot.EVENT_SILENT_SPAWNER_1_OBJ_80F1C910,
                    squads = {
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_ANCHOR_80F1C910, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_ANCHOR_80F1C910),
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_BOSS_80F1C910, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_BOSS_80F1C910),
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_FODDER_80F1C910, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_FODDER_80F1C910),
                    },
                    chest = {
                        mission.Slot.EVENT_SILENT_SPAWNER_1_REWARD_CHEST_OBJECT_80F1C910,
                    },
                },
            },
        },
        {
            state = mission.states.STATE_80F1404D_0013_0000_80F1404B,
            region = 152,
            patrol = {
                unit(mission.Squad.PF_ENCOUNTER_SQUAD_0_80F285D8, mission.Slot.PF_ENCOUNTER_SQUAD_0_80F285D8),
                unit(mission.Squad.PF_ENCOUNTER_SQUAD_1_80F285D8, mission.Slot.PF_ENCOUNTER_SQUAD_1_80F285D8),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_0_80F281B8, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_0_80F281B8),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_0_80F281D8, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_0_80F281D8),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_0_80F28258, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_0_80F28258),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_0_80F28297, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_0_80F28297),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_0_80F282B7, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_0_80F282B7),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_0_80F282F7, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_0_80F282F7),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_0_80F28442, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_0_80F28442),
                unit(mission.Squad.PF_GATEWAY_SIMPLE_SQUAD_1_80F28218, mission.Slot.PF_GATEWAY_SIMPLE_SQUAD_1_80F28218),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F2831D, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F2831D),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_0_80F28468, mission.Slot.PF_SIMPLE_WAVE_SQUAD_0_80F28468),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F2831D, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F2831D),
                unit(mission.Squad.PF_SIMPLE_WAVE_SQUAD_1_80F28468, mission.Slot.PF_SIMPLE_WAVE_SQUAD_1_80F28468),
                unit(mission.Squad.SQUAD_MARA_12TH_WEEK, mission.Slot.SQUAD_MARA_12TH_WEEK),
                unit(mission.Squad.SQUAD_MARA_15TH_WEEK, mission.Slot.SQUAD_MARA_15TH_WEEK),
                unit(mission.Squad.SQUAD_MARA_18TH_WEEK, mission.Slot.SQUAD_MARA_18TH_WEEK),
                unit(mission.Squad.SQUAD_MARA_21ST_WEEK, mission.Slot.SQUAD_MARA_21ST_WEEK),
                unit(mission.Squad.SQUAD_MARA_3RD_WEEK, mission.Slot.SQUAD_MARA_3RD_WEEK),
                unit(mission.Squad.SQUAD_MARA_6TH_WEEK, mission.Slot.SQUAD_MARA_6TH_WEEK),
                unit(mission.Squad.SQUAD_MARA_9TH_WEEK, mission.Slot.SQUAD_MARA_9TH_WEEK),
                unit(mission.Squad.SQ_SHADOW_THRALL_1_80F28198, mission.Slot.SQ_SHADOW_THRALL_1_80F28198),
                unit(mission.Squad.SQ_SHADOW_THRALL_2_80F28198, mission.Slot.SQ_SHADOW_THRALL_2_80F28198),
                unit(mission.Squad.SQ_SHADOW_THRALL_3_80F28198, mission.Slot.SQ_SHADOW_THRALL_3_80F28198),
            },
        },
        {
            state = mission.states.STATE_80F1404D_0014_0000_80F1404C,
            region = 160,
            patrol = {
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_CAPTAIN_80F28944, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_CAPTAIN_80F28944),
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_1_80F28944, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_1_80F28944),
                unit(mission.Squad.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_80F28944, mission.Slot.AWOKEN_OUTPOST_1_SQ_AWOKEN_GUARD_80F28944),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2862D, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2862D),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2864C, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2864C),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2866F, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2866F),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F28692, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F28692),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F286B5, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F286B5),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F286D5, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F286D5),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F286F4, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F286F4),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F28717, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F28717),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2873A, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2873A),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287A0, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287A0),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287BF, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287BF),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287DF, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287DF),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287FE, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F287FE),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2881E, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2881E),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2883D, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_0_80F2883D),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F2862D, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F2862D),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F2864C, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F2864C),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F2866F, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F2866F),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F28692, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F28692),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F286B5, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F286B5),
                unit(mission.Squad.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F286D5, mission.Slot.PF2_SIMPLE_ENCOUNTER_SQUAD_1_80F286D5),
            },
            events = {
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F28A98,
                    objective = mission.Slot.EVENT_SILENT_SPAWNER_1_OBJ_80F28A98,
                    squads = {
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_ANCHOR_80F28A98, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_ANCHOR_80F28A98),
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_BOSS_80F28A98, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_BOSS_80F28A98),
                        unit(mission.Squad.EVENT_SILENT_SPAWNER_1_SQ_FODDER_80F28A98, mission.Slot.EVENT_SILENT_SPAWNER_1_SQ_FODDER_80F28A98),
                    },
                    chest = {
                        mission.Slot.EVENT_SILENT_SPAWNER_1_REWARD_CHEST_OBJECT_80F28A98,
                    },
                },
                {
                    sensor = mission.Slot.M_PUBLIC_EVENT_SENSOR_80F28D47,
                    objective = mission.Slot.TOWER_DEFENSE_LANE_0_OBJ,
                    squads = {
                        unit(mission.Squad.SQ_INTRO_CARRY_OBJECT, mission.Slot.SQ_INTRO_CARRY_OBJECT),
                        unit(mission.Squad.SQ_INTRO_FODDER, mission.Slot.SQ_INTRO_FODDER),
                        unit(mission.Squad.SQ_INTRO_TAKEN_FODDER, mission.Slot.SQ_INTRO_TAKEN_FODDER),
                        unit(mission.Squad.SQ_TAKEN_ANCHOR_0, mission.Slot.SQ_TAKEN_ANCHOR_0),
                        unit(mission.Squad.SQ_TAKEN_ANCHOR_1, mission.Slot.SQ_TAKEN_ANCHOR_1),
                        unit(mission.Squad.SQ_TAKEN_ANCHOR_2, mission.Slot.SQ_TAKEN_ANCHOR_2),
                        unit(mission.Squad.SQ_TAKEN_ANCHOR_3, mission.Slot.SQ_TAKEN_ANCHOR_3),
                        unit(mission.Squad.SQ_TAKEN_ANCHOR_4, mission.Slot.SQ_TAKEN_ANCHOR_4),
                        unit(mission.Squad.SQ_TAKEN_ANCHOR_5, mission.Slot.SQ_TAKEN_ANCHOR_5),
                        unit(mission.Squad.SQ_TAKEN_BOSS, mission.Slot.SQ_TAKEN_BOSS),
                        unit(mission.Squad.SQ_TAKEN_FODDER_0, mission.Slot.SQ_TAKEN_FODDER_0),
                        unit(mission.Squad.SQ_TAKEN_FODDER_1, mission.Slot.SQ_TAKEN_FODDER_1),
                        unit(mission.Squad.SQ_TAKEN_FODDER_2, mission.Slot.SQ_TAKEN_FODDER_2),
                        unit(mission.Squad.SQ_TAKEN_WIZARD, mission.Slot.SQ_TAKEN_WIZARD),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_1, mission.Slot.SQ_TAKEN_WIZARD_1),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_2, mission.Slot.SQ_TAKEN_WIZARD_2),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_3, mission.Slot.SQ_TAKEN_WIZARD_3),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_4, mission.Slot.SQ_TAKEN_WIZARD_4),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_5, mission.Slot.SQ_TAKEN_WIZARD_5),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_HEROIC_TRIGGER, mission.Slot.SQ_TAKEN_WIZARD_HEROIC_TRIGGER),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_HEROIC_TRIGGER_1, mission.Slot.SQ_TAKEN_WIZARD_HEROIC_TRIGGER_1),
                        unit(mission.Squad.SQ_TAKEN_WIZARD_HEROIC_TRIGGER_2, mission.Slot.SQ_TAKEN_WIZARD_HEROIC_TRIGGER_2),
                        unit(mission.Squad.SQ_TEMPLE, mission.Slot.SQ_TEMPLE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_HARD_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_HARD_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_HARD_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_HARD_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_HEAVY_WAVE, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_HEAVY_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_LIGHT_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_LIGHT_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_LIGHT_WAVE, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_LIGHT_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_MEDIUM_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_MEDIUM_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_MEDIUM_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_MEDIUM_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_MID_WAVE, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_MID_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_SCENE_FODDER_0, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_SCENE_FODDER_0),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_SCENE_FODDER_1, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_SCENE_FODDER_1),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_SCENE_FODDER_2, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_SCENE_FODDER_2),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_0_SQ_ULTRA, mission.Slot.TOWER_DEFENSE_LANE_0_SQ_ULTRA),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_HARD_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_HARD_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_HARD_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_HARD_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_HEAVY_WAVE, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_HEAVY_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_LIGHT_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_LIGHT_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_LIGHT_WAVE, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_LIGHT_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_MEDIUM_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_MEDIUM_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_MEDIUM_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_MEDIUM_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_MID_WAVE, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_MID_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_SCENE_FODDER_0, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_SCENE_FODDER_0),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_SCENE_FODDER_1, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_SCENE_FODDER_1),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_SCENE_FODDER_2, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_SCENE_FODDER_2),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_1_SQ_ULTRA, mission.Slot.TOWER_DEFENSE_LANE_1_SQ_ULTRA),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_HARD_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_HARD_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_HARD_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_HARD_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_HEAVY_WAVE, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_HEAVY_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_LIGHT_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_LIGHT_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_LIGHT_WAVE, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_LIGHT_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_MEDIUM_CARRY_OBJECT, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_MEDIUM_CARRY_OBJECT),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_MEDIUM_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_MEDIUM_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_MID_WAVE, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_MID_WAVE),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_SCENE_FODDER_0, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_SCENE_FODDER_0),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_SCENE_FODDER_1, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_SCENE_FODDER_1),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_SCENE_FODDER_2, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_SCENE_FODDER_2),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_SNIPER, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_SNIPER),
                        unit(mission.Squad.TOWER_DEFENSE_LANE_2_SQ_ULTRA, mission.Slot.TOWER_DEFENSE_LANE_2_SQ_ULTRA),
                    },
                    chest = {
                        mission.Slot.REWARD_CHEST_PREFAB_CHEST_TIER0_OBJECT,
                        mission.Slot.REWARD_CHEST_PREFAB_CHEST_TIER1_OBJECT,
                        mission.Slot.REWARD_CHEST_PREFAB_CHEST_TIER2_OBJECT,
                        mission.Slot.REWARD_CHEST_PREFAB_CHEST_TIER3_OBJECT,
                        mission.Slot.REWARD_CHEST_PREFAB_CHEST_TIER4_OBJECT,
                        mission.Slot.REWARD_CHEST_PREFAB_SPAWN_FX_OBJECT,
                    },
                },
            },
        },
    }
end
